MLIR: lib/AsmParser/AffineParser.cpp File Reference
AffineParser.cpp File Reference
#include "Parser.h"
#include "mlir/IR/AffineMap.h"
#include "mlir/IR/IntegerSet.h"
#include "llvm/Support/SourceMgr.h"
Enumerations
enum AffineLowPrecOp
Lower precedence ops (all at the same precedence level).
enum AffineHighPrecOp
Higher precedence ops - all at the same precedence level.
Functions
static bool isIdentifier (const Token &token)
Returns true if the given token can be represented as an identifier.
static void parseAffineMapOrIntegerSet (StringRef inputStr, MLIRContext *context, AffineMap &map, IntegerSet &set)
Enumeration Type Documentation
AffineHighPrecOp
enum AffineHighPrecOp
Higher precedence ops - all at the same precedence level.
HNoOp is false in the boolean sense.
Definition at line 34 of file AffineParser.cpp.
AffineLowPrecOp
enum AffineLowPrecOp
Lower precedence ops (all at the same precedence level).
LNoOp is false in the boolean sense.
Definition at line 25 of file AffineParser.cpp.
Function Documentation
isIdentifier()
static bool isIdentifier (const Token & token) static
Returns true if the given token can be represented as an identifier.
Definition at line 269 of file AffineParser.cpp.
References mlir::emitError(), mlir::getAffineDimExpr(), mlir::getAffineSymbolExpr(), mlir::Token::isAny(), and mlir::Token::isKeyword().
parseAffineMapOrIntegerSet()
static void parseAffineMapOrIntegerSet (StringRef inputStr, MLIRContext * context, AffineMap & map, IntegerSet & set) static
Definition at line 737 of file AffineParser.cpp.
References mlir::detail::Parser::emitError(), mlir::Token::getLoc(), mlir::detail::Parser::getToken(), mlir::Token::isNot(), mlir::parseAffineMap(), mlir::detail::Parser::parseAffineMapOrIntegerSetReference(), and mlir::parseIntegerSet().