MLIR: lib/Dialect/Affine/Transforms/AffineLoopInvariantCodeMotion.cpp File Reference
AffineLoopInvariantCodeMotion.cpp File Reference
#include "mlir/Dialect/Affine/Passes.h"
#include "mlir/Analysis/SliceAnalysis.h"
#include "mlir/Dialect/Affine/Analysis/AffineAnalysis.h"
#include "mlir/Dialect/Affine/Analysis/AffineStructures.h"
#include "mlir/Dialect/Affine/Analysis/LoopAnalysis.h"
#include "mlir/Dialect/Affine/Analysis/Utils.h"
#include "mlir/Dialect/Affine/IR/AffineOps.h"
#include "mlir/Dialect/Affine/LoopUtils.h"
#include "mlir/Dialect/Affine/Utils.h"
#include "mlir/Dialect/Arith/IR/Arith.h"
#include "mlir/Dialect/Func/IR/FuncOps.h"
#include "mlir/IR/AffineExpr.h"
#include "mlir/IR/AffineMap.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/Matchers.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/DenseSet.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include "mlir/Dialect/Affine/Passes.h.inc"
Namespaces
mlir
Include the generated interface declarations.
Macros
#define GEN_PASS_DEF_AFFINELOOPINVARIANTCODEMOTION
#define DEBUG_TYPE "licm"
Functions
static bool checkInvarianceOfNestedIfOps (Operation *op, Value indVar, ValueRange iterArgs, SmallPtrSetImpl< Operation *> &opsWithUsers, SmallPtrSetImpl< Operation *> &opsToHoist)
static bool isOpLoopInvariant (Operation &op, Value indVar, ValueRange iterArgs, SmallPtrSetImpl< Operation *> &opsWithUsers, SmallPtrSetImpl< Operation *> &opsToHoist)
static bool areAllOpsInTheBlockListInvariant (Region &blockList, Value indVar, ValueRange iterArgs, SmallPtrSetImpl< Operation *> &opsWithUsers, SmallPtrSetImpl< Operation *> &opsToHoist)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "licm"
Definition at line 41 of file AffineLoopInvariantCodeMotion.cpp.
GEN_PASS_DEF_AFFINELOOPINVARIANTCODEMOTION
#define GEN_PASS_DEF_AFFINELOOPINVARIANTCODEMOTION
Definition at line 37 of file AffineLoopInvariantCodeMotion.cpp.
Function Documentation
areAllOpsInTheBlockListInvariant()
bool areAllOpsInTheBlockListInvariant (Region & blockList, Value indVar, ValueRange iterArgs, SmallPtrSetImpl< Operation *> & opsWithUsers, SmallPtrSetImpl< Operation *> & opsToHoist) static
Definition at line 166 of file AffineLoopInvariantCodeMotion.cpp.
References isOpLoopInvariant().
Referenced by checkInvarianceOfNestedIfOps(), and isOpLoopInvariant().
checkInvarianceOfNestedIfOps()
bool checkInvarianceOfNestedIfOps (Operation * op, Value indVar, ValueRange iterArgs, SmallPtrSetImpl< Operation *> & opsWithUsers, SmallPtrSetImpl< Operation *> & opsToHoist) static
Definition at line 183 of file AffineLoopInvariantCodeMotion.cpp.
References areAllOpsInTheBlockListInvariant(), isOpLoopInvariant(), mlir::Operation::moveBefore(), and mlir::Operation::use_empty().
Referenced by isOpLoopInvariant().
isOpLoopInvariant()
bool isOpLoopInvariant (Operation & op, Value indVar, ValueRange iterArgs, SmallPtrSetImpl< Operation *> & opsWithUsers, SmallPtrSetImpl< Operation *> & opsToHoist) static
Definition at line 74 of file AffineLoopInvariantCodeMotion.cpp.
References areAllOpsInTheBlockListInvariant(), checkInvarianceOfNestedIfOps(), mlir::Value::getDefiningOp(), mlir::getForInductionVarOwner(), mlir::getLoopIVs(), mlir::Operation::getNumOperands(), mlir::Operation::getOperand(), mlir::Value::getUsers(), mlir::m_Constant(), mlir::matchPattern(), and mlir::Value::print().
Referenced by areAllOpsInTheBlockListInvariant(), and checkInvarianceOfNestedIfOps().