MLIR: lib/Dialect/AMX/IR/AMXDialect.cpp File Reference
AMXDialect.cpp File Reference
#include "mlir/Dialect/AMX/AMXDialect.h"
#include "mlir/Dialect/LLVMIR/LLVMTypes.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/OpImplementation.h"
#include "mlir/IR/TypeUtilities.h"
#include "mlir/Dialect/AMX/AMXDialect.cpp.inc"
#include "mlir/Dialect/AMX/AMX.cpp.inc"
Macros
#define GET_OP_LIST
#define GET_OP_CLASSES
Functions
static LogicalResult verifyTileSize (Operation *op, VectorType tp)
Verify that AMX supports the implied tile shape.
static LogicalResult verifyMultShape (Operation *op, VectorType atp, VectorType btp, VectorType ctp, unsigned scale)
Verify that AMX supports the multiplication.
Macro Definition Documentation
GET_OP_CLASSES
#define GET_OP_CLASSES
Definition at line 107 of file AMXDialect.cpp.
GET_OP_LIST
#define GET_OP_LIST
Function Documentation
verifyMultShape()
static LogicalResult verifyMultShape (Operation * op, VectorType atp, VectorType btp, VectorType ctp, unsigned scale) static
Verify that AMX supports the multiplication.
Definition at line 43 of file AMXDialect.cpp.
References mlir::Operation::emitOpError(), mlir::failed(), mlir::failure(), getIndices(), mlir::bufferization::getMemRefType(), getVectorType(), mlir::Type::isBF16(), mlir::Type::isF32(), mlir::Type::isInteger(), mlir::success(), mlir::verify(), and verifyTileSize().
verifyTileSize()
static LogicalResult verifyTileSize (Operation * op, VectorType tp) static
Verify that AMX supports the implied tile shape.
Definition at line 31 of file AMXDialect.cpp.
References mlir::Operation::emitOpError(), and mlir::success().
Referenced by verifyMultShape().