MLIR: lib/Dialect/Arith/IR/InferIntRangeInterfaceImpls.cpp File Reference
InferIntRangeInterfaceImpls.cpp File Reference
#include "mlir/Dialect/Arith/IR/Arith.h"
#include "mlir/Interfaces/InferIntRangeInterface.h"
#include "llvm/Support/Debug.h"
Macros
#define DEBUG_TYPE "int-range-analysis"
Typedefs
using ConstArithFn = function_ref< Optional< APInt >(const APInt &, const APInt &)>
Function that evaluates the result of doing something on arithmetic constants and returns None on overflow.
using DivisionFixupFn = function_ref< Optional< APInt >(const APInt &lhs, const APInt &rhs, const APInt &result)>
Fix up division results (ex.
Functions
static ConstantIntRanges computeBoundsBy (ConstArithFn op, const APInt &minLeft, const APInt &minRight, const APInt &maxLeft, const APInt &maxRight, bool isSigned)
Return the maxmially wide signed or unsigned range for a given bitwidth.
static ConstantIntRanges minMaxBy (ConstArithFn op, ArrayRef< APInt > lhs, ArrayRef< APInt > rhs, bool isSigned)
Compute the minimum and maximum of (op(l, r) for l in lhs for r in rhs), ignoring unbounded values.
static ConstantIntRanges inferDivUIRange (const ConstantIntRanges &lhs, const ConstantIntRanges &rhs, DivisionFixupFn fixup)
static ConstantIntRanges inferDivSIRange (const ConstantIntRanges &lhs, const ConstantIntRanges &rhs, DivisionFixupFn fixup)
static std::tuple< APInt, APInt > widenBitwiseBounds (const ConstantIntRanges &bound)
"Widen" bounds - if 0bvvvvv??? <= a <= 0bvvvvv???, relax the bounds to 0bvvvvv000 <= a <= 0bvvvvv111, where vvvvv are the bits that both bonuds have in common.
static ConstantIntRanges extUIRange (const ConstantIntRanges &range, Type destType)
static ConstantIntRanges extSIRange (const ConstantIntRanges &range, Type destType)
static ConstantIntRanges truncIRange (const ConstantIntRanges &range, Type destType)
bool isStaticallyTrue (arith::CmpIPredicate pred, const ConstantIntRanges &lhs, const ConstantIntRanges &rhs)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "int-range-analysis"
Definition at line 14 of file InferIntRangeInterfaceImpls.cpp.
Typedef Documentation
ConstArithFn
using ConstArithFn = function_ref<Optional<APInt>(const APInt &, const APInt &)>
Function that evaluates the result of doing something on arithmetic constants and returns None on overflow.
Definition at line 22 of file InferIntRangeInterfaceImpls.cpp.
DivisionFixupFn
using DivisionFixupFn = function_ref<Optional<APInt>(const APInt &lhs, const APInt &rhs, const APInt &result)>
Fix up division results (ex.
for ceiling and floor), returning an APInt if there has been no overflow
Definition at line 160 of file InferIntRangeInterfaceImpls.cpp.
Function Documentation
computeBoundsBy()
static ConstantIntRanges computeBoundsBy (ConstArithFn op, const APInt & minLeft, const APInt & minRight, const APInt & maxLeft, const APInt & maxRight, bool isSigned) static
Return the maxmially wide signed or unsigned range for a given bitwidth.
Compute op(minLeft, minRight) and op(maxLeft, maxRight) if possible, If either computation overflows, make the result unbounded.
Definition at line 28 of file InferIntRangeInterfaceImpls.cpp.
References mlir::ConstantIntRanges::maxRange(), and mlir::ConstantIntRanges::range().
extSIRange()
static ConstantIntRanges extSIRange (const ConstantIntRanges & range, Type destType) static
Definition at line 487 of file InferIntRangeInterfaceImpls.cpp.
References mlir::ConstantIntRanges::fromSigned(), mlir::ConstantIntRanges::getStorageBitwidth(), mlir::ConstantIntRanges::smax(), and mlir::ConstantIntRanges::smin().
Referenced by truncIRange().
extUIRange()
static ConstantIntRanges extUIRange (const ConstantIntRanges & range, Type destType) static
Definition at line 469 of file InferIntRangeInterfaceImpls.cpp.
References mlir::ConstantIntRanges::fromSigned(), mlir::ConstantIntRanges::getStorageBitwidth(), mlir::ConstantIntRanges::umax(), and mlir::ConstantIntRanges::umin().
Referenced by truncIRange().
inferDivSIRange()
static ConstantIntRanges inferDivSIRange (const ConstantIntRanges & lhs, const ConstantIntRanges & rhs, DivisionFixupFn fixup) static
Definition at line 191 of file InferIntRangeInterfaceImpls.cpp.
inferDivUIRange()
static ConstantIntRanges inferDivUIRange (const ConstantIntRanges & lhs, const ConstantIntRanges & rhs, DivisionFixupFn fixup) static
Definition at line 162 of file InferIntRangeInterfaceImpls.cpp.
isStaticallyTrue()
bool isStaticallyTrue (arith::CmpIPredicate pred, const ConstantIntRanges & lhs, const ConstantIntRanges & rhs)
Definition at line 590 of file InferIntRangeInterfaceImpls.cpp.
minMaxBy()
static ConstantIntRanges minMaxBy (ConstArithFn op, ArrayRef< APInt > lhs, ArrayRef< APInt > rhs, bool isSigned) static
Compute the minimum and maximum of (op(l, r) for l in lhs for r in rhs), ignoring unbounded values.
Returns the maximal range if op overflows.
Definition at line 41 of file InferIntRangeInterfaceImpls.cpp.
Referenced by widenBitwiseBounds().
truncIRange()
static ConstantIntRanges truncIRange (const ConstantIntRanges & range, Type destType) static
Definition at line 505 of file InferIntRangeInterfaceImpls.cpp.
References extSIRange(), extUIRange(), mlir::ConstantIntRanges::getStorageBitwidth(), getZero(), mlir::ConstantIntRanges::smax(), mlir::ConstantIntRanges::smin(), mlir::ConstantIntRanges::umax(), and mlir::ConstantIntRanges::umin().
widenBitwiseBounds()
static std::tuple<APInt, APInt> widenBitwiseBounds (const ConstantIntRanges & bound) static
"Widen" bounds - if 0bvvvvv??? <= a <= 0bvvvvv???, relax the bounds to 0bvvvvv000 <= a <= 0bvvvvv111, where vvvvv are the bits that both bonuds have in common.
This gives us a consertive approximation for what values can be passed to bitwise operations.
Definition at line 360 of file InferIntRangeInterfaceImpls.cpp.
References minMaxBy(), mlir::ConstantIntRanges::umax(), and mlir::ConstantIntRanges::umin().