MLIR: lib/Dialect/Arith/Transforms/EmulateWideInt.cpp File Reference
EmulateWideInt.cpp File Reference
#include "mlir/Dialect/Arith/Transforms/Passes.h"
#include "mlir/Dialect/Arith/IR/Arith.h"
#include "mlir/Dialect/Arith/Transforms/WideIntEmulationConverter.h"
#include "mlir/Dialect/Func/IR/FuncOps.h"
#include "mlir/Dialect/Func/Transforms/FuncConversions.h"
#include "mlir/Dialect/Vector/IR/VectorOps.h"
#include "mlir/Transforms/DialectConversion.h"
#include "llvm/Support/FormatVariadic.h"
#include "llvm/Support/MathExtras.h"
#include <cassert>
#include "mlir/Dialect/Arith/Transforms/Passes.h.inc"
Namespaces
mlir::arith
Macros
#define GEN_PASS_DEF_ARITHEMULATEWIDEINT
Functions
static std::pair< APInt, APInt > getHalves (const APInt &value, unsigned newBitWidth)
Returns N bottom and N top bits from value, where N = newBitWidth.
static Type reduceInnermostDim (VectorType type)
Returns the type with the last (innermost) dimention reduced to x1.
static Value createScalarOrSplatConstant (ConversionPatternRewriter &rewriter, Location loc, Type type, const APInt &value)
Returns a constant of integer of vector type filled with (repeated) value.
static Value createScalarOrSplatConstant (ConversionPatternRewriter &rewriter, Location loc, Type type, int64_t value)
Returns a constant of integer of vector type filled with (repeated) value.
static Value extractLastDimSlice (ConversionPatternRewriter &rewriter, Location loc, Value input, int64_t lastOffset)
Extracts the input vector slice with elements at the last dimension offset by lastOffset.
static std::pair< Value, Value > extractLastDimHalves (ConversionPatternRewriter &rewriter, Location loc, Value input)
Extracts two vector slices from the input whose type is vector<...x2T>, with the first element at offset 0 and the second element at offset 1.
static Value dropTrailingX1Dim (ConversionPatternRewriter &rewriter, Location loc, Value input)
static Value appendX1Dim (ConversionPatternRewriter &rewriter, Location loc, Value input)
Performs a vector shape cast to append an x1 dimension.
static Value insertLastDimSlice (ConversionPatternRewriter &rewriter, Location loc, Value source, Value dest, int64_t lastOffset)
Inserts the source vector slice into the dest vector at offset lastOffset in the last dimension.
static Value constructResultVector (ConversionPatternRewriter &rewriter, Location loc, VectorType resultType, ValueRange resultComponents)
Constructs a new vector of type resultType by creating a series of insertions of resultComponents, each at the next offset of the last vector dimension.
Macro Definition Documentation
GEN_PASS_DEF_ARITHEMULATEWIDEINT
#define GEN_PASS_DEF_ARITHEMULATEWIDEINT
Definition at line 22 of file EmulateWideInt.cpp.
Function Documentation
appendX1Dim()
static Value appendX1Dim (ConversionPatternRewriter & rewriter, Location loc, Value input) static
Performs a vector shape cast to append an x1 dimension.
If the input is a scalar, this is a noop.
Definition at line 139 of file EmulateWideInt.cpp.
References mlir::OpBuilder::create(), mlir::Type::dyn_cast(), and mlir::Value::getType().
Referenced by constructResultVector().
constructResultVector()
static Value constructResultVector (ConversionPatternRewriter & rewriter, Location loc, VectorType resultType, ValueRange resultComponents) static
Constructs a new vector of type resultType by creating a series of insertions of resultComponents, each at the next offset of the last vector dimension.
When all resultComponents are scalars, the result type is vector<NxT>; when resultComponents are vector<...x1xT>s, the result type is vector<...xNxT>, where N is the number of resultComponenets.
Definition at line 178 of file EmulateWideInt.cpp.
References mlir::ConversionTarget::addDynamicallyLegalDialect(), mlir::ConversionTarget::addDynamicallyLegalOp(), appendX1Dim(), mlir::applyPartialConversion(), mlir::Type::cast(), mlir::OpBuilder::create(), mlir::OpBuilder::createOrFold(), createScalarOrSplatConstant(), dropTrailingX1Dim(), mlir::Attribute::dyn_cast(), mlir::Type::dyn_cast_or_null(), mlir::detail::enumerate(), extractLastDimHalves(), extractLastDimSlice(), mlir::failed(), mlir::DenseElementsAttr::get(), mlir::Operation::getContext(), mlir::function_interface_impl::getFunctionType(), getHalves(), insertLastDimSlice(), mlir::TypeConverter::isLegal(), mlir::ConversionPatternRewriter::notifyMatchFailure(), mlir::OpConversionPattern< SourceOp >::OpConversionPattern(), mlir::arith::populateArithWideIntEmulationPatterns(), reduceInnermostDim(), mlir::ConversionPatternRewriter::replaceOp(), mlir::RewriterBase::replaceOpWithNewOp(), and mlir::success().
createScalarOrSplatConstant() [1/2]
static Value createScalarOrSplatConstant (ConversionPatternRewriter & rewriter, Location loc, Type type, const APInt & value) static
Returns a constant of integer of vector type filled with (repeated) value.
Definition at line 58 of file EmulateWideInt.cpp.
References mlir::Type::cast(), mlir::OpBuilder::create(), mlir::Type::dyn_cast(), mlir::DenseElementsAttr::get(), and mlir::Builder::getIntegerAttr().
Referenced by constructResultVector(), and createScalarOrSplatConstant().
createScalarOrSplatConstant() [2/2]
static Value createScalarOrSplatConstant (ConversionPatternRewriter & rewriter, Location loc, Type type, int64_t value) static
Returns a constant of integer of vector type filled with (repeated) value.
Definition at line 73 of file EmulateWideInt.cpp.
References mlir::Type::cast(), createScalarOrSplatConstant(), and mlir::Type::dyn_cast().
dropTrailingX1Dim()
static Value dropTrailingX1Dim (ConversionPatternRewriter & rewriter, Location loc, Value input) static
Definition at line 122 of file EmulateWideInt.cpp.
References mlir::OpBuilder::create(), mlir::Type::dyn_cast(), and mlir::Value::getType().
Referenced by constructResultVector().
extractLastDimHalves()
static std::pair<Value, Value> extractLastDimHalves (ConversionPatternRewriter & rewriter, Location loc, Value input) static
Extracts two vector slices from the input whose type is vector<...x2T>, with the first element at offset 0 and the second element at offset 1.
Definition at line 114 of file EmulateWideInt.cpp.
References extractLastDimSlice().
Referenced by constructResultVector().
extractLastDimSlice()
static Value extractLastDimSlice (ConversionPatternRewriter & rewriter, Location loc, Value input, int64_t lastOffset) static
Extracts the input vector slice with elements at the last dimension offset by lastOffset.
Returns a value of vector type with the last dimension reduced to x1 or fully scalarized, e.g.:
vector<3x2xi16> –> vector<3x1xi16>
vector<2xi16> –> i16
Definition at line 91 of file EmulateWideInt.cpp.
References mlir::Type::cast(), mlir::OpBuilder::create(), getShape(), and mlir::Value::getType().
Referenced by constructResultVector(), and extractLastDimHalves().
getHalves()
static std::pair<APInt, APInt> getHalves (const APInt & value, unsigned newBitWidth) static
Returns N bottom and N top bits from value, where N = newBitWidth.
Treats value as a 2*N bits-wide integer. The bottom bits are returned in the first pair element, while the top bits in the second one.
Definition at line 36 of file EmulateWideInt.cpp.
Referenced by constructResultVector().
insertLastDimSlice()
static Value insertLastDimSlice (ConversionPatternRewriter & rewriter, Location loc, Value source, Value dest, int64_t lastOffset) static
Inserts the source vector slice into the dest vector at offset lastOffset in the last dimension.
source can be a scalar when dest is a 1D vector.
Definition at line 155 of file EmulateWideInt.cpp.
References mlir::Type::cast(), mlir::OpBuilder::create(), getShape(), mlir::Value::getType(), and mlir::Type::isa().
Referenced by constructResultVector().
reduceInnermostDim()
static Type reduceInnermostDim (VectorType type) static
Returns the type with the last (innermost) dimention reduced to x1.
Scalarizes 1D vector inputs to match how we extract/insert vector values, e.g.:
vector<3x2xi16> –> vector<3x1xi16>
vector<2xi16> –> i16
Definition at line 48 of file EmulateWideInt.cpp.
Referenced by constructResultVector().