MLIR: lib/Conversion/ArithToLLVM/ArithToLLVM.cpp File Reference
ArithToLLVM.cpp File Reference
#include "mlir/Conversion/ArithToLLVM/ArithToLLVM.h"
#include "mlir/Conversion/LLVMCommon/ConversionTarget.h"
#include "mlir/Conversion/LLVMCommon/VectorPattern.h"
#include "mlir/Dialect/Arith/IR/Arith.h"
#include "mlir/Dialect/LLVMIR/LLVMDialect.h"
#include "mlir/IR/TypeUtilities.h"
#include "mlir/Pass/Pass.h"
#include "mlir/Conversion/Passes.h.inc"
Namespaces
mlir
Include the generated interface declarations.
Macros
#define GEN_PASS_DEF_ARITHTOLLVMCONVERSIONPASS
Functions
template<typename LLVMPredType , typename PredType >
static LLVMPredType convertCmpPredicate (PredType pred)
Macro Definition Documentation
GEN_PASS_DEF_ARITHTOLLVMCONVERSIONPASS
#define GEN_PASS_DEF_ARITHTOLLVMCONVERSIONPASS
Definition at line 19 of file ArithToLLVM.cpp.
Function Documentation
convertCmpPredicate()
template<typename LLVMPredType , typename PredType > static LLVMPredType convertCmpPredicate (PredType pred) static
Definition at line 340 of file ArithToLLVM.cpp.
References mlir::applyPartialConversion(), mlir::OpBuilder::create(), mlir::failed(), mlir::LLVM::detail::handleMultidimensionalVectors(), mlir::Type::isa(), mlir::kDeriveIndexBitwidthFromDataLayout, mlir::ConversionPatternRewriter::notifyMatchFailure(), options, mlir::LowerToLLVMOptions::overrideIndexBitwidth(), mlir::arith::populateArithToLLVMConversionPatterns(), mlir::RewriterBase::replaceOpWithNewOp(), and mlir::success().