MLIR: lib/Dialect/GPU/Transforms/AsyncRegionRewriter.cpp File Reference
AsyncRegionRewriter.cpp File Reference
#include "mlir/Dialect/GPU/Transforms/Passes.h"
#include "mlir/Dialect/Async/IR/Async.h"
#include "mlir/Dialect/Func/IR/FuncOps.h"
#include "mlir/Dialect/GPU/IR/GPUDialect.h"
#include "mlir/Dialect/GPU/Transforms/Utils.h"
#include "mlir/IR/BlockAndValueMapping.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/IR/SymbolTable.h"
#include "mlir/Support/LLVM.h"
#include "mlir/Transforms/RegionUtils.h"
#include "llvm/ADT/TypeSwitch.h"
#include "mlir/Dialect/GPU/Transforms/Passes.h.inc"
Classes
struct GpuAsyncRegionPass::ThreadTokenCallback
struct GpuAsyncRegionPass::DeferWaitCallback
struct GpuAsyncRegionPass::SingleTokenUseCallback
Namespaces
mlir
Include the generated interface declarations.
Macros
#define GEN_PASS_DEF_GPUASYNCREGIONPASS
Functions
static bool isTerminator (Operation *op)
static bool hasSideEffects (Operation *op)
async::ExecuteOp addExecuteResults (async::ExecuteOp executeOp, ValueRange results)
Erases executeOp and returns a clone with additional results.
Macro Definition Documentation
GEN_PASS_DEF_GPUASYNCREGIONPASS
#define GEN_PASS_DEF_GPUASYNCREGIONPASS
Definition at line 29 of file AsyncRegionRewriter.cpp.
Function Documentation
addExecuteResults()
async::ExecuteOp addExecuteResults (async::ExecuteOp executeOp, ValueRange results)
Erases executeOp and returns a clone with additional results.
Definition at line 149 of file AsyncRegionRewriter.cpp.
References mlir::BlockAndValueMapping::clear(), mlir::Operation::getNumOperands(), mlir::Value::getType(), mlir::Operation::insertOperands(), and value.
Referenced by GpuAsyncRegionPass::SingleTokenUseCallback::operator()(), and GpuAsyncRegionPass::DeferWaitCallback::~DeferWaitCallback().
hasSideEffects()
static bool hasSideEffects (Operation * op) static
Definition at line 48 of file AsyncRegionRewriter.cpp.
Referenced by GpuAsyncRegionPass::ThreadTokenCallback::operator()(), GpuAsyncRegionPass::DeferWaitCallback::operator()(), and GpuAsyncRegionPass::DeferWaitCallback::~DeferWaitCallback().
isTerminator()
static bool isTerminator (Operation * op) static
Definition at line 45 of file AsyncRegionRewriter.cpp.
References mlir::Operation::mightHaveTrait().
Referenced by GpuAsyncRegionPass::ThreadTokenCallback::operator()(), and GpuAsyncRegionPass::DeferWaitCallback::~DeferWaitCallback().