MLIR: lib/Dialect/Bufferization/Transforms/BufferResultsToOutParams.cpp File Reference
BufferResultsToOutParams.cpp File Reference
#include "mlir/Dialect/Bufferization/Transforms/Passes.h"
#include "mlir/Dialect/Func/IR/FuncOps.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/IR/Operation.h"
#include "mlir/Pass/Pass.h"
#include "mlir/Dialect/Bufferization/Transforms/Passes.h.inc"
Namespaces
mlir
Include the generated interface declarations.
mlir::bufferization
Macros
#define GEN_PASS_DEF_BUFFERRESULTSTOOUTPARAMS
Functions
static bool hasFullyDynamicLayoutMap (MemRefType type)
Return true if the given MemRef type has a fully dynamic layout.
static bool hasStaticIdentityLayout (MemRefType type)
Return true if the given MemRef type has a static identity layout (i.e., no layout).
static LogicalResult updateFuncOp (func::FuncOp func, SmallVectorImpl< BlockArgument > &appendedEntryArgs)
static void updateReturnOps (func::FuncOp func, ArrayRef< BlockArgument > appendedEntryArgs)
static LogicalResult updateCalls (ModuleOp module, const bufferization::BufferResultsToOutParamsOptions &options)
Macro Definition Documentation
GEN_PASS_DEF_BUFFERRESULTSTOOUTPARAMS
#define GEN_PASS_DEF_BUFFERRESULTSTOOUTPARAMS
Definition at line 18 of file BufferResultsToOutParams.cpp.
Function Documentation
hasFullyDynamicLayoutMap()
static bool hasFullyDynamicLayoutMap (MemRefType type) static
Return true if the given MemRef type has a fully dynamic layout.
Definition at line 26 of file BufferResultsToOutParams.cpp.
References mlir::failed(), and mlir::getStridesAndOffset().
Referenced by updateCalls(), and updateFuncOp().
hasStaticIdentityLayout()
static bool hasStaticIdentityLayout (MemRefType type) static
Return true if the given MemRef type has a static identity layout (i.e., no layout).
Definition at line 40 of file BufferResultsToOutParams.cpp.
Referenced by updateCalls(), and updateFuncOp().
updateCalls()
static LogicalResult updateCalls (ModuleOp module, const bufferization::BufferResultsToOutParamsOptions & options) static
Definition at line 123 of file BufferResultsToOutParams.cpp.
References mlir::OpBuilder::create(), mlir::Operation::emitError(), mlir::Operation::erase(), mlir::failure(), mlir::bufferization::BufferResultsToOutParamsOptions::filterFn, mlir::Value::getType(), hasFullyDynamicLayoutMap(), hasStaticIdentityLayout(), mlir::SymbolTable::lookup(), and mlir::Operation::replaceAllUsesWith().
Referenced by mlir::bufferization::promoteBufferResultsToOutParams().
updateFuncOp()
static LogicalResult updateFuncOp (func::FuncOp func, SmallVectorImpl< BlockArgument > & appendedEntryArgs) static
Definition at line 48 of file BufferResultsToOutParams.cpp.
References mlir::detail::enumerate(), hasFullyDynamicLayoutMap(), hasStaticIdentityLayout(), and mlir::success().
Referenced by mlir::bufferization::promoteBufferResultsToOutParams().
updateReturnOps()
static void updateReturnOps (func::FuncOp func, ArrayRef< BlockArgument > appendedEntryArgs) static
Definition at line 100 of file BufferResultsToOutParams.cpp.
References mlir::OpBuilder::create(), and mlir::Operation::erase().
Referenced by mlir::bufferization::promoteBufferResultsToOutParams().