MLIR: lib/Bytecode/Reader/BytecodeReader.cpp File Reference
BytecodeReader.cpp File Reference
#include "mlir/Bytecode/BytecodeReader.h"
#include "../Encoding.h"
#include "mlir/AsmParser/AsmParser.h"
#include "mlir/Bytecode/BytecodeImplementation.h"
#include "mlir/IR/BuiltinDialect.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/OpImplementation.h"
#include "mlir/IR/Verifier.h"
#include "llvm/ADT/MapVector.h"
#include "llvm/ADT/ScopeExit.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/Support/MemoryBufferRef.h"
#include "llvm/Support/SaveAndRestore.h"
Macros
#define DEBUG_TYPE "mlir-bytecode-reader"
Functions
static std::string toString (bytecode::Section::ID sectionID)
Stringify the given section ID.
static bool isSectionOptional (bytecode::Section::ID sectionID)
Returns true if the given top-level section ID is optional.
template<typename RangeT , typename T >
static LogicalResult resolveEntry (EncodingReader &reader, RangeT &entries, uint64_t index, T &entry, StringRef entryStr)
Resolve an index into the given entry list.
template<typename RangeT , typename T >
static LogicalResult parseEntry (EncodingReader &reader, RangeT &entries, T &entry, StringRef entryStr)
Parse and resolve an index into the given entry list.
static LogicalResult parseDialectGrouping (EncodingReader &reader, MutableArrayRef< BytecodeDialect > dialects, function_ref< LogicalResult(BytecodeDialect *)> entryCallback)
Parse a single dialect group encoded in the byte stream.
template<typename T >
static LogicalResult parseResourceGroup (Location fileLoc, bool allowEmpty, EncodingReader &offsetReader, EncodingReader &resourceReader, StringSectionReader &stringReader, T *handler, function_ref< LogicalResult(StringRef)> processKeyFn={})
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "mlir-bytecode-reader"
Definition at line 27 of file BytecodeReader.cpp.
Function Documentation
isSectionOptional()
static bool isSectionOptional (bytecode::Section::ID sectionID) static
Returns true if the given top-level section ID is optional.
Definition at line 54 of file BytecodeReader.cpp.
References mlir::InFlightDiagnostic::append(), mlir::emitError(), mlir::failed(), mlir::failure(), mlir::bytecode::kAlignmentByte, mlir::bytecode::Section::kAttrType, mlir::bytecode::Section::kAttrTypeOffset, mlir::bytecode::Section::kDialect, mlir::bytecode::Section::kIR, mlir::bytecode::Section::kNumSections, mlir::bytecode::Section::kResource, mlir::bytecode::Section::kResourceOffset, mlir::bytecode::Section::kString, mlir::success(), and value.
parseDialectGrouping()
static LogicalResult parseDialectGrouping (EncodingReader & reader, MutableArrayRef< BytecodeDialect > dialects, function_ref< LogicalResult(BytecodeDialect *)> entryCallback) static
Parse a single dialect group encoded in the byte stream.
Definition at line 461 of file BytecodeReader.cpp.
References mlir::failed(), mlir::failure(), parseEntry(), and mlir::success().
parseEntry()
template<typename RangeT , typename T > static LogicalResult parseEntry (EncodingReader & reader, RangeT & entries, T & entry, StringRef entryStr) static
Parse and resolve an index into the given entry list.
Definition at line 321 of file BytecodeReader.cpp.
References mlir::MLIRContext::allowsUnregisteredDialects(), mlir::failed(), mlir::failure(), mlir::MLIRContext::getOrLoadDialect(), resolveEntry(), and mlir::success().
Referenced by parseDialectGrouping().
parseResourceGroup()
template<typename T > static LogicalResult parseResourceGroup (Location fileLoc, bool allowEmpty, EncodingReader & offsetReader, EncodingReader & resourceReader, StringSectionReader & stringReader, T * handler, function_ref< LogicalResult(StringRef)> processKeyFn = {}) static
Definition at line 572 of file BytecodeReader.cpp.
References mlir::failed(), and mlir::failure().
resolveEntry()
template<typename RangeT , typename T > static LogicalResult resolveEntry (EncodingReader & reader, RangeT & entries, uint64_t index, T & entry, StringRef entryStr) static
Resolve an index into the given entry list.
entry may either be a reference, in which case it is assigned to the corresponding value in entries, or a pointer, in which case it is assigned to the address of the element in entries.
Definition at line 305 of file BytecodeReader.cpp.
References mlir::success().
Referenced by parseEntry().
toString()
static std::string toString (bytecode::Section::ID sectionID) static
Stringify the given section ID.
Definition at line 32 of file BytecodeReader.cpp.
References mlir::bytecode::Section::kAttrType, mlir::bytecode::Section::kAttrTypeOffset, mlir::bytecode::Section::kDialect, mlir::bytecode::Section::kIR, mlir::bytecode::Section::kResource, mlir::bytecode::Section::kResourceOffset, and mlir::bytecode::Section::kString.
Referenced by encodeError(), getLocationFromLoc(), getURIFromLoc(), mlir::lsp::JSONTransport::run(), and verifyStructIndices().