MLIR: lib/Bytecode/Writer/BytecodeWriter.cpp File Reference
BytecodeWriter.cpp File Reference
#include "mlir/Bytecode/BytecodeWriter.h"
#include "../Encoding.h"
#include "IRNumbering.h"
#include "mlir/Bytecode/BytecodeImplementation.h"
#include "mlir/IR/BuiltinDialect.h"
#include "mlir/IR/OpImplementation.h"
#include "llvm/ADT/CachedHashString.h"
#include "llvm/ADT/MapVector.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/Support/Debug.h"
#include <random>
Classes
struct mlir::BytecodeWriterConfig::Impl
Macros
#define DEBUG_TYPE "mlir-bytecode-writer"
Functions
template<typename EntriesT , typename EntryCallbackT >
static void writeDialectGrouping (EncodingEmitter &emitter, EntriesT &&entries, EntryCallbackT &&callback)
Write the given entries in contiguous groups with the same parent dialect.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "mlir-bytecode-writer"
Definition at line 21 of file BytecodeWriter.cpp.
Function Documentation
writeDialectGrouping()
template<typename EntriesT , typename EntryCallbackT > static void writeDialectGrouping (EncodingEmitter & emitter, EntriesT && entries, EntryCallbackT && callback) static
Write the given entries in contiguous groups with the same parent dialect.
Each dialect sub-group is encoded with the parent dialect and number of elements, followed by the encoding for the entries. The given callback is invoked to encode each individual entry.
Definition at line 440 of file BytecodeWriter.cpp.
References mlir::Blob, mlir::Bool, mlir::Region::empty(), mlir::Block::getArguments(), mlir::Operation::getAttrDictionary(), mlir::Operation::getLoc(), mlir::Operation::getName(), mlir::bytecode::detail::IRNumberingState::getNumber(), mlir::Operation::getNumOperands(), mlir::Operation::getNumRegions(), mlir::Operation::getNumResults(), mlir::Operation::getNumSuccessors(), mlir::Operation::getOperands(), mlir::Operation::getRegions(), mlir::Operation::getResultTypes(), mlir::Operation::getSuccessors(), mlir::Operation::hasTrait(), mlir::bytecode::Section::kAttrType, mlir::bytecode::Section::kAttrTypeOffset, mlir::bytecode::Section::kDialect, mlir::bytecode::OpEncodingMask::kHasAttrs, mlir::bytecode::OpEncodingMask::kHasInlineRegions, mlir::bytecode::OpEncodingMask::kHasOperands, mlir::bytecode::OpEncodingMask::kHasResults, mlir::bytecode::OpEncodingMask::kHasSuccessors, mlir::bytecode::Section::kIR, mlir::bytecode::detail::DialectNumbering::number, mlir::String, mlir::succeeded(), and value.