MLIR: mlir::python::PySymbolTable Class Reference
mlir::python::PySymbolTable Class Reference
Bindings for MLIR symbol tables.
#include "Bindings/Python/IRModule.h"
Public Member Functions
PySymbolTable (PyOperationBase &operation)
Constructs a symbol table for the given operation.
~PySymbolTable ()
Destroys the symbol table.
pybind11::object dunderGetItem (const std::string &name)
Returns the symbol (opview) with the given name, throws if there is no such symbol in the table.
void erase (PyOperationBase &symbol)
Removes the given operation from the symbol table and erases it.
void dunderDel (const std::string &name)
Removes the operation with the given name from the symbol table and erases it, throws if there is no such symbol in the table.
PyAttribute insert (PyOperationBase &symbol)
Inserts the given operation into the symbol table.
operator MlirSymbolTable ()
Casts the bindings class into the C API structure.
Static Public Member Functions
static PyAttribute getSymbolName (PyOperationBase &symbol)
Gets and sets the name of a symbol op.
static void setSymbolName (PyOperationBase &symbol, const std::string &name)
static PyAttribute getVisibility (PyOperationBase &symbol)
Gets and sets the visibility of a symbol op.
static void setVisibility (PyOperationBase &symbol, const std::string &visibility)
static void replaceAllSymbolUses (const std::string &oldSymbol, const std::string &newSymbol, PyOperationBase &from)
Replaces all symbol uses within an operation.
static void walkSymbolTables (PyOperationBase &from, bool allSymUsesVisible, pybind11::object callback)
Walks all symbol tables under and including 'from'.
Detailed Description
Bindings for MLIR symbol tables.
Definition at line 1012 of file IRModule.h.
Constructor & Destructor Documentation
PySymbolTable()
PySymbolTable::PySymbolTable (PyOperationBase & operation) explicit
Constructs a symbol table for the given operation.
Definition at line 1731 of file IRCore.cpp.
References mlir::python::PyOperation::get(), mlir::python::PyOperationBase::getOperation(), mlirSymbolTableCreate(), and mlirSymbolTableIsNull().
~PySymbolTable()
mlir::python::PySymbolTable::~PySymbolTable () inline
Destroys the symbol table.
Definition at line 1018 of file IRModule.h.
References mlirSymbolTableDestroy().
Member Function Documentation
dunderDel()
void PySymbolTable::dunderDel (const std::string & name)
Removes the operation with the given name from the symbol table and erases it, throws if there is no such symbol in the table.
Definition at line 1761 of file IRCore.cpp.
References dunderGetItem(), and erase().
Referenced by walkSymbolTables().
dunderGetItem()
py::object PySymbolTable::dunderGetItem (const std::string & name)
Returns the symbol (opview) with the given name, throws if there is no such symbol in the table.
Definition at line 1739 of file IRCore.cpp.
References mlir::python::PyOperation::checkValid(), mlir::python::PyOperation::forOperation(), mlir::python::BaseContextObject::getContext(), mlir::python::PyObjectRef< T >::getObject(), mlirOperationIsNull(), mlirStringRefCreate(), and mlirSymbolTableLookup().
Referenced by dunderDel(), and walkSymbolTables().
erase()
void PySymbolTable::erase (PyOperationBase & symbol)
Removes the given operation from the symbol table and erases it.
Definition at line 1751 of file IRCore.cpp.
References mlir::python::PyOperation::checkValid(), mlir::python::PyOperation::get(), mlir::python::PyOperationBase::getOperation(), and mlirSymbolTableErase().
Referenced by dunderDel(), and walkSymbolTables().
getSymbolName()
PyAttribute PySymbolTable::getSymbolName (PyOperationBase & symbol) static
Gets and sets the name of a symbol op.
Definition at line 1778 of file IRCore.cpp.
References mlir::python::PyOperation::checkValid(), mlir::python::PyOperation::get(), mlir::python::BaseContextObject::getContext(), mlir::python::PyOperationBase::getOperation(), mlirAttributeIsNull(), mlirOperationGetAttributeByName(), and mlirSymbolTableGetSymbolAttributeName().
Referenced by walkSymbolTables().
getVisibility()
PyAttribute PySymbolTable::getVisibility (PyOperationBase & symbol) static
Gets and sets the visibility of a symbol op.
Definition at line 1805 of file IRCore.cpp.
References mlir::python::PyOperation::checkValid(), mlir::python::PyOperation::get(), mlir::python::BaseContextObject::getContext(), mlir::python::PyOperationBase::getOperation(), mlirAttributeIsNull(), mlirOperationGetAttributeByName(), and mlirSymbolTableGetVisibilityAttributeName().
Referenced by walkSymbolTables().
insert()
PyAttribute PySymbolTable::insert (PyOperationBase & symbol)
Inserts the given operation into the symbol table.
The operation must have the symbol trait.
Definition at line 1766 of file IRCore.cpp.
References mlir::python::PyOperation::checkValid(), mlir::python::PyOperation::get(), mlir::python::BaseContextObject::getContext(), mlir::python::PyOperationBase::getOperation(), mlirAttributeIsNull(), mlirOperationGetAttributeByName(), mlirSymbolTableGetSymbolAttributeName(), and mlirSymbolTableInsert().
Referenced by walkSymbolTables().
operator MlirSymbolTable()
mlir::python::PySymbolTable::operator MlirSymbolTable () inline
Casts the bindings class into the C API structure.
Definition at line 1055 of file IRModule.h.
References mlir::python::populateIRAffine(), mlir::python::populateIRAttributes(), mlir::python::populateIRCore(), mlir::python::populateIRInterfaces(), and mlir::python::populateIRTypes().
replaceAllSymbolUses()
void PySymbolTable::replaceAllSymbolUses (const std::string & oldSymbol, const std::string & newSymbol, PyOperationBase & from) static
Replaces all symbol uses within an operation.
See the API mlirSymbolTableReplaceAllSymbolUses for all caveats.
Definition at line 1834 of file IRCore.cpp.
References mlir::python::PyOperation::checkValid(), mlir::python::PyOperationBase::getOperation(), mlirLogicalResultIsFailure(), mlirSymbolTableReplaceAllSymbolUses(), and toMlirStringRef().
Referenced by walkSymbolTables().
setSymbolName()
void PySymbolTable::setSymbolName (PyOperationBase & symbol, const std::string & name) static
Definition at line 1790 of file IRCore.cpp.
References mlir::python::PyOperation::checkValid(), mlir::python::PyMlirContext::get(), mlir::python::PyOperation::get(), mlir::python::BaseContextObject::getContext(), mlir::python::PyOperationBase::getOperation(), mlirAttributeIsNull(), mlirOperationGetAttributeByName(), mlirOperationSetAttributeByName(), mlirStringAttrGet(), mlirSymbolTableGetSymbolAttributeName(), and toMlirStringRef().
Referenced by walkSymbolTables().
setVisibility()
void PySymbolTable::setVisibility (PyOperationBase & symbol, const std::string & visibility) static
Definition at line 1816 of file IRCore.cpp.
References mlir::python::PyOperation::checkValid(), mlir::python::PyMlirContext::get(), mlir::python::PyOperation::get(), mlir::python::BaseContextObject::getContext(), mlir::python::PyOperationBase::getOperation(), mlirAttributeIsNull(), mlirOperationGetAttributeByName(), mlirOperationSetAttributeByName(), mlirStringAttrGet(), mlirSymbolTableGetVisibilityAttributeName(), and toMlirStringRef().
Referenced by walkSymbolTables().
walkSymbolTables()
void PySymbolTable::walkSymbolTables (PyOperationBase & from, bool allSymUsesVisible, pybind11::object callback) static
Walks all symbol tables under and including 'from'.
Definition at line 1846 of file IRCore.cpp.
References mlir::python::PyInsertionPoint::atBlockBegin(), mlir::python::PyInsertionPoint::atBlockTerminator(), mlir::python::PyMlirContext::attachDiagnosticHandler(), MlirNamedAttribute::attribute, PyGlobalDebugFlag::bind(), mlir::python::PyOpView::buildGeneric(), mlir::python::PyOperation::checkValid(), mlir::python::PyRegion::checkValid(), classmethod(), mlir::python::PyMlirContext::clearLiveOperations(), mlir::python::PyOperation::clone(), mlir::python::PyMlirContext::contextEnter(), mlir::python::PyDiagnosticHandler::contextEnter(), mlir::python::PyLocation::contextEnter(), mlir::python::PyInsertionPoint::contextEnter(), mlir::python::PyMlirContext::contextExit(), mlir::python::PyDiagnosticHandler::contextExit(), mlir::python::PyLocation::contextExit(), mlir::python::PyInsertionPoint::contextExit(), mlir::python::PyOperation::create(), createCustomDialectWrapper(), mlir::python::PyMlirContext::createFromCapsule(), mlir::python::PyDialectRegistry::createFromCapsule(), mlir::python::PyLocation::createFromCapsule(), mlir::python::PyModule::createFromCapsule(), mlir::python::PyOperation::createFromCapsule(), mlir::python::PyType::createFromCapsule(), mlir::python::PyAttribute::createFromCapsule(), mlir::python::PyValue::createFromCapsule(), mlir::python::PyMlirContext::createNewContextForInit(), mlir::python::PyOperation::createOpView(), MlirStringRef::data, mlir::python::PyDiagnosticHandler::detach(), mlir::python::PyOperation::detachFromParent(), dunderDel(), dunderGetItem(), mlir::python::PyOperation::erase(), erase(), mlir::python::PyMlirContext::forContext(), mlir::python::PyModule::forModule(), mlir::python::PyOperation::forOperation(), mlir::python::Defaulting< DerivedTy, T >::get(), mlir::python::PyLocation::get(), mlir::python::PyOperation::get(), mlir::python::PyRegion::get(), mlir::python::PyBlock::get(), mlir::python::PyValue::get(), mlir::python::PyOperationBase::getAsm(), mlir::PyPrintAccumulator::getCallback(), mlir::python::PyMlirContext::getCapsule(), mlir::python::PyDialectRegistry::getCapsule(), mlir::python::PyLocation::getCapsule(), mlir::python::PyModule::getCapsule(), mlir::python::PyOperation::getCapsule(), mlir::python::PyType::getCapsule(), mlir::python::PyAttribute::getCapsule(), mlir::python::PyValue::getCapsule(), mlir::python::BaseContextObject::getContext(), mlir::python::PyThreadContextEntry::getDefaultContext(), mlir::python::PyThreadContextEntry::getDefaultInsertionPoint(), mlir::python::PyThreadContextEntry::getDefaultLocation(), mlir::python::PyDiagnosticHandler::getHadError(), mlir::python::PyMlirContext::getLiveCount(), mlir::python::PyMlirContext::getLiveModuleCount(), mlir::python::PyMlirContext::getLiveOperationCount(), mlir::python::PyDiagnostic::getLocation(), mlir::python::PyDiagnostic::getMessage(), mlir::python::PyDiagnostic::getNotes(), mlir::python::PyOperationBase::getOperation(), mlir::python::PyOperation::getOperation(), mlir::python::PyOpView::getOperationObject(), mlir::python::PyRegion::getParentOperation(), mlir::python::PyValue::getParentOperation(), mlir::python::PyDiagnostic::getSeverity(), getSymbolName(), mlir::PyPrintAccumulator::getUserData(), getVisibility(), mlir::presburger::hash_value(), mlir::python::PyInsertionPoint::insert(), insert(), mlir::python::PyDiagnosticHandler::isAttached(), mlir::python::PyOperation::isAttached(), mlir::PyPrintAccumulator::join(), kContextGetCallSiteLocationDocstring, kContextGetFileLocationDocstring, kContextGetFusedLocationDocstring, kContextGetNameLocationDocString, kContextParseTypeDocstring, kDumpDocstring, kModuleParseDocstring, kOperationCreateDocstring, kOperationGetAsmDocstring, kOperationPrintBytecodeDocstring, kOperationPrintDocstring, kOperationStrDunderDocstring, kValueDunderStrDocstring, MlirStringRef::length, MLIR_PYTHON_CAPI_FACTORY_ATTR, MLIR_PYTHON_CAPI_PTR_ATTR, mlirAttributeDump(), mlirAttributeGetContext(), mlirAttributeGetType(), mlirAttributeIsNull(), mlirAttributeParseGet(), mlirAttributePrint(), mlirBlockAppendOwnedOperation(), mlirBlockArgumentGetArgNumber(), mlirBlockArgumentGetOwner(), mlirBlockArgumentSetType(), mlirBlockCreate(), mlirBlockDetach(), mlirBlockGetArgument(), mlirBlockGetFirstOperation(), mlirBlockGetNumArguments(), mlirBlockGetParentOperation(), mlirBlockGetParentRegion(), mlirBlockPrint(), mlirContextAppendDialectRegistry(), mlirContextEnableMultithreading(), mlirContextGetAllowUnregisteredDialects(), mlirContextGetOrLoadDialect(), mlirContextIsRegisteredOperation(), mlirContextLoadAllAvailableDialects(), mlirContextSetAllowUnregisteredDialects(), MlirDiagnosticError, MlirDiagnosticNote, MlirDiagnosticRemark, MlirDiagnosticWarning, mlirDialectGetNamespace(), mlirDialectIsNull(), mlirEmitError(), mlirIdentifierStr(), mlirLocationCallSiteGet(), mlirLocationEqual(), mlirLocationFileLineColGet(), mlirLocationFusedGet(), mlirLocationNameGet(), mlirLocationPrint(), mlirLocationUnknownGet(), mlirModuleCreateEmpty(), mlirModuleCreateParse(), mlirModuleGetBody(), mlirModuleGetOperation(), mlirModuleIsNull(), mlirOperationDump(), mlirOperationEqual(), mlirOperationGetAttribute(), mlirOperationGetAttributeByName(), mlirOperationGetLocation(), mlirOperationGetName(), mlirOperationGetNumAttributes(), mlirOperationGetNumOperands(), mlirOperationGetNumResults(), mlirOperationGetOperand(), mlirOperationGetResult(), mlirOperationIsNull(), mlirOperationRemoveAttributeByName(), mlirOperationSetAttributeByName(), mlirOperationSetOperand(), mlirOperationVerify(), mlirOpResultGetOwner(), mlirOpResultGetResultNumber(), mlirRegionAppendOwnedBlock(), mlirRegionGetFirstBlock(), mlirRegionInsertOwnedBlock(), mlirRegionInsertOwnedBlockAfter(), mlirRegionInsertOwnedBlockBefore(), mlirRegionIsNull(), mlirStringRefCreate(), mlirSymbolTableLookup(), mlirSymbolTableWalkSymbolTables(), mlirTypeDump(), mlirTypeGetContext(), mlirTypeIsNull(), mlirTypeParseGet(), mlirTypePrint(), mlirValueDump(), mlirValueGetType(), mlirValueIsABlockArgument(), mlirValueIsAOpResult(), mlirValuePrint(), mlir::python::PyOperationBase::moveAfter(), mlir::python::PyOperationBase::moveBefore(), MlirNamedAttribute::name, mlir::PyPrintAccumulator::parts, mlir::python::populateIRCore(), mlir::python::PyOperationBase::print(), mlir::python::PyObjectRef< T >::releaseObject(), replaceAllSymbolUses(), mlir::python::PyOperation::setAttached(), mlir::python::SetPyError(), setSymbolName(), setVisibility(), toMlirStringRef(), value, and mlir::python::PyOperationBase::writeBytecode().
The documentation for this class was generated from the following files:
lib/Bindings/Python/IRModule.h
lib/Bindings/Python/IRCore.cpp