MLIR: mlir::sparse_tensor::SparseTensorEnumeratorBase< V > Class Template Reference
mlir::sparse_tensor::SparseTensorEnumeratorBase< V > Class Template Reference abstract
A (higher-order) function object for enumerating the elements of some SparseTensorStorage under a permutation.
#include "mlir/ExecutionEngine/SparseTensor/Storage.h"
Public Member Functions
SparseTensorEnumeratorBase (const SparseTensorStorageBase &tensor, uint64_t rank, const uint64_t *perm)
Constructs an enumerator with the given permutation for mapping the semantic-ordering of dimensions to the desired target-ordering.
virtual ~SparseTensorEnumeratorBase ()=default
SparseTensorEnumeratorBase (const SparseTensorEnumeratorBase &)=delete
SparseTensorEnumeratorBase & operator= (const SparseTensorEnumeratorBase &)=delete
uint64_t getRank () const
Returns the source/target tensor's rank.
const std::vector< uint64_t > & permutedSizes () const
Returns the target tensor's dimension sizes.
virtual void forallElements (ElementConsumer< V > yield)=0
Enumerates all elements of the source tensor, permutes their indices, and passes the permuted element to the callback.
Protected Attributes
const SparseTensorStorageBase & src
std::vector< uint64_t > permsz
std::vector< uint64_t > reord
std::vector< uint64_t > cursor
Detailed Description
template<typename V>
class mlir::sparse_tensor::SparseTensorEnumeratorBase< V >
A (higher-order) function object for enumerating the elements of some SparseTensorStorage under a permutation.
That is, the forallElements method encapsulates the loop-nest for enumerating the elements of the source tensor (in whatever order is best for the source tensor), and applies a permutation to the coordinates/indices before handing each element to the callback. A single enumerator object can be freely reused for several calls to forallElements, just so long as each call is sequential with respect to one another.
N.B., this class stores a reference to the SparseTensorStorageBase passed to the constructor; thus, objects of this class must not outlive the sparse tensor they depend on.
Design Note: The reason we define this class instead of simply using SparseTensorEnumerator<P,I,V> is because we need to hide/generalize the <P,I> template parameters from MLIR client code (to simplify the type parameters used for direct sparse-to-sparse conversion). And the reason we define the SparseTensorEnumerator<P,I,V> subclasses rather than simply using this class, is to avoid the cost of virtual-method dispatch within the loop-nest.
Definition at line 49 of file Storage.h.
Constructor & Destructor Documentation
SparseTensorEnumeratorBase() [1/2]
template<typename V> mlir::sparse_tensor::SparseTensorEnumeratorBase< V >::SparseTensorEnumeratorBase (const SparseTensorStorageBase & tensor, uint64_t rank, const uint64_t * perm) inline
Constructs an enumerator with the given permutation for mapping the semantic-ordering of dimensions to the desired target-ordering.
Preconditions:
the tensor must have the same V value type.
perm must be valid for rank.
Definition at line 560 of file Storage.h.
References mlir::sparse_tensor::SparseTensorStorageBase::getRank(), and mlir::sparse_tensor::SparseTensorStorageBase::operator=().
~SparseTensorEnumeratorBase()
template<typename V> virtual mlir::sparse_tensor::SparseTensorEnumeratorBase< V >::~SparseTensorEnumeratorBase () virtual default
SparseTensorEnumeratorBase() [2/2]
template<typename V> mlir::sparse_tensor::SparseTensorEnumeratorBase< V >::SparseTensorEnumeratorBase (const SparseTensorEnumeratorBase< V > &) delete
Member Function Documentation
forallElements()
template<typename V> virtual void mlir::sparse_tensor::SparseTensorEnumeratorBase< V >::forallElements (ElementConsumer< V > yield) pure virtual
Enumerates all elements of the source tensor, permutes their indices, and passes the permuted element to the callback.
The callback must not store the cursor reference directly, since this function reuses the storage. Instead, the callback must copy it if they want to keep it.
Implemented in mlir::sparse_tensor::SparseTensorEnumerator< P, I, V >.
Referenced by mlir::sparse_tensor::SparseTensorNNZ::initialize(), mlir::sparse_tensor::SparseTensorStorage< P, I, V >::SparseTensorStorage(), and mlir::sparse_tensor::SparseTensorStorage< P, I, V >::toCOO().
getRank()
template<typename V> uint64_t mlir::sparse_tensor::SparseTensorEnumeratorBase< V >::getRank () const inline
Returns the source/target tensor's rank.
(The source-rank and target-rank are always equal since we only support permutations. Though once we add support for other dimension mappings, this method will have to be split in two.)
Definition at line 587 of file Storage.h.
Referenced by mlir::sparse_tensor::SparseTensorNNZ::initialize().
operator=()
template<typename V> SparseTensorEnumeratorBase& mlir::sparse_tensor::SparseTensorEnumeratorBase< V >::operator= (const SparseTensorEnumeratorBase< V > &) delete
permutedSizes()
template<typename V> const std::vector<uint64_t>& mlir::sparse_tensor::SparseTensorEnumeratorBase< V >::permutedSizes () const inline
Returns the target tensor's dimension sizes.
Definition at line 590 of file Storage.h.
Referenced by mlir::sparse_tensor::SparseTensorNNZ::initialize(), mlir::sparse_tensor::SparseTensorStorage< P, I, V >::newSparseTensor(), and mlir::sparse_tensor::SparseTensorStorage< P, I, V >::toCOO().
Member Data Documentation
cursor
template<typename V> std::vector<uint64_t> mlir::sparse_tensor::SparseTensorEnumeratorBase< V >::cursor protected
Definition at line 603 of file Storage.h.
permsz
template<typename V> std::vector<uint64_t> mlir::sparse_tensor::SparseTensorEnumeratorBase< V >::permsz protected
Definition at line 601 of file Storage.h.
reord
template<typename V> std::vector<uint64_t> mlir::sparse_tensor::SparseTensorEnumeratorBase< V >::reord protected
Definition at line 602 of file Storage.h.
src
template<typename V> const SparseTensorStorageBase& mlir::sparse_tensor::SparseTensorEnumeratorBase< V >::src protected
Definition at line 600 of file Storage.h.
The documentation for this class was generated from the following file:
include/mlir/ExecutionEngine/SparseTensor/Storage.h