MLIR: mlir::sparse_tensor::SparseTensorStorageBase Class Reference
mlir::sparse_tensor::SparseTensorStorageBase Class Reference abstract
Abstract base class for SparseTensorStorage<P,I,V>.
#include "mlir/ExecutionEngine/SparseTensor/Storage.h"
Public Member Functions
SparseTensorStorageBase (const std::vector< uint64_t > &dimSizes, const uint64_t *perm, const DimLevelType *sparsity)
Constructs a new storage object.
virtual ~SparseTensorStorageBase ()=default
uint64_t getRank () const
Gets the rank of the tensor.
const std::vector< uint64_t > & getDimSizes () const
Gets the dimension-sizes array, in storage-order.
uint64_t getDimSize (uint64_t d) const
Safely looks up the size of the given (storage-order) dimension.
const std::vector< uint64_t > & getRev () const
Gets the "reverse" permutation, which maps this object's storage-order to the tensor's semantic-order.
const std::vector< DimLevelType > & getDimTypes () const
Gets the dimension-types array, in storage-order.
DimLevelType getDimType (uint64_t d) const
Safely looks up the level-type of the given (storage-order) dimension.
bool isDenseDim (uint64_t d) const
Safely checks if the (storage-order) dimension uses dense storage.
bool isCompressedDim (uint64_t d) const
Safely checks if the (storage-order) dimension uses compressed storage.
bool isSingletonDim (uint64_t d) const
Safely checks if the (storage-order) dimension uses singleton storage.
bool isOrderedDim (uint64_t d) const
Safely checks if the (storage-order) dimension is ordered.
bool isUniqueDim (uint64_t d) const
Safely checks if the (storage-order) dimension is unique.
virtual uint64_t getIndex (uint64_t d, uint64_t pos) const =0
virtual void endInsert ()=0
Finishes insertion.
Protected Member Functions
SparseTensorStorageBase (const SparseTensorStorageBase &)=default
SparseTensorStorageBase & operator= (const SparseTensorStorageBase &)=delete
Detailed Description
Abstract base class for SparseTensorStorage<P,I,V>.
This class takes responsibility for all the <P,I,V>-independent aspects of the tensor (e.g., shape, sparsity, permutation). In addition, we use function overloading to implement "partial" method specialization, which the C-API relies on to catch type errors arising from our use of opaque pointers.
Definition at line 68 of file Storage.h.
Constructor & Destructor Documentation
SparseTensorStorageBase() [1/2]
mlir::sparse_tensor::SparseTensorStorageBase::SparseTensorStorageBase (const SparseTensorStorageBase &) protected default
SparseTensorStorageBase() [2/2]
SparseTensorStorageBase::SparseTensorStorageBase (const std::vector< uint64_t > & dimSizes, const uint64_t * perm, const DimLevelType * sparsity)
Constructs a new storage object.
The perm maps the tensor's semantic-ordering of dimensions to this object's storage-order. The dimSizes and sparsity arrays are already in storage-order.
Precondition: perm and sparsity must be valid for dimSizes.size().
Definition at line 30 of file Storage.cpp.
References getRank(), isCompressedDim(), isDenseDim(), and isSingletonDim().
~SparseTensorStorageBase()
virtual mlir::sparse_tensor::SparseTensorStorageBase::~SparseTensorStorageBase () virtual default
Member Function Documentation
endInsert()
virtual void mlir::sparse_tensor::SparseTensorStorageBase::endInsert () pure virtual
Finishes insertion.
Implemented in mlir::sparse_tensor::SparseTensorStorage< P, I, V >.
getDimSize()
uint64_t mlir::sparse_tensor::SparseTensorStorageBase::getDimSize (uint64_t d) const inline
Safely looks up the size of the given (storage-order) dimension.
Definition at line 97 of file Storage.h.
References ASSERT_VALID_DIM.
getDimSizes()
const std::vector<uint64_t>& mlir::sparse_tensor::SparseTensorStorageBase::getDimSizes () const inline
Gets the dimension-sizes array, in storage-order.
Definition at line 94 of file Storage.h.
Referenced by mlir::sparse_tensor::SparseTensorStorage< P, I, V >::SparseTensorStorage(), and mlir::sparse_tensor::SparseTensorStorage< P, I, V >::toCOO().
getDimType()
DimLevelType mlir::sparse_tensor::SparseTensorStorageBase::getDimType (uint64_t d) const inline
Safely looks up the level-type of the given (storage-order) dimension.
Definition at line 110 of file Storage.h.
References ASSERT_VALID_DIM.
Referenced by isCompressedDim(), isDenseDim(), isOrderedDim(), isSingletonDim(), and isUniqueDim().
getDimTypes()
const std::vector<DimLevelType>& mlir::sparse_tensor::SparseTensorStorageBase::getDimTypes () const inline
Gets the dimension-types array, in storage-order.
Definition at line 107 of file Storage.h.
Referenced by mlir::sparse_tensor::SparseTensorStorage< P, I, V >::SparseTensorStorage().
getIndex()
virtual uint64_t mlir::sparse_tensor::SparseTensorStorageBase::getIndex (uint64_t d, uint64_t pos) const pure virtual
Implemented in mlir::sparse_tensor::SparseTensorStorage< P, I, V >.
getRank()
uint64_t mlir::sparse_tensor::SparseTensorStorageBase::getRank () const inline
Gets the rank of the tensor.
Definition at line 91 of file Storage.h.
Referenced by mlir::sparse_tensor::SparseTensorStorage< P, I, V >::expInsert(), mlir::sparse_tensor::SparseTensorNNZ::initialize(), mlir::sparse_tensor::SparseTensorEnumeratorBase< V >::SparseTensorEnumeratorBase(), mlir::sparse_tensor::SparseTensorStorage< P, I, V >::SparseTensorStorage(), SparseTensorStorageBase(), and mlir::sparse_tensor::SparseTensorStorage< P, I, V >::toCOO().
getRev()
const std::vector<uint64_t>& mlir::sparse_tensor::SparseTensorStorageBase::getRev () const inline
Gets the "reverse" permutation, which maps this object's storage-order to the tensor's semantic-order.
Definition at line 104 of file Storage.h.
isCompressedDim()
bool mlir::sparse_tensor::SparseTensorStorageBase::isCompressedDim (uint64_t d) const inline
Safely checks if the (storage-order) dimension uses compressed storage.
Definition at line 119 of file Storage.h.
References getDimType(), and mlir::sparse_tensor::isCompressedDLT().
Referenced by mlir::sparse_tensor::SparseTensorStorage< P, I, V >::SparseTensorStorage(), SparseTensorStorageBase(), and mlir::sparse_tensor::SparseTensorStorage< P, I, V >::toCOO().
isDenseDim()
bool mlir::sparse_tensor::SparseTensorStorageBase::isDenseDim (uint64_t d) const inline
Safely checks if the (storage-order) dimension uses dense storage.
Definition at line 116 of file Storage.h.
References getDimType(), and mlir::sparse_tensor::isDenseDLT().
Referenced by mlir::sparse_tensor::SparseTensorStorage< P, I, V >::SparseTensorStorage(), SparseTensorStorageBase(), and mlir::sparse_tensor::SparseTensorStorage< P, I, V >::toCOO().
isOrderedDim()
bool mlir::sparse_tensor::SparseTensorStorageBase::isOrderedDim (uint64_t d) const inline
Safely checks if the (storage-order) dimension is ordered.
Definition at line 129 of file Storage.h.
References getDimType(), and mlir::sparse_tensor::isOrderedDLT().
isSingletonDim()
bool mlir::sparse_tensor::SparseTensorStorageBase::isSingletonDim (uint64_t d) const inline
Safely checks if the (storage-order) dimension uses singleton storage.
Definition at line 124 of file Storage.h.
References getDimType(), and mlir::sparse_tensor::isSingletonDLT().
Referenced by mlir::sparse_tensor::SparseTensorStorage< P, I, V >::SparseTensorStorage(), SparseTensorStorageBase(), and mlir::sparse_tensor::SparseTensorStorage< P, I, V >::toCOO().
isUniqueDim()
bool mlir::sparse_tensor::SparseTensorStorageBase::isUniqueDim (uint64_t d) const inline
Safely checks if the (storage-order) dimension is unique.
Definition at line 132 of file Storage.h.
References getDimType(), and mlir::sparse_tensor::isUniqueDLT().
Referenced by mlir::sparse_tensor::SparseTensorStorage< P, I, V >::toCOO().
operator=()
SparseTensorStorageBase& mlir::sparse_tensor::SparseTensorStorageBase::operator= (const SparseTensorStorageBase &) protected delete
Referenced by mlir::sparse_tensor::SparseTensorEnumeratorBase< V >::SparseTensorEnumeratorBase().
The documentation for this class was generated from the following files:
include/mlir/ExecutionEngine/SparseTensor/Storage.h
lib/ExecutionEngine/SparseTensor/Storage.cpp