MLIR: mlir::sparse_tensor::SparseTensorNNZ Class Reference
mlir::sparse_tensor::SparseTensorNNZ Class Reference final
Statistics regarding the number of nonzero subtensors in a source tensor, for direct sparse=>sparse conversion a la https://arxiv.org/abs/2001.02609.
#include "mlir/ExecutionEngine/SparseTensor/Storage.h"
Public Types
using NNZConsumer = const std::function< void(uint64_t)> &
The type of callback functions which receive an nnz-statistic.
Public Member Functions
SparseTensorNNZ (const std::vector< uint64_t > &dimSizes, const std::vector< DimLevelType > &sparsity)
Allocates the statistics structure for the desired sizes and sparsity (in the target tensor's storage-order).
SparseTensorNNZ (const SparseTensorNNZ &)=delete
SparseTensorNNZ & operator= (const SparseTensorNNZ &)=delete
uint64_t getRank () const
Returns the rank of the target tensor.
template<typename V >
void initialize (SparseTensorEnumeratorBase< V > &enumerator)
Enumerates the source tensor to fill in the statistics.
void forallIndices (uint64_t stopDim, NNZConsumer yield) const
Lexicographically enumerates all indicies for dimensions strictly less than stopDim, and passes their nnz statistic to the callback.
Detailed Description
Statistics regarding the number of nonzero subtensors in a source tensor, for direct sparse=>sparse conversion a la https://arxiv.org/abs/2001.02609.
N.B., this class stores references to the parameters passed to the constructor; thus, objects of this class must not outlive those parameters.
Definition at line 681 of file Storage.h.
Member Typedef Documentation
NNZConsumer
using mlir::sparse_tensor::SparseTensorNNZ::NNZConsumer = const std::function<void(uint64_t)> &
The type of callback functions which receive an nnz-statistic.
Definition at line 711 of file Storage.h.
Constructor & Destructor Documentation
SparseTensorNNZ() [1/2]
SparseTensorNNZ::SparseTensorNNZ (const std::vector< uint64_t > & dimSizes, const std::vector< DimLevelType > & sparsity)
Allocates the statistics structure for the desired sizes and sparsity (in the target tensor's storage-order).
Allocate the statistics structure for the desired sizes and sparsity (in the target tensor's storage-order).
This constructor does not actually populate the statistics, however; for that see initialize.
Precondition: dimSizes must not contain zeros.
Definition at line 30 of file NNZ.cpp.
References mlir::sparse_tensor::detail::checkedMul(), getRank(), mlir::sparse_tensor::isCompressedDLT(), mlir::sparse_tensor::isDenseDLT(), mlir::sparse_tensor::isSingletonDLT(), and MLIR_SPARSETENSOR_FATAL.
SparseTensorNNZ() [2/2]
mlir::sparse_tensor::SparseTensorNNZ::SparseTensorNNZ (const SparseTensorNNZ &) delete
Member Function Documentation
forallIndices()
void SparseTensorNNZ::forallIndices (uint64_t stopDim, SparseTensorNNZ::NNZConsumer yield) const
Lexicographically enumerates all indicies for dimensions strictly less than stopDim, and passes their nnz statistic to the callback.
Since our use-case only requires the statistic not the coordinates themselves, we do not bother to construct those coordinates.
Definition at line 66 of file NNZ.cpp.
References getRank(), and mlir::sparse_tensor::isCompressedDLT().
Referenced by mlir::sparse_tensor::SparseTensorStorage< P, I, V >::SparseTensorStorage().
getRank()
uint64_t mlir::sparse_tensor::SparseTensorNNZ::getRank () const inline
Returns the rank of the target tensor.
Definition at line 697 of file Storage.h.
Referenced by forallIndices(), and SparseTensorNNZ().
initialize()
template<typename V > void mlir::sparse_tensor::SparseTensorNNZ::initialize (SparseTensorEnumeratorBase< V > & enumerator) inline
Enumerates the source tensor to fill in the statistics.
The enumerator should already incorporate the permutation (from semantic-order to the target storage-order).
Definition at line 703 of file Storage.h.
References mlir::sparse_tensor::SparseTensorEnumeratorBase< V >::forallElements(), mlir::sparse_tensor::SparseTensorStorageBase::getRank(), mlir::sparse_tensor::SparseTensorEnumeratorBase< V >::getRank(), and mlir::sparse_tensor::SparseTensorEnumeratorBase< V >::permutedSizes().
Referenced by mlir::sparse_tensor::SparseTensorStorage< P, I, V >::SparseTensorStorage().
operator=()
SparseTensorNNZ& mlir::sparse_tensor::SparseTensorNNZ::operator= (const SparseTensorNNZ &) delete
The documentation for this class was generated from the following files:
include/mlir/ExecutionEngine/SparseTensor/Storage.h
lib/ExecutionEngine/SparseTensor/NNZ.cpp