MLIR: mlir::sparse_tensor::SparseTensorEnumerator< P, I, V > Class Template Reference
mlir::sparse_tensor::SparseTensorEnumerator< P, I, V > Class Template Reference
#include "mlir/ExecutionEngine/SparseTensor/Storage.h"
Public Member Functions
SparseTensorEnumerator (const StorageImpl &tensor, uint64_t rank, const uint64_t *perm)
Constructs an enumerator with the given permutation for mapping the semantic-ordering of dimensions to the desired target-ordering.
~SparseTensorEnumerator () final=default
void forallElements (ElementConsumer< V > yield) final
Enumerates all elements of the source tensor, permutes their indices, and passes the permuted element to the callback.
Public Member Functions inherited from mlir::sparse_tensor::SparseTensorEnumeratorBase< V >
SparseTensorEnumeratorBase (const SparseTensorStorageBase &tensor, uint64_t rank, const uint64_t *perm)
Constructs an enumerator with the given permutation for mapping the semantic-ordering of dimensions to the desired target-ordering.
virtual ~SparseTensorEnumeratorBase ()=default
SparseTensorEnumeratorBase (const SparseTensorEnumeratorBase &)=delete
SparseTensorEnumeratorBase & operator= (const SparseTensorEnumeratorBase &)=delete
uint64_t getRank () const
Returns the source/target tensor's rank.
const std::vector< uint64_t > & permutedSizes () const
Returns the target tensor's dimension sizes.
Additional Inherited Members
Protected Attributes inherited from mlir::sparse_tensor::SparseTensorEnumeratorBase< V >
const SparseTensorStorageBase & src
std::vector< uint64_t > permsz
std::vector< uint64_t > reord
std::vector< uint64_t > cursor
Detailed Description
template<typename P, typename I, typename V>
class mlir::sparse_tensor::SparseTensorEnumerator< P, I, V >
Definition at line 183 of file Storage.h.
Constructor & Destructor Documentation
SparseTensorEnumerator()
template<typename P, typename I, typename V> mlir::sparse_tensor::SparseTensorEnumerator< P, I, V >::SparseTensorEnumerator (const StorageImpl & tensor, uint64_t rank, const uint64_t * perm) inline
Constructs an enumerator with the given permutation for mapping the semantic-ordering of dimensions to the desired target-ordering.
Precondition: perm must be valid for rank.
Definition at line 617 of file Storage.h.
~SparseTensorEnumerator()
template<typename P, typename I, typename V> mlir::sparse_tensor::SparseTensorEnumerator< P, I, V >::~SparseTensorEnumerator () final default
Member Function Documentation
forallElements()
template<typename P, typename I, typename V> void mlir::sparse_tensor::SparseTensorEnumerator< P, I, V >::forallElements (ElementConsumer< V > yield) inline final virtual
Enumerates all elements of the source tensor, permutes their indices, and passes the permuted element to the callback.
The callback must not store the cursor reference directly, since this function reuses the storage. Instead, the callback must copy it if they want to keep it.
Implements mlir::sparse_tensor::SparseTensorEnumeratorBase< V >.
Definition at line 623 of file Storage.h.
References mlir::sparse_tensor::isCompressedDLT(), mlir::sparse_tensor::isDenseDLT(), and mlir::sparse_tensor::isSingletonDLT().
The documentation for this class was generated from the following file:
include/mlir/ExecutionEngine/SparseTensor/Storage.h