MLIR: lib/Dialect/SparseTensor/Transforms/CodegenUtils.cpp File Reference
CodegenUtils.cpp File Reference
#include "CodegenUtils.h"
#include "mlir/Dialect/Affine/IR/AffineOps.h"
#include "mlir/Dialect/Bufferization/IR/Bufferization.h"
#include "mlir/Dialect/Linalg/IR/Linalg.h"
#include "mlir/Dialect/Linalg/Utils/Utils.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/Dialect/Tensor/IR/Tensor.h"
#include "mlir/IR/Matchers.h"
#include "mlir/IR/Types.h"
#include "mlir/IR/Value.h"
Macros
#define CASE(ONAME, O)
#define CASE(VNAME, V)
Functions
static Value genIndexLoad (OpBuilder &builder, Location loc, Value ptr, Value s)
Generates a pointer/index load from the sparse storage scheme.
static Optional< std::pair< Value, Value > > genSplitSparseConstant (OpBuilder &builder, Location loc, Value tensor)
If the tensor is a sparse constant, generates and returns the pair of the constants for the indices and the values.
static Value genIndexAndValueForSparse (OpBuilder &builder, Location loc, Value indices, Value values, SmallVectorImpl< Value > &indicesArray, ValueRange ivs, unsigned rank)
Generates the code to copy the index at indices[ivs] to ind, and return the value at value[ivs].
static Value genIndexAndValueForDense (OpBuilder &builder, Location loc, Value tensor, SmallVectorImpl< Value > &indicesArray, ValueRange ivs)
Generates the code to read the value from tensor[ivs], and conditionally stores the indices ivs to the memory in ind.
Macro Definition Documentation
CASE [1/2]
#define CASE (ONAME, O)
Value:
case OverheadType::kU##ONAME:                                                \
    return #ONAME;
Referenced by mlir::sparse_tensor::overheadTypeFunctionSuffix(), and mlir::sparse_tensor::primaryTypeFunctionSuffix().
CASE [2/2]
#define CASE (VNAME, V)
Value:
case PrimaryType::k##VNAME:                                                  \
    return #VNAME;
Function Documentation
genIndexAndValueForDense()
static Value genIndexAndValueForDense (OpBuilder & builder, Location loc, Value tensor, SmallVectorImpl< Value > & indicesArray, ValueRange ivs) static
Generates the code to read the value from tensor[ivs], and conditionally stores the indices ivs to the memory in ind.
The generated code looks like the following and the insertion point after this routine is inside the if-then branch behind the assignment to ind. This is to ensure that the code that uses the ind, such as an addEltX call generated after, is inside the if-then branch. if (tensor[ivs] != 0) ind = ivs
Definition at line 84 of file CodegenUtils.cpp.
References mlir::sparse_tensor::genValueForDense().
Referenced by mlir::sparse_tensor::genDenseTensorOrSparseConstantIterLoop().
genIndexAndValueForSparse()
static Value genIndexAndValueForSparse (OpBuilder & builder, Location loc, Value indices, Value values, SmallVectorImpl< Value > & indicesArray, ValueRange ivs, unsigned rank) static
Generates the code to copy the index at indices[ivs] to ind, and return the value at value[ivs].
Definition at line 61 of file CodegenUtils.cpp.
References mlir::sparse_tensor::constantIndex(), mlir::OpBuilder::create(), and mlir::Builder::getIndexType().
Referenced by mlir::sparse_tensor::genDenseTensorOrSparseConstantIterLoop().
genIndexLoad()
static Value genIndexLoad (OpBuilder & builder, Location loc, Value ptr, Value s) static
Generates a pointer/index load from the sparse storage scheme.
Narrower data types need to be zero extended before casting the value into the index type used for looping and indexing.
Definition at line 27 of file CodegenUtils.cpp.
References mlir::OpBuilder::create(), mlir::Builder::getI64Type(), mlir::Builder::getIndexType(), mlir::Type::getIntOrFloatBitWidth(), mlir::Value::getType(), and mlir::Type::isa().
Referenced by mlir::sparse_tensor::SparseTensorLoopEmitter::enterCoIterationOverTensorsAtDims(), and mlir::sparse_tensor::SparseTensorLoopEmitter::enterLoopOverTensorAtDim().
genSplitSparseConstant()
static Optional<std::pair<Value, Value> > genSplitSparseConstant (OpBuilder & builder, Location loc, Value tensor) static
If the tensor is a sparse constant, generates and returns the pair of the constants for the indices and the values.
Definition at line 46 of file CodegenUtils.cpp.
References mlir::OpBuilder::create(), mlir::Value::getDefiningOp(), and mlir::DenseElementsAttr::getValues().
Referenced by mlir::sparse_tensor::genDenseTensorOrSparseConstantIterLoop().