MLIR: lib/Target/LLVMIR/ConvertFromLLVMIR.cpp File Reference
ConvertFromLLVMIR.cpp File Reference
#include "mlir/Target/LLVMIR/Import.h"
#include "mlir/Dialect/DLTI/DLTI.h"
#include "mlir/Dialect/LLVMIR/LLVMDialect.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/MLIRContext.h"
#include "mlir/IR/Matchers.h"
#include "mlir/Interfaces/DataLayoutInterfaces.h"
#include "mlir/Target/LLVMIR/TypeFromLLVM.h"
#include "mlir/Tools/mlir-translate/Translation.h"
#include "llvm/ADT/PostOrderIterator.h"
#include "llvm/ADT/StringSet.h"
#include "llvm/ADT/TypeSwitch.h"
#include "llvm/IR/Attributes.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DebugInfoMetadata.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/InlineAsm.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/Type.h"
#include "llvm/IRReader/IRReader.h"
#include "llvm/Support/Error.h"
#include "llvm/Support/SourceMgr.h"
#include "mlir/Dialect/LLVMIR/LLVMConversionEnumsFromLLVM.inc"
#include "mlir/Dialect/LLVMIR/LLVMConvertibleLLVMIRIntrinsics.inc"
#include "mlir/Dialect/LLVMIR/LLVMIntrinsicFromLLVMIRConversions.inc"
#include "mlir/Dialect/LLVMIR/LLVMOpFromLLVMIRConversions.inc"
Namespaces
mlir
Include the generated interface declarations.
Functions
static bool isConvertibleIntrinsic (llvm::Intrinsic::ID id)
Returns true if the LLVM IR intrinsic is convertible to an MLIR LLVM dialect intrinsic, or false if no counterpart exists.
static std::string diag (llvm::Value &value)
static DenseIntElementsAttr parseDataLayoutAlignment (MLIRContext &ctx, StringRef spec)
Creates an attribute containing ABI and preferred alignment numbers parsed a string.
static FloatType getDLFloatType (MLIRContext &ctx, int32_t bitwidth)
Returns a supported MLIR floating point type of the given bit width or null if the bit width is not supported.
static ICmpPredicate getICmpPredicate (llvm::CmpInst::Predicate pred)
static FCmpPredicate getFCmpPredicate (llvm::CmpInst::Predicate pred)
static AtomicOrdering getLLVMAtomicOrdering (llvm::AtomicOrdering ordering)
static AtomicBinOp getLLVMAtomicBinOp (llvm::AtomicRMWInst::BinOp binOp)
static StringRef getLLVMSyncScope (llvm::FenceInst *fenceInst)
Converts the sync scope identifier of fenceInst to the string representation necessary to build the LLVM dialect fence operation.
static SmallVector< int64_t > getPositionFromIndices (ArrayRef< unsigned > indices)
Converts an array of unsigned indices to a signed integer position array.
static SetVector< llvm::BasicBlock * > getTopologicallySortedBlocks (llvm::Function *func)
Get a topologically sorted list of blocks for the given function.
static OwningOpRef< Operation * > translateLLVMIRToModule (llvm::SourceMgr &sourceMgr, MLIRContext *context)
void mlir::registerFromLLVMIRTranslation ()
Function Documentation
diag()
static std::string diag (llvm::Value & value) static
Definition at line 60 of file ConvertFromLLVMIR.cpp.
References value.
Referenced by adjustToDivisorsOfTripCounts(), alterGpuLaunch(), mlir::transform::TransformState::applyTransform(), mlir::transform::detail::applyTransformToEach(), mlir::DiagnosedDefiniteFailure::attachNote(), buildUnresolvedTargetMaterialization(), checkDoubleConsume(), cloneAndFuseFirstUse(), mlir::lsp::MLIRServer::convertFromBytecode(), mlir::Operation::create(), createGpuLaunch(), diagnoseInvalidOperandDominance(), mlir::detail::DiagnosticEngineImpl::emit(), mlir::DiagnosticEngine::emit(), emitDiag(), mlir::detail::Parser::emitError(), mlir::Operation::emitError(), mlir::Operation::emitRemark(), mlir::emitSilenceableFailure(), mlir::Operation::emitWarning(), mlir::detail::PassCrashReproducerGenerator::finalize(), findLiveUserOfReplaced(), forwardTerminatorOperands(), generateGpuBlockIds(), getBaseValue(), mlir::transform::TransformState::getHandlesForPayloadOp(), getLspDiagnoticFromDiag(), mlir::scf::getParallelForInductionVarOwner(), getTopologicallySortedBlocks(), legalizeUnresolvedMaterialization(), mlir::pdll::Lexer::Lexer(), loopScheduling(), mlir::transform::gpu::mapNestedForeachToThreadsImpl(), mlir::ConversionPattern::matchAndRewrite(), TransferWriteToVectorStoreLowering::matchAndRewrite(), mlir::RewriterBase::notifyMatchFailure(), mlir::detail::ConversionPatternRewriterImpl::notifyMatchFailure(), mlir::DiagnosedDefiniteFailure::operator DiagnosedSilenceableFailure(), mlir::DiagnosedDefiniteFailure::operator LogicalResult(), mlir::parseSourceString(), printAwaitResultType(), printInsertExtractValueElementType(), mlir::DiagnosticEngine::registerHandler(), mlir::detail::ConversionPatternRewriterImpl::remapValues(), mlir::DiagnosedSilenceableFailure::silenceableFailure(), mlir::SourceMgrDiagnosticHandler::SourceMgrDiagnosticHandler(), mlir::SourceMgrDiagnosticVerifierHandler::SourceMgrDiagnosticVerifierHandler(), mlir::transform::tileToForeachThreadOpImpl(), mlir::SourceMgrDiagnosticVerifierHandler::verify(), mlir::impl::verifyCastInterfaceOp(), mlir::detail::verifyDataLayoutOp(), verifyOpAndAdjustFlags(), mlir::transform::detail::verifyPossibleTopLevelTransformOpTrait(), verifyTypesAlongAllEdges(), and wrapInExecuteRegion().
getDLFloatType()
static FloatType getDLFloatType (MLIRContext & ctx, int32_t bitwidth) static
Returns a supported MLIR floating point type of the given bit width or null if the bit width is not supported.
Definition at line 90 of file ConvertFromLLVMIR.cpp.
References mlir::FloatType::getF128(), mlir::FloatType::getF16(), mlir::FloatType::getF32(), mlir::FloatType::getF64(), and mlir::FloatType::getF80().
Referenced by getTopologicallySortedBlocks().
getFCmpPredicate()
static FCmpPredicate getFCmpPredicate (llvm::CmpInst::Predicate pred) static
Definition at line 135 of file ConvertFromLLVMIR.cpp.
getICmpPredicate()
static ICmpPredicate getICmpPredicate (llvm::CmpInst::Predicate pred) static
Definition at line 107 of file ConvertFromLLVMIR.cpp.
getLLVMAtomicBinOp()
static AtomicBinOp getLLVMAtomicBinOp (llvm::AtomicRMWInst::BinOp binOp) static
Definition at line 195 of file ConvertFromLLVMIR.cpp.
References max(), and min().
getLLVMAtomicOrdering()
static AtomicOrdering getLLVMAtomicOrdering (llvm::AtomicOrdering ordering) static
Definition at line 175 of file ConvertFromLLVMIR.cpp.
getLLVMSyncScope()
static StringRef getLLVMSyncScope (llvm::FenceInst * fenceInst) static
Converts the sync scope identifier of fenceInst to the string representation necessary to build the LLVM dialect fence operation.
Definition at line 230 of file ConvertFromLLVMIR.cpp.
getPositionFromIndices()
static SmallVector<int64_t> getPositionFromIndices (ArrayRef< unsigned > indices) static
Converts an array of unsigned indices to a signed integer position array.
Definition at line 241 of file ConvertFromLLVMIR.cpp.
getTopologicallySortedBlocks()
static SetVector<llvm::BasicBlock *> getTopologicallySortedBlocks (llvm::Function * func) static
Get a topologically sorted list of blocks for the given function.
Definition at line 312 of file ConvertFromLLVMIR.cpp.
References mlir::Block::begin(), mlir::Constant, mlir::Operation::create(), diag(), mlir::Type::dyn_cast(), mlir::Type::dyn_cast_or_null(), mlir::emitError(), mlir::detail::enumerate(), mlir::failed(), mlir::failure(), mlir::DenseElementsAttr::get(), mlir::FloatType::getBF16(), getDLFloatType(), mlir::Operation::getResult(), mlir::LLVM::getVectorElementType(), mlir::LLVM::getVectorNumElements(), mlir::Type::isa(), mlir::LLVM::isCompatibleVectorType(), isConvertibleIntrinsic(), mlir::m_Constant(), mlir::matchPattern(), processValue(), mlir::succeeded(), mlir::success(), and value.
Referenced by mlir::LLVM::ModuleTranslation::symbolTable().
isConvertibleIntrinsic()
static bool isConvertibleIntrinsic (llvm::Intrinsic::ID id) static
Returns true if the LLVM IR intrinsic is convertible to an MLIR LLVM dialect intrinsic, or false if no counterpart exists.
Definition at line 50 of file ConvertFromLLVMIR.cpp.
Referenced by getTopologicallySortedBlocks().
parseDataLayoutAlignment()
static DenseIntElementsAttr parseDataLayoutAlignment (MLIRContext & ctx, StringRef spec) static
Creates an attribute containing ABI and preferred alignment numbers parsed a string.
The string may be either "abi:preferred" or just "abi". In the latter case, the prefrred alignment is considered equal to ABI alignment.
Definition at line 70 of file ConvertFromLLVMIR.cpp.
References mlir::DenseIntElementsAttr::get().
translateLLVMIRToModule()
static OwningOpRef<Operation *> translateLLVMIRToModule (llvm::SourceMgr & sourceMgr, MLIRContext * context) static
Definition at line 1156 of file ConvertFromLLVMIR.cpp.
References mlir::emitError(), and mlir::translateLLVMIRToModule().
Referenced by mlir::registerFromLLVMIRTranslation().