MLIR: lib/Analysis/DataFlow/DeadCodeAnalysis.cpp File Reference
DeadCodeAnalysis.cpp File Reference
#include "mlir/Analysis/DataFlow/DeadCodeAnalysis.h"
#include "mlir/Analysis/DataFlow/ConstantPropagationAnalysis.h"
#include "mlir/Interfaces/CallInterfaces.h"
#include "mlir/Interfaces/ControlFlowInterfaces.h"
Functions
static bool isRegionOrCallableReturn (Operation *op)
Returns true if the operation is a returning terminator in region control-flow or the terminator of a callable region.
static Optional< SmallVector< Attribute > > getOperandValuesImpl (Operation *op, function_ref< const Lattice< ConstantValue > *(Value)> getLattice)
Get the constant values of the operands of an operation.
Function Documentation
getOperandValuesImpl()
static Optional<SmallVector<Attribute> > getOperandValuesImpl (Operation * op, function_ref< const Lattice< ConstantValue > *(Value)> getLattice) static
Get the constant values of the operands of an operation.
If any of the constant value lattices are uninitialized, return none to indicate the analysis should bail out.
Definition at line 313 of file DeadCodeAnalysis.cpp.
References mlir::dataflow::ConstantValue::getConstantValue(), mlir::Operation::getNumOperands(), mlir::Operation::getOperands(), mlir::Operation::getParentRegion(), mlir::Region::getRegionNumber(), mlir::Block::getSuccessors(), mlir::dataflow::Lattice< ValueT >::getValue(), mlir::dataflow::ConstantValue::isUninitialized(), mlir::dataflow::PredecessorState::join(), mlir::DataFlowAnalysis::propagateIfChanged(), and value.
isRegionOrCallableReturn()
static bool isRegionOrCallableReturn (Operation * op) static
Returns true if the operation is a returning terminator in region control-flow or the terminator of a callable region.
Definition at line 176 of file DeadCodeAnalysis.cpp.
References mlir::failed(), mlir::failure(), mlir::Operation::getBlock(), mlir::Operation::getNumRegions(), mlir::Operation::getNumSuccessors(), mlir::Operation::getParentOp(), mlir::Operation::getRegions(), mlir::Block::getTerminator(), mlir::DataFlowAnalysis::propagateIfChanged(), mlir::success(), and mlir::dataflow::DeadCodeAnalysis::visit().
Referenced by mlir::dataflow::DeadCodeAnalysis::visit().