MLIR: lib/Target/LLVMIR/DebugTranslation.cpp File Reference
DebugTranslation.cpp File Reference
#include "DebugTranslation.h"
#include "mlir/Dialect/LLVMIR/LLVMDialect.h"
#include "llvm/ADT/TypeSwitch.h"
#include "llvm/IR/Metadata.h"
#include "llvm/IR/Module.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/Path.h"
Functions
static WalkResult interruptIfValidLocation (Operation *op)
A utility walker that interrupts if the operation has valid debug information.
template<class... Ts>
static llvm::DISubprogram * getSubprogram (bool isDistinct, Ts &&...args)
Return a new subprogram that is either distinct or not, depending on isDistinct.
Function Documentation
getSubprogram()
template<class... Ts> static llvm::DISubprogram* getSubprogram (bool isDistinct, Ts &&... args) static
Return a new subprogram that is either distinct or not, depending on isDistinct.
Definition at line 160 of file DebugTranslation.cpp.
References mlir::LLVM::detail::DebugTranslation::translate().
interruptIfValidLocation()
static WalkResult interruptIfValidLocation (Operation * op) static
A utility walker that interrupts if the operation has valid debug information.
Definition at line 23 of file DebugTranslation.cpp.
References mlir::WalkResult::advance(), mlir::Operation::getLoc(), mlir::WalkResult::interrupt(), and mlir::Location::isa().
Referenced by mlir::LLVM::detail::DebugTranslation::DebugTranslation().