MLIR: lib/Dialect/Linalg/Transforms/DecomposeLinalgOps.cpp File Reference
DecomposeLinalgOps.cpp File Reference
#include "mlir/Dialect/Linalg/Transforms/Transforms.h"
#include "mlir/Dialect/Affine/IR/AffineOps.h"
#include "mlir/Dialect/Linalg/IR/Linalg.h"
Functions
static SmallVector< OpFoldResult > getGenericOpLoopRange (OpBuilder &b, GenericOp op)
Helper method to compute the range of a generic op.
SmallVector< OpFoldResult > permuteValues (ArrayRef< OpFoldResult > values, AffineMap map)
Helper method to permute the list of values based on the map.
static Value getZero (OpBuilder &b, Location loc, Type elementType)
Get zero value for an element type.
Function Documentation
getGenericOpLoopRange()
static SmallVector<OpFoldResult> getGenericOpLoopRange (OpBuilder & b, GenericOp op) static
Helper method to compute the range of a generic op.
Definition at line 104 of file DecomposeLinalgOps.cpp.
References mlir::makeComposedFoldedMultiResultAffineApply(), and mlir::OpBuilder::setInsertionPoint().
Referenced by getZero().
getZero()
static Value getZero (OpBuilder & b, Location loc, Type elementType) static
Get zero value for an element type.
Definition at line 131 of file DecomposeLinalgOps.cpp.
References mlir::Block::begin(), mlir::Value::cast(), mlir::Type::cast(), mlir::OpBuilder::create(), mlir::Value::dyn_cast(), mlir::Block::empty(), mlir::detail::enumerate(), mlir::Builder::getAffineMapArrayAttr(), mlir::Block::getArgument(), mlir::Operation::getBlock(), getGenericOpLoopRange(), mlir::Builder::getMultiDimIdentityMap(), mlir::Operation::getNumResults(), mlir::Block::getOperations(), mlir::detail::IROperandBase::getOwner(), mlir::OpResult::getOwner(), mlir::Operation::getResults(), mlir::Block::getTerminator(), mlir::Builder::getType(), mlir::Value::getType(), mlir::Type::isa(), mlir::Type::isIndex(), mlir::Type::isIntOrIndexOrFloat(), mlir::RewriterBase::notifyMatchFailure(), mlir::RewriterBase::replaceOp(), mlir::RewriterBase::replaceOpWithinBlock(), mlir::Value::replaceUsesWithIf(), mlir::OpBuilder::setInsertionPointToEnd(), and mlir::success().
Referenced by calculateCarry(), castBoolToIntN(), checkIntFloatCast(), mlir::detail::DenseResourceElementsAttrBase< T >::classof(), createInitialValueForReduceOp(), getLocalInvocationDimSize(), mlir::linalg::getNeutralElement(), mlir::spirv::getOpenCLElementPtr(), mlir::spirv::getPushConstantValue(), getScalarOrVectorI32Constant(), mlir::spirv::getVulkanElementPtr(), lowerEntryPointABIAttr(), mlir::ConstantIntRanges::maxRange(), signedCeilNonnegInputs(), truncIRange(), and verifyConstantType().
permuteValues()
SmallVector<OpFoldResult> permuteValues (ArrayRef< OpFoldResult > values, AffineMap map)
Helper method to permute the list of values based on the map.
Definition at line 118 of file DecomposeLinalgOps.cpp.
References mlir::detail::enumerate(), mlir::AffineMap::getResults(), and mlir::AffineMap::isPermutation().