MLIR: lib/Dialect/SPIRV/Transforms/DecorateCompositeTypeLayoutPass.cpp File Reference
DecorateCompositeTypeLayoutPass.cpp File Reference
#include "mlir/Dialect/SPIRV/Transforms/Passes.h"
#include "mlir/Dialect/Func/IR/FuncOps.h"
#include "mlir/Dialect/SPIRV/IR/SPIRVDialect.h"
#include "mlir/Dialect/SPIRV/IR/SPIRVOps.h"
#include "mlir/Dialect/SPIRV/Utils/LayoutUtils.h"
#include "mlir/Transforms/DialectConversion.h"
#include "mlir/Dialect/SPIRV/Transforms/Passes.h.inc"
Namespaces
mlir
Include the generated interface declarations.
mlir::spirv
Macros
#define GEN_PASS_DEF_SPIRVCOMPOSITETYPELAYOUT
Functions
static void populateSPIRVLayoutInfoPatterns (RewritePatternSet &patterns)
Macro Definition Documentation
GEN_PASS_DEF_SPIRVCOMPOSITETYPELAYOUT
#define GEN_PASS_DEF_SPIRVCOMPOSITETYPELAYOUT
Definition at line 28 of file DecorateCompositeTypeLayoutPass.cpp.
Function Documentation
populateSPIRVLayoutInfoPatterns()
static void populateSPIRVLayoutInfoPatterns (RewritePatternSet & patterns) static
Definition at line 98 of file DecorateCompositeTypeLayoutPass.cpp.
References mlir::RewritePatternSet::add(), mlir::ConversionTarget::addDynamicallyLegalOp(), mlir::ConversionTarget::addLegalDialect(), mlir::ConversionTarget::addLegalOp(), mlir::applyFullConversion(), mlir::failed(), mlir::RewritePatternSet::getContext(), and mlir::VulkanLayoutUtils::isLegalType().