MLIR: lib/Dialect/Linalg/Transforms/Detensorize.cpp File Reference
Detensorize.cpp File Reference
#include "mlir/Dialect/Linalg/Passes.h"
#include "mlir/Dialect/ControlFlow/IR/ControlFlowOps.h"
#include "mlir/Dialect/Func/IR/FuncOps.h"
#include "mlir/Dialect/Func/Transforms/FuncConversions.h"
#include "mlir/Dialect/Linalg/IR/Linalg.h"
#include "mlir/Dialect/Tensor/IR/Tensor.h"
#include "mlir/IR/OpDefinition.h"
#include "mlir/Transforms/DialectConversion.h"
#include "mlir/Transforms/GreedyPatternRewriteDriver.h"
#include <iterator>
#include <memory>
#include <utility>
#include "mlir/Dialect/Linalg/Passes.h.inc"
Namespaces
mlir
Include the generated interface declarations.
Macros
#define GEN_PASS_DEF_LINALGDETENSORIZE
Functions
static Value sourceMaterializationCallback (OpBuilder &builder, Type type, ValueRange inputs, Location loc)
Macro Definition Documentation
GEN_PASS_DEF_LINALGDETENSORIZE
#define GEN_PASS_DEF_LINALGDETENSORIZE
Definition at line 24 of file Detensorize.cpp.
Function Documentation
sourceMaterializationCallback()
static Value sourceMaterializationCallback (OpBuilder & builder, Type type, ValueRange inputs, Location loc) static
Definition at line 31 of file Detensorize.cpp.
References mlir::RewritePatternSet::add(), mlir::ConversionTarget::addDynamicallyLegalOp(), mlir::TypeConverter::SignatureConversion::addInputs(), mlir::applyFullConversion(), mlir::applyPatternsAndFoldGreedily(), mlir::Block::begin(), mlir::ConversionPatternRewriter::cancelRootUpdate(), mlir::Value::cast(), mlir::ConversionPatternRewriter::convertNonEntryRegionTypes(), mlir::OpBuilder::create(), mlir::Value::dyn_cast(), mlir::Operation::erase(), mlir::ConversionPatternRewriter::eraseOp(), mlir::failed(), mlir::failure(), mlir::ConversionPatternRewriter::finalizeRootUpdate(), mlir::BlockArgument::getArgNumber(), mlir::Value::getDefiningOp(), mlir::TensorType::getElementType(), mlir::Operation::getOperands(), mlir::BlockArgument::getOwner(), mlir::Value::getParentBlock(), mlir::Operation::getResultTypes(), mlir::Block::getTerminator(), mlir::Value::getType(), mlir::ValueRange::getType(), mlir::Value::getUsers(), mlir::TensorType::hasRank(), mlir::ConversionPatternRewriter::inlineRegionBefore(), mlir::TypeConverter::isLegal(), mlir::isLegalForReturnOpTypeConversionPattern(), mlir::isNotBranchOpInterfaceOrReturnLikeOp(), mlir::ConversionTarget::markUnknownOpDynamicallyLegal(), mlir::ConversionPatternRewriter::mergeBlocks(), mlir::OpConversionPattern< SourceOp >::OpConversionPattern(), mlir::populateBranchOpInterfaceTypeConversionPattern(), mlir::Block::pred_begin(), mlir::Block::pred_end(), mlir::ConversionPatternRewriter::replaceOp(), mlir::ConversionPatternRewriter::splitBlock(), mlir::ConversionPatternRewriter::startRootUpdate(), mlir::success(), and value.