MLIR: lib/Dialect/SCF/IR/SCF.cpp File Reference
SCF.cpp File Reference
#include "mlir/Dialect/SCF/IR/SCF.h"
#include "mlir/Dialect/Arith/IR/Arith.h"
#include "mlir/Dialect/Arith/Utils/Utils.h"
#include "mlir/Dialect/Bufferization/IR/Bufferization.h"
#include "mlir/Dialect/ControlFlow/IR/ControlFlowOps.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/Dialect/Tensor/IR/Tensor.h"
#include "mlir/IR/BlockAndValueMapping.h"
#include "mlir/IR/FunctionInterfaces.h"
#include "mlir/IR/Matchers.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/Support/MathExtras.h"
#include "mlir/Transforms/InliningUtils.h"
#include "mlir/Dialect/SCF/IR/SCFOpsDialect.cpp.inc"
#include "mlir/Dialect/SCF/IR/SCFOps.cpp.inc"
Classes
struct SingleBlockExecuteInliner
struct MultiBlockExecuteInliner
Macros
#define GET_OP_LIST
#define GET_OP_CLASSES
Functions
static void replaceOpWithRegion (PatternRewriter &rewriter, Operation *op, Region &region, ValueRange blockArgs={})
Replaces the given op with the contents of the given single-block region, using the operands of the block terminator to replace operation results.
static void printInitializationList (OpAsmPrinter &p, Block::BlockArgListType blocksArgs, ValueRange initializers, StringRef prefix="")
Prints the initialization list in the form of <prefix>(inner = outer, inner2 = outer2, <...>) where 'inner' values are assumed to be region arguments and 'outer' values are regular SSA values.
template<typename T >
static FailureOr< SmallVector< T > > permute (const SmallVector< T > &vals, ArrayRef< int64_t > perm)
template<typename T >
static FailureOr< SmallVector< T > > getValuesPermutedByThreadMapping (scf::ForeachThreadOp foreachThreadOp, const SmallVector< T > &values)
Helper to get apply the thread_dim_mapping permutation of a foreachThreadOp to values.
Macro Definition Documentation
GET_OP_CLASSES
#define GET_OP_CLASSES
GET_OP_LIST
#define GET_OP_LIST
Function Documentation
getValuesPermutedByThreadMapping()
template<typename T > static FailureOr<SmallVector<T> > getValuesPermutedByThreadMapping (scf::ForeachThreadOp foreachThreadOp, const SmallVector< T > & values) static
Helper to get apply the thread_dim_mapping permutation of a foreachThreadOp to values.
Definition at line 1309 of file SCF.cpp.
References mlir::extractFromI64ArrayAttr(), mlir::failed(), mlir::Builder::getIndexAttr(), and permute().
permute()
template<typename T > static FailureOr<SmallVector<T> > permute (const SmallVector< T > & vals, ArrayRef< int64_t > perm) static
Definition at line 1286 of file SCF.cpp.
References mlir::failure().
Referenced by getValuesPermutedByThreadMapping().
printInitializationList()
static void printInitializationList (OpAsmPrinter & p, Block::BlockArgListType blocksArgs, ValueRange initializers, StringRef prefix = "") static
Prints the initialization list in the form of <prefix>(inner = outer, inner2 = outer2, <...>) where 'inner' values are assumed to be region arguments and 'outer' values are regular SSA values.
Definition at line 370 of file SCF.cpp.
References mlir::OperationState::addRegion(), mlir::OperationState::attributes, mlir::Value::dyn_cast(), mlir::AsmParser::emitError(), mlir::failure(), mlir::AsmParser::getBuilder(), mlir::scf::getForInductionVarOwner(), mlir::Builder::getIndexType(), mlir::AsmParser::getNameLoc(), mlir::OperationState::location, mlir::OperationState::operands, mlir::OpAsmParser::parseArgument(), mlir::AsmParser::parseArrowTypeList(), mlir::OpAsmParser::parseAssignmentList(), mlir::AsmParser::parseEqual(), mlir::AsmParser::parseKeyword(), mlir::OpAsmParser::parseOperand(), mlir::AsmParser::parseOptionalAttrDict(), mlir::AsmParser::parseOptionalKeyword(), mlir::OpAsmParser::parseRegion(), print(), mlir::OpAsmPrinter::printOptionalAttrDict(), mlir::OpAsmPrinter::printRegion(), mlir::OpAsmParser::resolveOperand(), mlir::succeeded(), mlir::success(), mlir::OpAsmParser::Argument::type, and mlir::OperationState::types.
Referenced by mlir::scf::buildLoopNest(), and mlir::scf::getParallelForInductionVarOwner().
replaceOpWithRegion()
static void replaceOpWithRegion (PatternRewriter & rewriter, Operation * op, Region & region, ValueRange blockArgs = {}) static
Replaces the given op with the contents of the given single-block region, using the operands of the block terminator to replace operation results.
Definition at line 85 of file SCF.cpp.
References mlir::OperationState::addRegion(), mlir::OperationState::attributes, mlir::RewriterBase::eraseOp(), mlir::failure(), mlir::Region::front(), mlir::Operation::getOperands(), mlir::Block::getTerminator(), mlir::RewriterBase::mergeBlockBefore(), mlir::AsmParser::parseOptionalArrowTypeList(), mlir::AsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::parseRegion(), print(), mlir::AsmPrinter::printOptionalArrowTypeList(), mlir::OpAsmPrinter::printOptionalAttrDict(), mlir::OpAsmPrinter::printRegion(), mlir::RewriterBase::replaceOp(), mlir::success(), mlir::OperationState::types, and mlir::verify().
Referenced by mlir::scf::buildLoopNest(), mlir::scf::insideMutuallyExclusiveBranches(), and SingleBlockExecuteInliner::matchAndRewrite().