MLIR: lib/AsmParser/DialectSymbolParser.cpp File Reference
DialectSymbolParser.cpp File Reference
#include "AsmParserImpl.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/Dialect.h"
#include "mlir/IR/DialectImplementation.h"
#include "llvm/Support/SourceMgr.h"
Functions
template<typename Symbol , typename SymbolAliasMap , typename CreateFn >
static Symbol parseExtendedSymbol (Parser &p, SymbolAliasMap &aliases, CreateFn &&createSymbol)
Parse an extended dialect symbol.
template<typename T , typename ParserFn >
static T parseSymbol (StringRef inputStr, MLIRContext *context, size_t &numRead, ParserFn &&parserFn)
Parses a symbol, of type 'T', and returns it if parsing was successful.
Function Documentation
parseExtendedSymbol()
template<typename Symbol , typename SymbolAliasMap , typename CreateFn > static Symbol parseExtendedSymbol (Parser & p, SymbolAliasMap & aliases, CreateFn && createSymbol) static
Parse an extended dialect symbol.
Definition at line 149 of file DialectSymbolParser.cpp.
References mlir::detail::Parser::codeCompleteDialectSymbol(), mlir::detail::Parser::consumeToken(), mlir::detail::Parser::emitWrongTokenError(), mlir::Token::getLoc(), mlir::Token::getSpelling(), mlir::detail::Parser::getToken(), mlir::detail::Parser::getTokenSpelling(), mlir::Token::is(), mlir::Token::isCodeCompletion(), and mlir::detail::Parser::parseDialectSymbolBody().
parseSymbol()
template<typename T , typename ParserFn > static T parseSymbol (StringRef inputStr, MLIRContext * context, size_t & numRead, ParserFn && parserFn) static
Parses a symbol, of type 'T', and returns it if parsing was successful.
If parsing failed, nullptr is returned. The number of bytes read from the input string is returned in 'numRead'.
Definition at line 301 of file DialectSymbolParser.cpp.
References mlir::detail::Parser::getContext(), mlir::Type::getContext(), mlir::Token::getLoc(), mlir::detail::Parser::getSourceMgr(), mlir::detail::Parser::getToken(), mlir::parseAttribute(), and mlir::parseType().