MLIR: lib/Dialect/Bufferization/Transforms/DropEquivalentBufferResults.cpp File Reference
DropEquivalentBufferResults.cpp File Reference
#include "mlir/Dialect/Bufferization/Transforms/Passes.h"
#include "mlir/Dialect/Func/IR/FuncOps.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/IR/Operation.h"
#include "mlir/Pass/Pass.h"
#include "mlir/Dialect/Bufferization/Transforms/Passes.h.inc"
Namespaces
mlir
Include the generated interface declarations.
mlir::bufferization
Macros
#define GEN_PASS_DEF_DROPEQUIVALENTBUFFERRESULTS
Functions
static func::ReturnOp getAssumedUniqueReturnOp (func::FuncOp funcOp)
Return the unique ReturnOp that terminates funcOp.
static func::FuncOp getCalledFunction (CallOpInterface callOp)
Return the func::FuncOp called by callOp.
Macro Definition Documentation
GEN_PASS_DEF_DROPEQUIVALENTBUFFERRESULTS
#define GEN_PASS_DEF_DROPEQUIVALENTBUFFERRESULTS
Definition at line 39 of file DropEquivalentBufferResults.cpp.
Function Documentation
getAssumedUniqueReturnOp()
static func::ReturnOp getAssumedUniqueReturnOp (func::FuncOp funcOp) static
Return the unique ReturnOp that terminates funcOp.
Return nullptr if there is no such unique ReturnOp.
Definition at line 48 of file DropEquivalentBufferResults.cpp.
Referenced by mlir::bufferization::dropEquivalentBufferResults().
getCalledFunction()
static func::FuncOp getCalledFunction (CallOpInterface callOp) static
Return the func::FuncOp called by callOp.
Definition at line 61 of file DropEquivalentBufferResults.cpp.
References mlir::SymbolTable::lookupNearestSymbolFrom().
Referenced by mlir::bufferization::dropEquivalentBufferResults().