MLIR: lib/Dialect/Tensor/Transforms/ExtractSliceFromReshapeUtils.cpp File Reference
ExtractSliceFromReshapeUtils.cpp File Reference
#include "mlir/Dialect/Affine/IR/AffineOps.h"
#include "mlir/Dialect/Arith/IR/Arith.h"
#include "mlir/Dialect/Arith/Utils/Utils.h"
#include "mlir/Dialect/Tensor/IR/Tensor.h"
#include "mlir/Dialect/Tensor/Transforms/TransformUtils.h"
#include "mlir/Dialect/Tensor/Transforms/Transforms.h"
#include "mlir/Dialect/Utils/ReshapeOpsUtils.h"
#include "mlir/Dialect/Utils/StaticValueUtils.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/OpDefinition.h"
#include "llvm/ADT/STLExtras.h"
Typedefs
using DimAndIndex = std::tuple< unsigned, Value >
A tuple that represents (dimension number, dimension value).
Functions
static OpFoldResult getShapeDimSize (OpBuilder &b, Location loc, Value rankedTensor, int64_t dimIdx)
Get the dimension size of a value of RankedTensor type at the.
static SmallVector< OpFoldResult > getShapeDimSizes (OpBuilder &b, Location loc, Value rankedTensor)
Get all the dimension sizes of a value of RankedTensor type.
static DimAndIndex invertSliceIndexing (OpBuilder &b, Location loc, ArrayRef< Range > sliceParams, const DimAndIndex &dimAndIndex)
Transform dimAndIndex from the output index space of a (non-rank-reducing) slice described by sliceParams into the input index space.
static ValueRange invertCollapseShapeIndexing (OpBuilder &b, Location loc, ArrayRef< ReassociationIndices > reassociation, ArrayRef< OpFoldResult > reshapeSourceShape, const DimAndIndex &dimAndIndex)
Transform dimAndIndex from the result tensor index space of a CollapseShapeOp to the source tensor index space.
Typedef Documentation
DimAndIndex
using DimAndIndex = std::tuple<unsigned, Value>
A tuple that represents (dimension number, dimension value).
Definition at line 50 of file ExtractSliceFromReshapeUtils.cpp.
Function Documentation
getShapeDimSize()
static OpFoldResult getShapeDimSize (OpBuilder & b, Location loc, Value rankedTensor, int64_t dimIdx) static
Get the dimension size of a value of RankedTensor type at the.
Definition at line 29 of file ExtractSliceFromReshapeUtils.cpp.
References mlir::Type::cast(), mlir::OpBuilder::create(), mlir::OpBuilder::createOrFold(), mlir::Builder::getIndexAttr(), and mlir::Value::getType().
Referenced by getShapeDimSizes().
getShapeDimSizes()
static SmallVector<OpFoldResult> getShapeDimSizes (OpBuilder & b, Location loc, Value rankedTensor) static
Get all the dimension sizes of a value of RankedTensor type.
Definition at line 40 of file ExtractSliceFromReshapeUtils.cpp.
References mlir::Type::cast(), getShapeDimSize(), and mlir::Value::getType().
Referenced by mlir::tensor::ExtractSliceFromCollapseHelper::create(), and mlir::tensor::simplifyCollapseShapeWithRankReducingExtractSlice().
invertCollapseShapeIndexing()
static ValueRange invertCollapseShapeIndexing (OpBuilder & b, Location loc, ArrayRef< ReassociationIndices > reassociation, ArrayRef< OpFoldResult > reshapeSourceShape, const DimAndIndex & dimAndIndex) static
Transform dimAndIndex from the result tensor index space of a CollapseShapeOp to the source tensor index space.
Definition at line 73 of file ExtractSliceFromReshapeUtils.cpp.
References mlir::OpBuilder::create(), and mlir::Operation::getResults().
Referenced by mlir::tensor::ExtractSliceFromCollapseHelper::emitLoopNestBody().
invertSliceIndexing()
static DimAndIndex invertSliceIndexing (OpBuilder & b, Location loc, ArrayRef< Range > sliceParams, const DimAndIndex & dimAndIndex) static
Transform dimAndIndex from the output index space of a (non-rank-reducing) slice described by sliceParams into the input index space.
Definition at line 54 of file ExtractSliceFromReshapeUtils.cpp.
References mlir::bindDims(), mlir::bindSymbols(), mlir::Builder::getContext(), mlir::getValueOrCreateConstantIndexOp(), and mlir::makeComposedAffineApply().
Referenced by mlir::tensor::ExtractSliceFromCollapseHelper::emitLoopNestBody().