MLIR: lib/Dialect/MemRef/Transforms/FoldMemRefAliasOps.cpp File Reference
FoldMemRefAliasOps.cpp File Reference
#include "mlir/Dialect/MemRef/Transforms/Passes.h"
#include "mlir/Dialect/Affine/IR/AffineOps.h"
#include "mlir/Dialect/Arith/IR/Arith.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/Dialect/Utils/IndexingUtils.h"
#include "mlir/Dialect/Vector/IR/VectorOps.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/Transforms/GreedyPatternRewriteDriver.h"
#include "llvm/ADT/SmallBitVector.h"
#include "llvm/ADT/TypeSwitch.h"
#include "mlir/Dialect/MemRef/Transforms/Passes.h.inc"
Namespaces
mlir
Include the generated interface declarations.
mlir::memref
Macros
#define GEN_PASS_DEF_FOLDMEMREFALIASOPS
Functions
static LogicalResult resolveSourceIndicesExpandShape (Location loc, PatternRewriter &rewriter, memref::ExpandShapeOp expandShapeOp, ValueRange indices, SmallVectorImpl< Value > &sourceIndices)
Given the 'indices' of a load/store operation where the memref is a result of a expand_shape op, returns the indices w.r.t to the source memref of the expand_shape op.
static LogicalResult resolveSourceIndicesCollapseShape (Location loc, PatternRewriter &rewriter, memref::CollapseShapeOp collapseShapeOp, ValueRange indices, SmallVectorImpl< Value > &sourceIndices)
Given the 'indices' of a load/store operation where the memref is a result of a collapse_shape op, returns the indices w.r.t to the source memref of the collapse_shape op.
static LogicalResult resolveSourceIndicesSubView (Location loc, PatternRewriter &rewriter, memref::SubViewOp subViewOp, ValueRange indices, SmallVectorImpl< Value > &sourceIndices)
Given the 'indices' of an load/store operation where the memref is a result of a subview op, returns the indices w.r.t to the source memref of the subview op.
template<typename LoadOrStoreOpTy >
static Value getMemRefOperand (LoadOrStoreOpTy op)
Helpers to access the memref operand for each op.
static Value getMemRefOperand (vector::TransferReadOp op)
static Value getMemRefOperand (vector::TransferWriteOp op)
static AffineMapAttr getPermutationMapAttr (MLIRContext *context, memref::SubViewOp subViewOp, AffineMap currPermutationMap)
Given the permutation map of the original vector.transfer_read/vector.transfer_write operations compute the permutation map to use after the subview is folded with it.
static SmallVector< Value > calculateExpandedAccessIndices (AffineMap affineMap, const SmallVector< Value > &indices, Location loc, PatternRewriter &rewriter)
Macro Definition Documentation
GEN_PASS_DEF_FOLDMEMREFALIASOPS
#define GEN_PASS_DEF_FOLDMEMREFALIASOPS
Definition at line 28 of file FoldMemRefAliasOps.cpp.
Function Documentation
calculateExpandedAccessIndices()
static SmallVector<Value> calculateExpandedAccessIndices (AffineMap affineMap, const SmallVector< Value > & indices, Location loc, PatternRewriter & rewriter) static
Definition at line 300 of file FoldMemRefAliasOps.cpp.
References mlir::OpBuilder::create(), mlir::failed(), mlir::failure(), mlir::Builder::getContext(), getMemRefOperand(), mlir::AffineMap::getNumResults(), getPermutationMapAttr(), mlir::AffineMap::getSubMap(), mlir::RewriterBase::replaceOpWithNewOp(), resolveSourceIndicesCollapseShape(), resolveSourceIndicesExpandShape(), resolveSourceIndicesSubView(), and mlir::success().
getMemRefOperand() [1/3]
template<typename LoadOrStoreOpTy > static Value getMemRefOperand (LoadOrStoreOpTy op) static
Helpers to access the memref operand for each op.
Definition at line 201 of file FoldMemRefAliasOps.cpp.
Referenced by calculateExpandedAccessIndices().
getMemRefOperand() [2/3]
static Value getMemRefOperand (vector::TransferReadOp op) static
Definition at line 205 of file FoldMemRefAliasOps.cpp.
getMemRefOperand() [3/3]
static Value getMemRefOperand (vector::TransferWriteOp op) static
Definition at line 209 of file FoldMemRefAliasOps.cpp.
getPermutationMapAttr()
static AffineMapAttr getPermutationMapAttr (MLIRContext * context, memref::SubViewOp subViewOp, AffineMap currPermutationMap) static
Given the permutation map of the original vector.transfer_read/vector.transfer_write operations compute the permutation map to use after the subview is folded with it.
Definition at line 216 of file FoldMemRefAliasOps.cpp.
References mlir::AffineMap::compose(), mlir::AffineMap::get(), and mlir::getAffineDimExpr().
Referenced by calculateExpandedAccessIndices().
resolveSourceIndicesCollapseShape()
static LogicalResult resolveSourceIndicesCollapseShape (Location loc, PatternRewriter & rewriter, memref::CollapseShapeOp collapseShapeOp, ValueRange indices, SmallVectorImpl< Value > & sourceIndices) static
Given the 'indices' of a load/store operation where the memref is a result of a collapse_shape op, returns the indices w.r.t to the source memref of the collapse_shape op.
For example
%0 = ... : memref<2x6x42xf32> %1 = memref.collapse_shape %0 [[0, 1], [2]] : memref<2x6x42xf32> into memref<12x42xf32> %2 = load %1[i1, i2] : memref<12x42xf32>
could be folded into
%2 = load %0[i1 / 6, i1 % 6, i2] : memref<2x6x42xf32>
Definition at line 97 of file FoldMemRefAliasOps.cpp.
References mlir::OpBuilder::create(), mlir::AffineMap::get(), mlir::Builder::getConstantAffineMap(), mlir::getDelinearizedAffineExpr(), and mlir::success().
Referenced by calculateExpandedAccessIndices().
resolveSourceIndicesExpandShape()
static LogicalResult resolveSourceIndicesExpandShape (Location loc, PatternRewriter & rewriter, memref::ExpandShapeOp expandShapeOp, ValueRange indices, SmallVectorImpl< Value > & sourceIndices) static
Given the 'indices' of a load/store operation where the memref is a result of a expand_shape op, returns the indices w.r.t to the source memref of the expand_shape op.
For example
%0 = ... : memref<12x42xf32> %1 = memref.expand_shape %0 [[0, 1], [2]] : memref<12x42xf32> into memref<2x6x42xf32> %2 = load %1[i1, i2, i3] : memref<2x6x42xf32
could be folded into
%2 = load %0[6 * i1 + i2, i3] : memref<12x42xf32>
Definition at line 53 of file FoldMemRefAliasOps.cpp.
References mlir::OpBuilder::create(), mlir::AffineMap::get(), mlir::getLinearAffineExpr(), and mlir::success().
Referenced by calculateExpandedAccessIndices().
resolveSourceIndicesSubView()
static LogicalResult resolveSourceIndicesSubView (Location loc, PatternRewriter & rewriter, memref::SubViewOp subViewOp, ValueRange indices, SmallVectorImpl< Value > & sourceIndices) static
Given the 'indices' of an load/store operation where the memref is a result of a subview op, returns the indices w.r.t to the source memref of the subview op.
For example
%0 = ... : memref<12x42xf32> %1 = subview %0[arg0, arg1][][stride1, stride2] : memref<12x42xf32> to memref<4x4xf32, offset=?, strides=[?, ?]> %2 = load %1[i1, i2] : memref<4x4xf32, offset=?, strides=[?, ?]>
could be folded into
%2 = load %0[arg0 + i1 * stride1][arg1 + i2 * stride2] : memref<12x42xf32>
Definition at line 150 of file FoldMemRefAliasOps.cpp.
References mlir::AffineExpr::cast(), mlir::OpBuilder::create(), mlir::failure(), mlir::AffineMap::get(), mlir::Builder::getAffineDimExpr(), mlir::Builder::getAffineSymbolExpr(), and mlir::success().
Referenced by calculateExpandedAccessIndices().