MLIR: lib/Dialect/Linalg/Transforms/Generalization.cpp File Reference
Generalization.cpp File Reference
#include "mlir/Dialect/Linalg/Passes.h"
#include "mlir/Dialect/Func/IR/FuncOps.h"
#include "mlir/Dialect/Linalg/IR/Linalg.h"
#include "mlir/Dialect/Linalg/Transforms/Transforms.h"
#include "mlir/IR/AffineMap.h"
#include "mlir/IR/Attributes.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/ImplicitLocOpBuilder.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/Transforms/GreedyPatternRewriteDriver.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/Support/Debug.h"
#include "mlir/Dialect/Linalg/Passes.h.inc"
Namespaces
mlir
Include the generated interface declarations.
Macros
#define GEN_PASS_DEF_LINALGGENERALIZATION
#define DEBUG_TYPE "linalg-generalization"
Functions
static LogicalResult generalizeNamedOpPrecondition (LinalgOp linalgOp)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "linalg-generalization"
Definition at line 33 of file Generalization.cpp.
GEN_PASS_DEF_LINALGGENERALIZATION
#define GEN_PASS_DEF_LINALGGENERALIZATION
Definition at line 29 of file Generalization.cpp.
Function Documentation
generalizeNamedOpPrecondition()
static LogicalResult generalizeNamedOpPrecondition (LinalgOp linalgOp) static
Definition at line 38 of file Generalization.cpp.
References mlir::failure(), and mlir::success().
Referenced by mlir::linalg::generalizeNamedOp().