MLIR: lib/Dialect/GPU/IR/InferIntRangeInterfaceImpls.cpp File Reference
InferIntRangeInterfaceImpls.cpp File Reference
#include "mlir/Dialect/GPU/IR/GPUDialect.h"
#include "mlir/Interfaces/InferIntRangeInterface.h"
Functions
static ConstantIntRanges getIndexRange (uint64_t umin, uint64_t umax)
Variables
static constexpr uint64_t kMaxDim = std::numeric_limits<uint32_t>::max()
static constexpr uint64_t kMaxSubgroupSize = 128
Function Documentation
getIndexRange()
static ConstantIntRanges getIndexRange (uint64_t umin, uint64_t umax) static
Definition at line 20 of file InferIntRangeInterfaceImpls.cpp.
References mlir::ConstantIntRanges::fromUnsigned(), mlir::ConstantIntRanges::intersection(), kMaxDim, kMaxSubgroupSize, max(), mlir::ConstantIntRanges::umax(), mlir::ConstantIntRanges::umin(), mlir::gpu::KernelDim3::x, mlir::gpu::KernelDim3::y, and mlir::gpu::KernelDim3::z.
Variable Documentation
kMaxDim
constexpr uint64_t kMaxDim = std::numeric_limits<uint32_t>::max() static
Definition at line 16 of file InferIntRangeInterfaceImpls.cpp.
Referenced by getIndexRange().
kMaxSubgroupSize
constexpr uint64_t kMaxSubgroupSize = 128 static
Definition at line 18 of file InferIntRangeInterfaceImpls.cpp.
Referenced by getIndexRange().