MLIR: lib/Conversion/GPUCommon/GPUToLLVMConversion.cpp File Reference
GPUToLLVMConversion.cpp File Reference
#include "mlir/Conversion/GPUCommon/GPUCommonPass.h"
#include "mlir/Conversion/ArithToLLVM/ArithToLLVM.h"
#include "mlir/Conversion/AsyncToLLVM/AsyncToLLVM.h"
#include "mlir/Conversion/ControlFlowToLLVM/ControlFlowToLLVM.h"
#include "mlir/Conversion/FuncToLLVM/ConvertFuncToLLVM.h"
#include "mlir/Conversion/FuncToLLVM/ConvertFuncToLLVMPass.h"
#include "mlir/Conversion/LLVMCommon/ConversionTarget.h"
#include "mlir/Conversion/LLVMCommon/Pattern.h"
#include "mlir/Conversion/MemRefToLLVM/MemRefToLLVM.h"
#include "mlir/Conversion/VectorToLLVM/ConvertVectorToLLVM.h"
#include "mlir/Dialect/Async/IR/Async.h"
#include "mlir/Dialect/GPU/IR/GPUDialect.h"
#include "mlir/Dialect/GPU/Transforms/Passes.h"
#include "mlir/Dialect/LLVMIR/LLVMDialect.h"
#include "mlir/IR/Attributes.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/BuiltinTypes.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/Support/Error.h"
#include "llvm/Support/FormatVariadic.h"
#include "mlir/Conversion/Passes.h.inc"
Namespaces
mlir
Include the generated interface declarations.
Macros
#define GEN_PASS_DEF_GPUTOLLVMCONVERSIONPASS
Functions
static LogicalResult areAllLLVMTypes (Operation *op, ValueRange operands, ConversionPatternRewriter &rewriter)
static LogicalResult isAsyncWithOneDependency (ConversionPatternRewriter &rewriter, gpu::AsyncOpInterface op)
static bool isGpuAsyncTokenType (Value value)
static bool isDefinedByCallTo (Value value, StringRef functionName)
Variables
static constexpr const char * kGpuBinaryStorageSuffix = "_gpubin_cst"
Macro Definition Documentation
GEN_PASS_DEF_GPUTOLLVMCONVERSIONPASS
#define GEN_PASS_DEF_GPUTOLLVMCONVERSIONPASS
Definition at line 41 of file GPUToLLVMConversion.cpp.
Function Documentation
areAllLLVMTypes()
static LogicalResult areAllLLVMTypes (Operation * op, ValueRange operands, ConversionPatternRewriter & rewriter) static
Definition at line 419 of file GPUToLLVMConversion.cpp.
References mlir::Value::getType(), mlir::LLVM::isCompatibleType(), mlir::ConversionPatternRewriter::notifyMatchFailure(), mlir::success(), and value.
Referenced by isAsyncWithOneDependency(), and isDefinedByCallTo().
isAsyncWithOneDependency()
static LogicalResult isAsyncWithOneDependency (ConversionPatternRewriter & rewriter, gpu::AsyncOpInterface op) static
Definition at line 430 of file GPUToLLVMConversion.cpp.
References areAllLLVMTypes(), mlir::Attribute::cast(), mlir::OpBuilder::create(), mlir::ConversionPatternRewriter::eraseOp(), mlir::failed(), mlir::failure(), getElementPtrType(), getElementType(), getSizeInBytes(), mlir::ConversionPatternRewriter::notifyMatchFailure(), mlir::ConversionPatternRewriter::replaceOp(), and mlir::success().
Referenced by isDefinedByCallTo().
isDefinedByCallTo()
static bool isDefinedByCallTo (Value value, StringRef functionName) static
Definition at line 564 of file GPUToLLVMConversion.cpp.
References areAllLLVMTypes(), mlir::Operation::create(), mlir::OpBuilder::create(), mlir::LLVM::createGlobalString(), mlir::LLVMTypeConverter::dangerousSetOptions(), mlir::detail::enumerate(), mlir::ConversionPatternRewriter::eraseOp(), mlir::failed(), mlir::failure(), mlir::Value::getDefiningOp(), getElementPtrType(), mlir::Type::getIntOrFloatBitWidth(), mlir::LLVM::LLVMStructType::getNewIdentified(), getNumElements(), mlir::LLVMTypeConverter::getOptions(), mlir::Value::getType(), mlir::Type::isa(), isAsyncWithOneDependency(), mlir::Type::isIntOrFloat(), kGpuBinaryStorageSuffix, mlir::ConversionPatternRewriter::notifyMatchFailure(), options, mlir::LLVMTypeConverter::promoteOperands(), mlir::ConversionPatternRewriter::replaceOp(), mlir::OpBuilder::restoreInsertionPoint(), mlir::OpBuilder::saveInsertionPoint(), mlir::OpBuilder::setInsertionPointAfter(), mlir::success(), mlir::LowerToLLVMOptions::useBarePtrCallConv, and value.
isGpuAsyncTokenType()
static bool isGpuAsyncTokenType (Value value) static
Definition at line 528 of file GPUToLLVMConversion.cpp.
References mlir::Value::getType(), mlir::Type::isa(), mlir::ConversionPatternRewriter::notifyMatchFailure(), mlir::success(), and mlir::RewriterBase::updateRootInPlace().
Variable Documentation
kGpuBinaryStorageSuffix
constexpr const char* kGpuBinaryStorageSuffix = "_gpubin_cst" static
Definition at line 47 of file GPUToLLVMConversion.cpp.
Referenced by isDefinedByCallTo().