MLIR: lib/Dialect/Index/IR/IndexOps.cpp File Reference
IndexOps.cpp File Reference
#include "mlir/Dialect/Index/IR/IndexOps.h"
#include "mlir/Dialect/Index/IR/IndexAttrs.h"
#include "mlir/Dialect/Index/IR/IndexDialect.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/OpImplementation.h"
#include "mlir/Dialect/Index/IR/IndexOps.cpp.inc"
Macros
#define GET_OP_LIST
#define GET_OP_CLASSES
Functions
static OpFoldResult foldBinaryOpUnchecked (ArrayRef< Attribute > operands, function_ref< Optional< APInt >(const APInt &, const APInt &)> calculate)
Fold an index operation irrespective of the target bitwidth.
static OpFoldResult foldBinaryOpChecked (ArrayRef< Attribute > operands, function_ref< Optional< APInt >(const APInt &, const APInt &lhs)> calculate)
Fold an index operation only if the truncated 64-bit result matches the 32-bit result for operations that don't satisfy the above property.
static Optional< APInt > calculateCeilDivS (const APInt &n, const APInt &m)
Compute ceildivs(n, m) as x = m > 0 ? -1 : 1 and then n*m > 0 ? (n+x)/m + 1 : -(-n/m).
static Optional< APInt > calculateFloorDivS (const APInt &n, const APInt &m)
Compute floordivs(n, m) as x = m < 0 ? 1 : -1 and then n*m < 0 ? -1 - (x-n)/m : n/m.
bool compareIndices (const APInt &lhs, const APInt &rhs, IndexCmpPredicate pred)
Compare two integers according to the comparison predicate.
Macro Definition Documentation
GET_OP_CLASSES
#define GET_OP_CLASSES
Definition at line 421 of file IndexOps.cpp.
GET_OP_LIST
#define GET_OP_LIST
Function Documentation
calculateCeilDivS()
static Optional<APInt> calculateCeilDivS (const APInt & n, const APInt & m) static
Compute ceildivs(n, m) as x = m > 0 ? -1 : 1 and then n*m > 0 ? (n+x)/m + 1 : -(-n/m).
Definition at line 175 of file IndexOps.cpp.
References foldBinaryOpChecked(), and None.
calculateFloorDivS()
static Optional<APInt> calculateFloorDivS (const APInt & n, const APInt & m) static
Compute floordivs(n, m) as x = m < 0 ? 1 : -1 and then n*m < 0 ? -1 - (x-n)/m : n/m.
Definition at line 225 of file IndexOps.cpp.
References foldBinaryOpChecked(), and None.
compareIndices()
bool compareIndices (const APInt & lhs, const APInt & rhs, IndexCmpPredicate pred)
Compare two integers according to the comparison predicate.
Definition at line 354 of file IndexOps.cpp.
foldBinaryOpChecked()
static OpFoldResult foldBinaryOpChecked (ArrayRef< Attribute > operands, function_ref< Optional< APInt >(const APInt &, const APInt &lhs)> calculate) static
Fold an index operation only if the truncated 64-bit result matches the 32-bit result for operations that don't satisfy the above property.
These are operations where the upper bits of the operands can affect the lower bits of the results.
The function accepts a lambda that computes the integer result in both 64-bit and 32-bit. If either call returns None, the operation is not folded.
Definition at line 88 of file IndexOps.cpp.
Referenced by calculateCeilDivS(), and calculateFloorDivS().
foldBinaryOpUnchecked()
static OpFoldResult foldBinaryOpUnchecked (ArrayRef< Attribute > operands, function_ref< Optional< APInt >(const APInt &, const APInt &)> calculate) static
Fold an index operation irrespective of the target bitwidth.
The operation must satisfy the property:
trunc(f(a, b)) = f(trunc(a), trunc(b))
For all values of a and b. The function accepts a lambda that computes the integer result, which in turn must satisfy the above property.
Definition at line 63 of file IndexOps.cpp.