MLIR: lib/ExecutionEngine/JitRunner.cpp File Reference
JitRunner.cpp File Reference
#include "mlir/ExecutionEngine/JitRunner.h"
#include "mlir/Dialect/LLVMIR/LLVMDialect.h"
#include "mlir/ExecutionEngine/ExecutionEngine.h"
#include "mlir/ExecutionEngine/OptUtils.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/MLIRContext.h"
#include "mlir/Parser/Parser.h"
#include "mlir/Support/FileUtilities.h"
#include "mlir/Tools/ParseUtilities.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ExecutionEngine/Orc/JITTargetMachineBuilder.h"
#include "llvm/ExecutionEngine/Orc/LLJIT.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/LegacyPassNameParser.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/FileUtilities.h"
#include "llvm/Support/SourceMgr.h"
#include "llvm/Support/StringSaver.h"
#include "llvm/Support/ToolOutputFile.h"
#include <cstdint>
#include <numeric>
#include <utility>
Functions
static OwningOpRef< Operation * > parseMLIRInput (StringRef inputFilename, bool insertImplicitModule, MLIRContext *context)
static Error makeStringError (const Twine &message)
static Optional< unsigned > getCommandLineOptLevel (Options &options)
static Error compileAndExecute (Options &options, Operation *module, StringRef entryPoint, CompileAndExecuteConfig config, void **args)
static Error compileAndExecuteVoidFunction (Options &options, Operation *module, StringRef entryPoint, CompileAndExecuteConfig config)
template<typename Type >
Error checkCompatibleReturnType (LLVM::LLVMFuncOp mainFunction)
template<>
Error checkCompatibleReturnType< int32_t > (LLVM::LLVMFuncOp mainFunction)
template<>
Error checkCompatibleReturnType< int64_t > (LLVM::LLVMFuncOp mainFunction)
template<>
Error checkCompatibleReturnType< float > (LLVM::LLVMFuncOp mainFunction)
template<typename Type >
Error compileAndExecuteSingleReturnFunction (Options &options, Operation *module, StringRef entryPoint, CompileAndExecuteConfig config)
Function Documentation
checkCompatibleReturnType()
template<typename Type > Error checkCompatibleReturnType (LLVM::LLVMFuncOp mainFunction)
Referenced by compileAndExecuteVoidFunction().
checkCompatibleReturnType< float >()
template<> Error checkCompatibleReturnType< float > (LLVM::LLVMFuncOp mainFunction)
Definition at line 294 of file JitRunner.cpp.
References makeStringError(), and mlir::success().
checkCompatibleReturnType< int32_t >()
template<> Error checkCompatibleReturnType< int32_t > (LLVM::LLVMFuncOp mainFunction)
Definition at line 274 of file JitRunner.cpp.
References makeStringError(), and mlir::success().
checkCompatibleReturnType< int64_t >()
template<> Error checkCompatibleReturnType< int64_t > (LLVM::LLVMFuncOp mainFunction)
Definition at line 284 of file JitRunner.cpp.
References makeStringError(), and mlir::success().
compileAndExecute()
static Error compileAndExecute (Options & options, Operation * module, StringRef entryPoint, CompileAndExecuteConfig config, void ** args) static
Definition at line 167 of file JitRunner.cpp.
References mlir::ExecutionEngine::create(), mlir::ExecutionEngineOptions::enableObjectDump, getCommandLineOptLevel(), mlir::ExecutionEngineOptions::jitCodeGenOptLevel, mlir::ExecutionEngineOptions::llvmModuleBuilder, mlir::ExecutionEngineOptions::sharedLibPaths, mlir::success(), and mlir::ExecutionEngineOptions::transformer.
Referenced by compileAndExecuteVoidFunction().
compileAndExecuteSingleReturnFunction()
template<typename Type > Error compileAndExecuteSingleReturnFunction (Options & options, Operation * module, StringRef entryPoint, CompileAndExecuteConfig config)
Definition at line 303 of file JitRunner.cpp.
References mlir::Error, mlir::SymbolTable::lookupSymbolIn(), and makeStringError().
compileAndExecuteVoidFunction()
static Error compileAndExecuteVoidFunction (Options & options, Operation * module, StringRef entryPoint, CompileAndExecuteConfig config) static
Definition at line 259 of file JitRunner.cpp.
References checkCompatibleReturnType(), compileAndExecute(), mlir::Error, mlir::SymbolTable::lookupSymbolIn(), and makeStringError().
Referenced by mlir::JitRunnerMain().
getCommandLineOptLevel()
static Optional<unsigned> getCommandLineOptLevel (Options & options) static
Definition at line 150 of file JitRunner.cpp.
Referenced by compileAndExecute(), and mlir::JitRunnerMain().
makeStringError()
static Error makeStringError (const Twine & message) inline static
Definition at line 145 of file JitRunner.cpp.
Referenced by checkCompatibleReturnType< float >(), checkCompatibleReturnType< int32_t >(), checkCompatibleReturnType< int64_t >(), compileAndExecuteSingleReturnFunction(), compileAndExecuteVoidFunction(), and mlir::JitRunnerMain().
parseMLIRInput()
static OwningOpRef<Operation *> parseMLIRInput (StringRef inputFilename, bool insertImplicitModule, MLIRContext * context) static
Definition at line 121 of file JitRunner.cpp.
References mlir::OwningOpRef< OpTy >::get(), mlir::Operation::hasTrait(), mlir::openInputFile(), and mlir::parseSourceFileForTool().
Referenced by mlir::JitRunnerMain().