MLIR: lib/Dialect/Linalg/IR/LinalgOps.cpp File Reference
LinalgOps.cpp File Reference
#include "mlir/Dialect/Linalg/IR/Linalg.h"
#include "mlir/AsmParser/AsmParser.h"
#include "mlir/Dialect/Affine/IR/AffineOps.h"
#include "mlir/Dialect/Arith/IR/Arith.h"
#include "mlir/Dialect/Arith/Utils/Utils.h"
#include "mlir/Dialect/Complex/IR/Complex.h"
#include "mlir/Dialect/Math/IR/Math.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/Dialect/SCF/IR/SCF.h"
#include "mlir/Dialect/SparseTensor/IR/SparseTensor.h"
#include "mlir/Dialect/Tensor/IR/Tensor.h"
#include "mlir/Dialect/Utils/ReshapeOpsUtils.h"
#include "mlir/Dialect/Utils/StaticValueUtils.h"
#include "mlir/IR/AffineExprVisitor.h"
#include "mlir/IR/AffineMap.h"
#include "mlir/IR/Matchers.h"
#include "mlir/IR/OpImplementation.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/Interfaces/InferTypeOpInterface.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/SmallSet.h"
#include "llvm/ADT/StringSet.h"
#include "llvm/ADT/TypeSwitch.h"
#include "llvm/Support/FormatVariadic.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/raw_ostream.h"
#include "mlir/Dialect/Linalg/IR/LinalgNamedStructuredOps.yamlgen.cpp.inc"
#include "mlir/Dialect/Linalg/IR/LinalgOps.cpp.inc"
#include "mlir/Dialect/Linalg/IR/LinalgStructuredOps.cpp.inc"
Macros
#define GET_OP_CLASSES
#define GET_OP_CLASSES
Typedefs
using RegionBuilderFn = llvm::function_ref< void(ImplicitLocOpBuilder &, Block &, ArrayRef< NamedAttribute >)>
Functions
static void fillStructuredOpRegion (OpBuilder &opBuilder, Region &region, TypeRange inputTypes, TypeRange outputTypes, ArrayRef< NamedAttribute > attrs, RegionBuilderFn regionBuilder)
Fills the region of a structured operation using the provided regionBuilder.
static void buildStructuredOp (OpBuilder &b, OperationState &state, llvm::Optional< TypeRange > resultTensorTypes, ValueRange inputs, ValueRange outputs, ArrayRef< NamedAttribute > attributes, RegionBuilderFn regionBuilder)
Creates a structured operation given inputs, outputs, and attributes.
static ParseResult parseCommonStructuredOpParts (OpAsmParser &parser, OperationState &result, SmallVectorImpl< Type > &inputTypes, SmallVectorImpl< Type > &outputTypes, bool addOperandSegmentSizes=true)
Common parsing used for both named structured ops created by ods-gen and by manually defined C++ ops.
static void printCommonStructuredOpParts (OpAsmPrinter &p, ValueRange inputs, ValueRange outputs)
static void printCommonStructuredOpPartsWithNewLine (OpAsmPrinter &p, ValueRange inputs, ValueRange outputs)
static ParseResult parseNamedStructuredOpRegion (OpAsmParser &parser, Region &region, unsigned numRegionArgs, TypeRange inputTypes, TypeRange outputTypes, ArrayRef< NamedAttribute > attrs, RegionBuilderFn regionBuilder)
static ParseResult parseNamedStructuredOpResults (OpAsmParser &parser, SmallVectorImpl< Type > &resultTypes)
static ParseResult parseNamedStructuredOp (OpAsmParser &parser, OperationState &result, unsigned numRegionArgs, RegionBuilderFn regionBuilder)
static void printNamedStructuredOpResults (OpAsmPrinter &p, TypeRange resultTypes)
static void printNamedStructuredOp (OpAsmPrinter &p, Operation *op, ValueRange inputs, ValueRange outputs)
static void buildGenericRegion (OpBuilder &builder, Location loc, Region &region, ValueRange inputs, ValueRange outputs, function_ref< void(OpBuilder &, Location, ValueRange)> bodyBuild)
static void getGenericEffectsImpl (SmallVectorImpl< SideEffects::EffectInstance< MemoryEffects::Effect >> &effects, ValueRange results, OpOperandVector inputOperands, OpOperandVector outputOperands)
static bool isResultValueDead (linalg::GenericOp genericOp, OpResult result)
static ParseResult parseDstStyleOp (OpAsmParser &parser, OperationState &result, function_ref< ParseResult(OpAsmParser &, NamedAttrList &)> parseAttrsFn=nullptr)
static ParseResult parseDenseI64ArrayAttr (OpAsmParser &parser, NamedAttrList &attributes, StringRef attributeName)
static void printDenseI64ArrayAttr (OpAsmPrinter &p, StringRef attributeName, ArrayRef< int64_t > attributeValue)
static void buildIdentityRegion (OpBuilder &builder, Location loc, Region &region, ValueRange inputs, ValueRange outputs)
static LogicalResult verifyYield (linalg::YieldOp op, LinalgOp linalgOp)
static void appendMangledType (llvm::raw_string_ostream &ss, Type t)
Macro Definition Documentation
GET_OP_CLASSES [1/2]
#define GET_OP_CLASSES
Definition at line 1993 of file LinalgOps.cpp.
GET_OP_CLASSES [2/2]
#define GET_OP_CLASSES
Definition at line 1993 of file LinalgOps.cpp.
Typedef Documentation
RegionBuilderFn
using RegionBuilderFn = llvm::function_ref<void(ImplicitLocOpBuilder &, Block &, ArrayRef<NamedAttribute>)>
Definition at line 50 of file LinalgOps.cpp.
Function Documentation
appendMangledType()
static void appendMangledType (llvm::raw_string_ostream & ss, Type t) static
Definition at line 2037 of file LinalgOps.cpp.
References mlir::Type::dyn_cast(), and mlir::Type::isSignlessIntOrIndexOrFloat().
Referenced by mlir::linalg::generateLibraryCallName().
buildGenericRegion()
static void buildGenericRegion (OpBuilder & builder, Location loc, Region & region, ValueRange inputs, ValueRange outputs, function_ref< void(OpBuilder &, Location, ValueRange)> bodyBuild) static
Definition at line 664 of file LinalgOps.cpp.
References mlir::OperationState::addAttributes(), mlir::OperationState::addRegion(), mlir::OperationState::addTypes(), mlir::NamedAttrList::assign(), mlir::OperationState::attributes, mlir::OpBuilder::createBlock(), mlir::Region::end(), mlir::failed(), mlir::failure(), mlir::Builder::getAffineMapArrayAttr(), mlir::Block::getArguments(), mlir::getElementTypeOrSelf(), mlir::Builder::getStrArrayAttr(), mlir::Builder::getStringAttr(), mlir::OperationState::location, mlir::AsmParser::parseAttribute(), parseCommonStructuredOpParts(), mlir::AsmParser::parseEqual(), parseNamedStructuredOpResults(), mlir::AsmParser::parseOptionalAttrDict(), mlir::AsmParser::parseOptionalKeyword(), mlir::OpAsmParser::parseRegion(), print(), printCommonStructuredOpParts(), printNamedStructuredOpResults(), mlir::OpAsmPrinter::printOptionalAttrDict(), mlir::OpAsmPrinter::printRegion(), mlir::OperationState::regions, mlir::succeeded(), and mlir::success().
Referenced by buildIdentityRegion(), and parseDstStyleOp().
buildIdentityRegion()
static void buildIdentityRegion (OpBuilder & builder, Location loc, Region & region, ValueRange inputs, ValueRange outputs) static
Definition at line 1653 of file LinalgOps.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::addAttributes(), mlir::OperationState::addOperands(), mlir::OperationState::addRegion(), mlir::OperationState::addTypes(), mlir::OperationState::attributes, buildGenericRegion(), mlir::OpBuilder::create(), mlir::OpAsmPrinter::decreaseIndent(), mlir::detail::enumerate(), mlir::failed(), mlir::failure(), mlir::Builder::getAffineMapArrayAttr(), mlir::AsmParser::getContext(), mlir::AsmParser::getCurrentLocation(), mlir::Builder::getDenseI64ArrayAttr(), getGenericEffectsImpl(), mlir::Builder::getMultiDimIdentityMap(), mlir::getParallelIteratorTypeName(), mlir::AffineMap::getPermutationMap(), mlir::AffineMap::getSubMap(), mlir::Value::getType(), mlir::OpAsmPrinter::increaseIndent(), mlir::Type::isa(), mlir::linalg::isPermutation(), mlir::OperationState::location, mlir::OperationState::name, mlir::OperationState::operands, mlir::AsmParser::parseColonTypeList(), parseDenseI64ArrayAttr(), parseDstStyleOp(), mlir::OpAsmParser::parseOperandList(), mlir::AsmParser::parseOptionalAttrDict(), print(), printCommonStructuredOpPartsWithNewLine(), printDenseI64ArrayAttr(), mlir::OpAsmPrinter::printNewline(), mlir::OpAsmPrinter::printOptionalAttrDict(), mlir::OpAsmParser::resolveOperands(), mlir::success(), and mlir::verify().
buildStructuredOp()
static void buildStructuredOp (OpBuilder & b, OperationState & state, llvm::Optional< TypeRange > resultTensorTypes, ValueRange inputs, ValueRange outputs, ArrayRef< NamedAttribute > attributes, RegionBuilderFn regionBuilder) static
Creates a structured operation given inputs, outputs, and attributes.
The result types are derived automatically if resultTensorTypes is none. The body of the operation is filled using regionBuilder. All ods-gen created structured operations use the method to implement their builders.
Definition at line 95 of file LinalgOps.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::addAttributes(), mlir::OperationState::addOperands(), mlir::OperationState::addRegion(), mlir::OperationState::addTypes(), mlir::OperationState::attributes, fillStructuredOpRegion(), mlir::NamedAttrList::getAttrs(), mlir::Builder::getDenseI32ArrayAttr(), and mlir::ValueRange::getTypes().
fillStructuredOpRegion()
static void fillStructuredOpRegion (OpBuilder & opBuilder, Region & region, TypeRange inputTypes, TypeRange outputTypes, ArrayRef< NamedAttribute > attrs, RegionBuilderFn regionBuilder) static
Fills the region of a structured operation using the provided regionBuilder.
The method is used by both named structured ops created by ods-gen and by manually defined C++ ops. It is called by both builders and parsers and creates a block with arguments corresponding to the elemental types of inputTypes and outputTypes. All output types are asserted to be ShapedType.
Definition at line 58 of file LinalgOps.cpp.
References mlir::OpBuilder::createBlock(), mlir::getElementTypeOrSelf(), mlir::Builder::getUnknownLoc(), mlir::Type::isa(), and mlir::OpBuilder::setInsertionPointToStart().
Referenced by buildStructuredOp(), and parseNamedStructuredOpRegion().
getGenericEffectsImpl()
static void getGenericEffectsImpl (SmallVectorImpl< SideEffects::EffectInstance< MemoryEffects::Effect >> & effects, ValueRange results, OpOperandVector inputOperands, OpOperandVector outputOperands) static
Definition at line 836 of file LinalgOps.cpp.
References mlir::SideEffects::Effect::Base< DerivedEffect, BaseEffect >::get(), and mlir::SideEffects::Resource::Base< DefaultResource >::get().
Referenced by buildIdentityRegion(), and parseDstStyleOp().
isResultValueDead()
static bool isResultValueDead (linalg::GenericOp genericOp, OpResult result) static
Definition at line 864 of file LinalgOps.cpp.
References mlir::RewritePatternSet::add(), mlir::OpBuilder::create(), mlir::Block::empty(), mlir::detail::enumerate(), mlir::RewriterBase::eraseOp(), mlir::failure(), mlir::memref::foldMemRefCast(), mlir::Block::front(), mlir::IROperand< DerivedT, IRValueT >::get(), mlir::Builder::getAffineMapArrayAttr(), mlir::Block::getArgument(), mlir::Operation::getOperand(), mlir::OpOperand::getOperandNumber(), mlir::Operation::getResult(), mlir::OpResult::getResultNumber(), mlir::sparse_tensor::getSparseTensorEncoding(), mlir::Block::getTerminator(), mlir::Value::getType(), mlir::Value::hasOneUse(), mlir::Operation::hasOneUse(), mlir::RewriterBase::mergeBlocks(), mlir::RewriterBase::replaceOp(), mlir::RewriterBase::replaceOpWithNewOp(), mlir::OpBuilder::setInsertionPoint(), mlir::success(), mlir::RewriterBase::updateRootInPlace(), mlir::Value::use_empty(), mlir::Operation::use_empty(), mlir::Value::user_begin(), mlir::Operation::user_begin(), and mlir::verify().
parseCommonStructuredOpParts()
static ParseResult parseCommonStructuredOpParts (OpAsmParser & parser, OperationState & result, SmallVectorImpl< Type > & inputTypes, SmallVectorImpl< Type > & outputTypes, bool addOperandSegmentSizes = true) static
Common parsing used for both named structured ops created by ods-gen and by manually defined C++ ops.
Does not handle regions.
Definition at line 125 of file LinalgOps.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::attributes, mlir::failure(), mlir::AsmParser::getBuilder(), mlir::AsmParser::getCurrentLocation(), mlir::Builder::getDenseI32ArrayAttr(), mlir::OperationState::operands, mlir::AsmParser::parseColonTypeList(), mlir::AsmParser::parseLParen(), mlir::OpAsmParser::parseOperandList(), mlir::AsmParser::parseOptionalAttrDict(), mlir::AsmParser::parseOptionalKeyword(), mlir::AsmParser::parseRParen(), mlir::OpAsmParser::resolveOperands(), mlir::succeeded(), and mlir::success().
Referenced by buildGenericRegion(), parseDstStyleOp(), and parseNamedStructuredOp().
parseDenseI64ArrayAttr()
static ParseResult parseDenseI64ArrayAttr (OpAsmParser & parser, NamedAttrList & attributes, StringRef attributeName) static
Definition at line 1508 of file LinalgOps.cpp.
References mlir::OperationState::addRegion(), mlir::failure(), mlir::AsmParser::Paren, mlir::detail::DenseArrayAttrImpl< T >::parse(), mlir::OpAsmParser::parseArgumentList(), parseDstStyleOp(), mlir::AsmParser::parseEqual(), mlir::AsmParser::parseKeyword(), mlir::OpAsmParser::parseRegion(), mlir::NamedAttrList::set(), and mlir::success().
Referenced by buildIdentityRegion().
parseDstStyleOp()
static ParseResult parseDstStyleOp (OpAsmParser & parser, OperationState & result, function_ref< ParseResult(OpAsmParser &, NamedAttrList &)> parseAttrsFn = nullptr) static
Definition at line 1299 of file LinalgOps.cpp.
References mlir::OperationState::addAttributes(), mlir::OperationState::addRegion(), mlir::OperationState::addTypes(), mlir::OperationState::attributes, buildGenericRegion(), mlir::AffineMap::dropResults(), mlir::failed(), mlir::failure(), mlir::Builder::getAffineMapArrayAttr(), getElementType(), getGenericEffectsImpl(), mlir::AffineMap::getMultiDimIdentityMap(), mlir::Builder::getMultiDimIdentityMap(), mlir::getParallelIteratorTypeName(), mlir::getReductionIteratorTypeName(), getShape(), mlir::Value::getType(), mlir::OpAsmPrinter::increaseIndent(), mlir::Type::isa(), mlir::OperationState::location, mlir::AsmParser::Paren, mlir::OpAsmParser::parseArgumentList(), parseCommonStructuredOpParts(), mlir::AsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::parseRegion(), print(), printCommonStructuredOpPartsWithNewLine(), mlir::OpAsmPrinter::printNewline(), mlir::OpAsmPrinter::printOptionalAttrDict(), mlir::OpAsmPrinter::printRegion(), mlir::OpAsmPrinter::printRegionArgument(), mlir::OperationState::regions, mlir::success(), and mlir::verify().
Referenced by buildIdentityRegion(), and parseDenseI64ArrayAttr().
parseNamedStructuredOp()
static ParseResult parseNamedStructuredOp (OpAsmParser & parser, OperationState & result, unsigned numRegionArgs, RegionBuilderFn regionBuilder) static
Definition at line 218 of file LinalgOps.cpp.
References mlir::OperationState::addRegion(), mlir::OperationState::addTypes(), mlir::OperationState::attributes, mlir::failure(), mlir::NamedAttrList::getAttrs(), parseCommonStructuredOpParts(), parseNamedStructuredOpRegion(), parseNamedStructuredOpResults(), and mlir::success().
parseNamedStructuredOpRegion()
static ParseResult parseNamedStructuredOpRegion (OpAsmParser & parser, Region & region, unsigned numRegionArgs, TypeRange inputTypes, TypeRange outputTypes, ArrayRef< NamedAttribute > attrs, RegionBuilderFn regionBuilder) static
Definition at line 192 of file LinalgOps.cpp.
References mlir::AsmParser::emitError(), fillStructuredOpRegion(), mlir::AsmParser::getContext(), mlir::AsmParser::getCurrentLocation(), and mlir::success().
Referenced by parseNamedStructuredOp().
parseNamedStructuredOpResults()
static ParseResult parseNamedStructuredOpResults (OpAsmParser & parser, SmallVectorImpl< Type > & resultTypes) static
Definition at line 211 of file LinalgOps.cpp.
References mlir::failure(), mlir::AsmParser::parseOptionalArrowTypeList(), and mlir::success().
Referenced by buildGenericRegion(), and parseNamedStructuredOp().
printCommonStructuredOpParts()
static void printCommonStructuredOpParts (OpAsmPrinter & p, ValueRange inputs, ValueRange outputs) static
Definition at line 168 of file LinalgOps.cpp.
References mlir::ValueRange::getTypes().
Referenced by buildGenericRegion(), and printNamedStructuredOp().
printCommonStructuredOpPartsWithNewLine()
static void printCommonStructuredOpPartsWithNewLine (OpAsmPrinter & p, ValueRange inputs, ValueRange outputs) static
Definition at line 176 of file LinalgOps.cpp.
References mlir::ValueRange::getTypes(), and mlir::OpAsmPrinter::printNewline().
Referenced by buildIdentityRegion(), parseDstStyleOp(), and printDenseI64ArrayAttr().
printDenseI64ArrayAttr()
static void printDenseI64ArrayAttr (OpAsmPrinter & p, StringRef attributeName, ArrayRef< int64_t > attributeValue) static
Definition at line 1538 of file LinalgOps.cpp.
References mlir::Type::cast(), mlir::detail::enumerate(), mlir::Block::getArguments(), getElementType(), mlir::Block::getNumArguments(), getShape(), mlir::OpAsmPrinter::increaseIndent(), print(), printCommonStructuredOpPartsWithNewLine(), mlir::OpAsmPrinter::printNewline(), mlir::OpAsmPrinter::printOptionalAttrDict(), mlir::OpAsmPrinter::printRegion(), mlir::OpAsmPrinter::printRegionArgument(), mlir::success(), and mlir::verify().
Referenced by buildIdentityRegion().
printNamedStructuredOp()
static void printNamedStructuredOp (OpAsmPrinter & p, Operation * op, ValueRange inputs, ValueRange outputs) static
Definition at line 251 of file LinalgOps.cpp.
References mlir::presburger::abs(), mlir::RewritePatternSet::add(), mlir::bindSymbols(), mlir::presburger::ceil(), mlir::OpBuilder::create(), mlir::Attribute::dyn_cast(), mlir::Type::dyn_cast(), mlir::emitWarning(), mlir::failed(), mlir::failure(), mlir::presburger::floor(), mlir::AffineMap::get(), mlir::Operation::getAttrs(), mlir::Builder::getContext(), mlir::Value::getDefiningOp(), mlir::Type::getIntOrFloatBitWidth(), mlir::Value::getLoc(), mlir::Operation::getResultTypes(), mlir::Value::getType(), mlir::Builder::getUnknownLoc(), mlir::Type::isa(), mlir::Type::isIndex(), mlir::makeComposedFoldedAffineApply(), mlir::RewriterBase::notifyMatchFailure(), mlir::OpRewritePattern< SourceOp >::OpRewritePattern(), mlir::parseAttribute(), printCommonStructuredOpParts(), printNamedStructuredOpResults(), mlir::OpAsmPrinter::printOptionalAttrDict(), mlir::RewriterBase::replaceOpWithNewOp(), mlir::OpBuilder::setInsertionPointToEnd(), mlir::success(), and value.
printNamedStructuredOpResults()
static void printNamedStructuredOpResults (OpAsmPrinter & p, TypeRange resultTypes) static
Definition at line 244 of file LinalgOps.cpp.
References mlir::AsmPrinter::printOptionalArrowTypeList().
Referenced by buildGenericRegion(), and printNamedStructuredOp().
verifyYield()
static LogicalResult verifyYield (linalg::YieldOp op, LinalgOp linalgOp) static
Definition at line 1939 of file LinalgOps.cpp.
References mlir::IROperand< DerivedT, IRValueT >::get(), mlir::getElementTypeOrSelf(), mlir::Value::getType(), mlir::success(), and mlir::verify().