MLIR: lib/Conversion/LinalgToStandard/LinalgToStandard.cpp File Reference
LinalgToStandard.cpp File Reference
#include "mlir/Conversion/LinalgToStandard/LinalgToStandard.h"
#include "mlir/Dialect/Affine/IR/AffineOps.h"
#include "mlir/Dialect/Func/IR/FuncOps.h"
#include "mlir/Dialect/LLVMIR/LLVMDialect.h"
#include "mlir/Dialect/Linalg/IR/Linalg.h"
#include "mlir/Dialect/Linalg/Transforms/Transforms.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/Dialect/SCF/IR/SCF.h"
#include "mlir/Pass/Pass.h"
#include "mlir/Conversion/Passes.h.inc"
Namespaces
mlir
Include the generated interface declarations.
Macros
#define GEN_PASS_DEF_CONVERTLINALGTOSTANDARD
Functions
static MemRefType makeStridedLayoutDynamic (MemRefType type)
static SmallVector< Type, 4 > extractOperandTypes (Operation *op)
Helper function to extract the operand types that are passed to the generated CallOp.
static FlatSymbolRefAttr getLibraryCallSymbolRef (Operation *op, PatternRewriter &rewriter)
static SmallVector< Value, 4 > createTypeCanonicalizedMemRefOperands (OpBuilder &b, Location loc, ValueRange operands)
Macro Definition Documentation
GEN_PASS_DEF_CONVERTLINALGTOSTANDARD
#define GEN_PASS_DEF_CONVERTLINALGTOSTANDARD
Definition at line 21 of file LinalgToStandard.cpp.
Function Documentation
createTypeCanonicalizedMemRefOperands()
static SmallVector<Value, 4> createTypeCanonicalizedMemRefOperands (OpBuilder & b, Location loc, ValueRange operands) static
Definition at line 94 of file LinalgToStandard.cpp.
Referenced by mlir::linalg::LinalgOpToLibraryCallRewrite::matchAndRewrite().
extractOperandTypes()
static SmallVector<Type, 4> extractOperandTypes (Operation * op) static
Helper function to extract the operand types that are passed to the generated CallOp.
MemRefTypes have their layout canonicalized since the information is not used in signature generation. Note that static size information is not modified.
Definition at line 39 of file LinalgToStandard.cpp.
References mlir::Operation::getNumOperands(), mlir::Operation::getOperandTypes(), and makeStridedLayoutDynamic().
Referenced by getLibraryCallSymbolRef().
getLibraryCallSymbolRef()
static FlatSymbolRefAttr getLibraryCallSymbolRef (Operation * op, PatternRewriter & rewriter) static
Definition at line 56 of file LinalgToStandard.cpp.
References mlir::OpBuilder::create(), mlir::Operation::emitWarning(), extractOperandTypes(), mlir::FlatSymbolRefAttr::getAttr(), mlir::Builder::getContext(), mlir::Operation::getContext(), mlir::Builder::getFunctionType(), mlir::Operation::getLoc(), mlir::Operation::getNumResults(), mlir::Operation::getParentOfType(), mlir::FlatSymbolRefAttr::getValue(), mlir::Operation::setAttr(), and mlir::OpBuilder::setInsertionPoint().
Referenced by mlir::linalg::LinalgOpToLibraryCallRewrite::matchAndRewrite().
makeStridedLayoutDynamic()
static MemRefType makeStridedLayoutDynamic (MemRefType type) static
Definition at line 28 of file LinalgToStandard.cpp.
References mlir::MemRefType::Builder::setLayout().
Referenced by extractOperandTypes().