MLIR: lib/Analysis/Liveness.cpp File Reference
Liveness.cpp File Reference
#include "mlir/Analysis/Liveness.h"
#include "mlir/IR/Block.h"
#include "mlir/IR/Operation.h"
#include "mlir/IR/Region.h"
#include "mlir/IR/Value.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SetOperations.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/Support/raw_ostream.h"
Functions
static void buildBlockMapping (Operation *operation, DenseMap< Block *, BlockInfoBuilder > &builders)
Builds the internal liveness block mapping.
Function Documentation
buildBlockMapping()
static void buildBlockMapping (Operation * operation, DenseMap< Block *, BlockInfoBuilder > & builders) static
Builds the internal liveness block mapping.
Definition at line 125 of file Liveness.cpp.
References mlir::Block::pred_begin(), mlir::Block::pred_end(), mlir::PreOrder, and mlir::Operation::walk().
Referenced by mlir::Liveness::Liveness().