MLIR: lib/Dialect/LLVMIR/IR/LLVMTypes.cpp File Reference
LLVMTypes.cpp File Reference
#include "TypeDetail.h"
#include "mlir/Dialect/LLVMIR/LLVMDialect.h"
#include "mlir/Dialect/LLVMIR/LLVMTypes.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/DialectImplementation.h"
#include "mlir/IR/TypeSupport.h"
#include "llvm/ADT/ScopeExit.h"
#include "llvm/ADT/TypeSwitch.h"
#include "llvm/Support/TypeSize.h"
#include "mlir/Dialect/LLVMIR/LLVMTypeInterfaces.cpp.inc"
#include "mlir/Dialect/LLVMIR/LLVMTypes.cpp.inc"
Macros
#define GET_TYPEDEF_CLASSES
#define GET_TYPEDEF_LIST
Enumerations
enum StructDLEntryPos
Functions
static ParseResult parseFunctionTypes (AsmParser &p, FailureOr< SmallVector< Type >> &params, FailureOr< bool > &isVarArg)
static void printFunctionTypes (AsmPrinter &p, ArrayRef< Type > params, bool isVarArg)
static ParseResult parsePointer (AsmParser &p, FailureOr< Type > &elementType, FailureOr< unsigned > &addressSpace)
static void printPointer (AsmPrinter &p, Type elementType, unsigned addressSpace)
static LLVM_ATTRIBUTE_UNUSED OptionalParseResult generatedTypeParser (AsmParser &parser, StringRef *mnemonic, Type &value)
These are unused for now.
static LLVM_ATTRIBUTE_UNUSED LogicalResult generatedTypePrinter (Type def, AsmPrinter &printer)
static Optional< unsigned > getPointerDataLayoutEntry (DataLayoutEntryListRef params, LLVMPointerType type, PtrDLEntryPos pos)
Returns the part of the data layout entry that corresponds to pos for the given type by interpreting the list of entries params.
static Optional< unsigned > getStructDataLayoutEntry (DataLayoutEntryListRef params, LLVMStructType type, StructDLEntryPos pos)
static unsigned calculateStructAlignment (const DataLayout &dataLayout, DataLayoutEntryListRef params, LLVMStructType type, StructDLEntryPos pos)
static unsigned extractStructSpecValue (Attribute attr, StructDLEntryPos pos)
template<typename VecTy >
static LogicalResult verifyVectorConstructionInvariants (function_ref< InFlightDiagnostic()> emitError, Type elementType, unsigned numElements)
Verifies that the type about to be constructed is well-formed.
static bool isCompatibleImpl (Type type, DenseSet< Type > &compatibleTypes)
Variables
constexpr static const unsigned kBitsInByte = 8
constexpr static const unsigned kDefaultPointerSizeBits = 64
constexpr static const unsigned kDefaultPointerAlignment = 8
Macro Definition Documentation
GET_TYPEDEF_CLASSES
#define GET_TYPEDEF_CLASSES
Definition at line 127 of file LLVMTypes.cpp.
GET_TYPEDEF_LIST
#define GET_TYPEDEF_LIST
Enumeration Type Documentation
StructDLEntryPos
enum StructDLEntryPos strong
Definition at line 574 of file LLVMTypes.cpp.
Function Documentation
calculateStructAlignment()
static unsigned calculateStructAlignment (const DataLayout & dataLayout, DataLayoutEntryListRef params, LLVMStructType type, StructDLEntryPos pos) static
Definition at line 596 of file LLVMTypes.cpp.
References mlir::LLVM::Abi, mlir::LLVM::LLVMStructType::getBody(), getStructDataLayoutEntry(), mlir::DataLayout::getTypeABIAlignment(), mlir::LLVM::LLVMStructType::isPacked(), kBitsInByte, and max().
Referenced by mlir::LLVM::LLVMStructType::getABIAlignment(), and mlir::LLVM::LLVMStructType::getPreferredAlignment().
extractStructSpecValue()
static unsigned extractStructSpecValue (Attribute attr, StructDLEntryPos pos) static
Definition at line 634 of file LLVMTypes.cpp.
References mlir::Attribute::cast().
Referenced by mlir::LLVM::LLVMStructType::areCompatible(), and mlir::LLVM::LLVMStructType::verifyEntries().
generatedTypeParser()
static LLVM_ATTRIBUTE_UNUSED OptionalParseResult generatedTypeParser (AsmParser & parser, StringRef * mnemonic, Type & value) static
These are unused for now.
TODO: Move over to these once more types have been migrated to TypeDef.
Referenced by parsePDLType(), and printPointer().
generatedTypePrinter()
static LLVM_ATTRIBUTE_UNUSED LogicalResult generatedTypePrinter (Type def, AsmPrinter & printer) static
Referenced by mlir::pdl::PDLType::classof(), and printPointer().
getPointerDataLayoutEntry()
static Optional<unsigned> getPointerDataLayoutEntry (DataLayoutEntryListRef params, LLVMPointerType type, PtrDLEntryPos pos) static
Returns the part of the data layout entry that corresponds to pos for the given type by interpreting the list of entries params.
For the pointer type in the default address space, returns the default value if the entries do not provide a custom one, for other address spaces returns None.
Definition at line 313 of file LLVMTypes.cpp.
References mlir::LLVM::Abi, mlir::Attribute::cast(), mlir::Type::cast(), mlir::Type::dyn_cast(), mlir::emitError(), mlir::LLVM::extractPointerSpecValue(), getElementType(), mlir::DataLayout::getTypeABIAlignment(), mlir::DataLayout::getTypePreferredAlignment(), mlir::DataLayout::getTypeSizeInBits(), kBitsInByte, kDefaultPointerAlignment, kDefaultPointerSizeBits, mlir::LLVM::Preferred, mlir::LLVM::Size, and mlir::success().
getStructDataLayoutEntry()
static Optional<unsigned> getStructDataLayoutEntry (DataLayoutEntryListRef params, LLVMStructType type, StructDLEntryPos pos) static
Definition at line 578 of file LLVMTypes.cpp.
References mlir::LLVM::Abi, and mlir::LLVM::Preferred.
Referenced by calculateStructAlignment().
isCompatibleImpl()
static bool isCompatibleImpl (Type type, DenseSet< Type > & compatibleTypes) static
Definition at line 847 of file LLVMTypes.cpp.
Referenced by mlir::LLVM::isCompatibleType().
parseFunctionTypes()
static ParseResult parseFunctionTypes (AsmParser & p, FailureOr< SmallVector< Type >> & params, FailureOr< bool > & isVarArg) static
Definition at line 35 of file LLVMTypes.cpp.
References mlir::failure(), mlir::AsmParser::parseOptionalComma(), mlir::AsmParser::parseOptionalEllipsis(), mlir::AsmParser::parseOptionalRParen(), mlir::LLVM::parsePrettyLLVMType(), mlir::AsmParser::parseRParen(), mlir::succeeded(), and mlir::success().
parsePointer()
static ParseResult parsePointer (AsmParser & p, FailureOr< Type > & elementType, FailureOr< unsigned > & addressSpace) static
Definition at line 83 of file LLVMTypes.cpp.
References mlir::failed(), mlir::failure(), mlir::OptionalParseResult::has_value(), mlir::AsmParser::parseInteger(), mlir::AsmParser::parseOptionalComma(), mlir::AsmParser::parseOptionalInteger(), mlir::LLVM::parsePrettyLLVMType(), mlir::succeeded(), mlir::success(), and mlir::OptionalParseResult::value().
printFunctionTypes()
static void printFunctionTypes (AsmPrinter & p, ArrayRef< Type > params, bool isVarArg) static
Definition at line 67 of file LLVMTypes.cpp.
References mlir::LLVM::printPrettyLLVMType().
printPointer()
static void printPointer (AsmPrinter & p, Type elementType, unsigned addressSpace) static
Definition at line 103 of file LLVMTypes.cpp.
References generatedTypeParser(), generatedTypePrinter(), mlir::LLVM::printPrettyLLVMType(), and value.
verifyVectorConstructionInvariants()
template<typename VecTy > static LogicalResult verifyVectorConstructionInvariants (function_ref< InFlightDiagnostic()> emitError, Type elementType, unsigned numElements) static
Verifies that the type about to be constructed is well-formed.
Definition at line 716 of file LLVMTypes.cpp.
References mlir::Type::dyn_cast(), mlir::emitError(), mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >::get(), mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >::getChecked(), mlir::Type::getContext(), getElementType(), getNumElements(), mlir::Type::isa(), mlir::LLVM::isCompatibleFloatingPointType(), mlir::success(), and mlir::verify().
Variable Documentation
kBitsInByte
constexpr static const unsigned kBitsInByte = 8 static
Definition at line 29 of file LLVMTypes.cpp.
Referenced by calculateStructAlignment(), getPointerDataLayoutEntry(), and mlir::LLVM::LLVMStructType::getTypeSizeInBits().
kDefaultPointerAlignment
constexpr static const unsigned kDefaultPointerAlignment = 8 static
Definition at line 297 of file LLVMTypes.cpp.
Referenced by getPointerDataLayoutEntry().
kDefaultPointerSizeBits
constexpr static const unsigned kDefaultPointerSizeBits = 64 static
Definition at line 296 of file LLVMTypes.cpp.
Referenced by getPointerDataLayoutEntry().