MLIR: lib/Target/LLVMIR/Dialect/LLVMIR/LLVMToLLVMIRTranslation.cpp File Reference
LLVMToLLVMIRTranslation.cpp File Reference
#include "mlir/Target/LLVMIR/Dialect/LLVMIR/LLVMToLLVMIRTranslation.h"
#include "mlir/Dialect/LLVMIR/LLVMDialect.h"
#include "mlir/IR/Operation.h"
#include "mlir/Support/LLVM.h"
#include "mlir/Target/LLVMIR/ModuleTranslation.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/InlineAsm.h"
#include "llvm/IR/MDBuilder.h"
#include "llvm/IR/MatrixBuilder.h"
#include "llvm/IR/Operator.h"
#include "mlir/Dialect/LLVMIR/LLVMConversionEnumsToLLVM.inc"
#include "mlir/Dialect/LLVMIR/LLVMConversions.inc"
#include "mlir/Dialect/LLVMIR/LLVMIntrinsicConversions.inc"
Functions
static llvm::CmpInst::Predicate getLLVMCmpPredicate (ICmpPredicate p)
Convert MLIR integer comparison predicate to LLVM IR comparison predicate.
static llvm::CmpInst::Predicate getLLVMCmpPredicate (FCmpPredicate p)
static llvm::AtomicRMWInst::BinOp getLLVMAtomicBinOp (AtomicBinOp op)
static llvm::AtomicOrdering getLLVMAtomicOrdering (AtomicOrdering ordering)
static llvm::FastMathFlags getFastmathFlags (FastmathFlagsInterface &op)
static llvm::MDNode * getLoopOptionMetadata (llvm::LLVMContext &ctx, LoopOptionCase option, int64_t value)
Returns an LLVM metadata node corresponding to a loop option.
static void setLoopMetadata (Operation &opInst, llvm::Instruction &llvmInst, llvm::IRBuilderBase &builder, LLVM::ModuleTranslation &moduleTranslation)
static SmallVector< unsigned > extractPosition (ArrayRef< int64_t > indices)
Convert the value of a DenseI64ArrayAttr to a vector of unsigned indices.
static FailureOr< llvm::Function * > getOverloadedDeclaration (CallIntrinsicOp &op, llvm::Intrinsic::ID id, llvm::Module *module, LLVM::ModuleTranslation &moduleTranslation)
Get the declaration of an overloaded llvm intrinsic.
static LogicalResult convertCallLLVMIntrinsicOp (CallIntrinsicOp &op, llvm::IRBuilderBase &builder, LLVM::ModuleTranslation &moduleTranslation)
Builder for LLVM_CallIntrinsicOp.
static LogicalResult convertOperationImpl (Operation &opInst, llvm::IRBuilderBase &builder, LLVM::ModuleTranslation &moduleTranslation)
Function Documentation
convertCallLLVMIntrinsicOp()
static LogicalResult convertCallLLVMIntrinsicOp (CallIntrinsicOp & op, llvm::IRBuilderBase & builder, LLVM::ModuleTranslation & moduleTranslation) static
Builder for LLVM_CallIntrinsicOp.
Definition at line 298 of file LLVMToLLVMIRTranslation.cpp.
References mlir::failed(), mlir::failure(), getOverloadedDeclaration(), mlir::LLVM::ModuleTranslation::lookupValues(), mlir::LLVM::ModuleTranslation::mapValue(), and mlir::success().
convertOperationImpl()
static LogicalResult convertOperationImpl (Operation & opInst, llvm::IRBuilderBase & builder, LLVM::ModuleTranslation & moduleTranslation) static
Definition at line 326 of file LLVMToLLVMIRTranslation.cpp.
References mlir::Attribute::cast(), mlir::LLVM::ModuleTranslation::convertType(), mlir::detail::enumerate(), mlir::failure(), mlir::Operation::getAttrOfType(), mlir::LLVM::ModuleTranslation::getContext(), getFastmathFlags(), mlir::LLVM::ModuleTranslation::getLLVMContext(), mlir::Operation::getNumResults(), mlir::Operation::getResult(), mlir::LLVMTranslationDialectInterface::LLVMTranslationDialectInterface(), mlir::LLVM::ModuleTranslation::lookupBlock(), mlir::LLVM::ModuleTranslation::lookupFunction(), mlir::LLVM::ModuleTranslation::lookupGlobal(), mlir::LLVM::ModuleTranslation::lookupValue(), mlir::LLVM::ModuleTranslation::lookupValues(), mlir::LLVM::ModuleTranslation::mapBranch(), mlir::LLVM::ModuleTranslation::mapValue(), setLoopMetadata(), mlir::success(), and mlir::LLVM::ModuleTranslation::symbolTable().
extractPosition()
static SmallVector<unsigned> extractPosition (ArrayRef< int64_t > indices) static
Convert the value of a DenseI64ArrayAttr to a vector of unsigned indices.
Definition at line 255 of file LLVMToLLVMIRTranslation.cpp.
Referenced by foldExtractOpFromExtractChain().
getFastmathFlags()
static llvm::FastMathFlags getFastmathFlags (FastmathFlagsInterface & op) static
Definition at line 148 of file LLVMToLLVMIRTranslation.cpp.
References contract().
Referenced by convertOperationImpl().
getLLVMAtomicBinOp()
static llvm::AtomicRMWInst::BinOp getLLVMAtomicBinOp (AtomicBinOp op) static
Definition at line 96 of file LLVMToLLVMIRTranslation.cpp.
References max(), and min().
getLLVMAtomicOrdering()
static llvm::AtomicOrdering getLLVMAtomicOrdering (AtomicOrdering ordering) static
Definition at line 128 of file LLVMToLLVMIRTranslation.cpp.
getLLVMCmpPredicate() [1/2]
static llvm::CmpInst::Predicate getLLVMCmpPredicate (ICmpPredicate p) static
Convert MLIR integer comparison predicate to LLVM IR comparison predicate.
Definition at line 32 of file LLVMToLLVMIRTranslation.cpp.
getLLVMCmpPredicate() [2/2]
static llvm::CmpInst::Predicate getLLVMCmpPredicate (FCmpPredicate p) static
Definition at line 58 of file LLVMToLLVMIRTranslation.cpp.
getLoopOptionMetadata()
static llvm::MDNode* getLoopOptionMetadata (llvm::LLVMContext & ctx, LoopOptionCase option, int64_t value) static
Returns an LLVM metadata node corresponding to a loop option.
This metadata is attached to an llvm.loop node.
Definition at line 172 of file LLVMToLLVMIRTranslation.cpp.
References mlir::Constant.
Referenced by setLoopMetadata().
getOverloadedDeclaration()
static FailureOr<llvm::Function *> getOverloadedDeclaration (CallIntrinsicOp & op, llvm::Intrinsic::ID id, llvm::Module * module, LLVM::ModuleTranslation & moduleTranslation) static
Get the declaration of an overloaded llvm intrinsic.
First we get the overloaded argument types and/or result type from the CallIntrinsicOp, and then use those to get the correct declaration of the overloaded intrinsic.
Definition at line 265 of file LLVMToLLVMIRTranslation.cpp.
References mlir::LLVM::ModuleTranslation::convertType().
Referenced by convertCallLLVMIntrinsicOp().
setLoopMetadata()
static void setLoopMetadata (Operation & opInst, llvm::Instruction & llvmInst, llvm::IRBuilderBase & builder, LLVM::ModuleTranslation & moduleTranslation) static
Definition at line 205 of file LLVMToLLVMIRTranslation.cpp.
References mlir::LLVM::ModuleTranslation::getAccessGroup(), mlir::Operation::getAttr(), getLoopOptionMetadata(), mlir::LLVM::ModuleTranslation::lookupLoopOptionsMetadata(), and mlir::LLVM::ModuleTranslation::mapLoopOptionsMetadata().
Referenced by convertOperationImpl().