MLIR: lib/Conversion/GPUToROCDL/LowerGpuOpsToROCDLOps.cpp File Reference
LowerGpuOpsToROCDLOps.cpp File Reference
#include "mlir/Conversion/ControlFlowToLLVM/ControlFlowToLLVM.h"
#include "mlir/Conversion/GPUToROCDL/GPUToROCDLPass.h"
#include "mlir/Conversion/AMDGPUToROCDL/AMDGPUToROCDL.h"
#include "mlir/Conversion/ArithToLLVM/ArithToLLVM.h"
#include "mlir/Conversion/FuncToLLVM/ConvertFuncToLLVM.h"
#include "mlir/Conversion/LLVMCommon/ConversionTarget.h"
#include "mlir/Conversion/LLVMCommon/LoweringOptions.h"
#include "mlir/Conversion/LLVMCommon/Pattern.h"
#include "mlir/Conversion/LLVMCommon/TypeConverter.h"
#include "mlir/Conversion/MemRefToLLVM/MemRefToLLVM.h"
#include "mlir/Conversion/VectorToLLVM/ConvertVectorToLLVM.h"
#include "mlir/Dialect/Func/IR/FuncOps.h"
#include "mlir/Dialect/GPU/IR/GPUDialect.h"
#include "mlir/Dialect/GPU/Transforms/Passes.h"
#include "mlir/Dialect/LLVMIR/ROCDLDialect.h"
#include "mlir/Dialect/Math/IR/Math.h"
#include "mlir/Dialect/Vector/IR/VectorOps.h"
#include "mlir/Pass/Pass.h"
#include "mlir/Transforms/DialectConversion.h"
#include "mlir/Transforms/GreedyPatternRewriteDriver.h"
#include "llvm/Support/FormatVariadic.h"
#include "../GPUCommon/GPUOpsLowering.h"
#include "../GPUCommon/IndexIntrinsicsOpLowering.h"
#include "../GPUCommon/OpToFuncCallLowering.h"
#include "mlir/Conversion/Passes.h.inc"
#include "GPUToROCDL.cpp.inc"
Namespaces
mlir
Include the generated interface declarations.
Macros
#define GEN_PASS_DEF_CONVERTGPUOPSTOROCDLOPS
Functions
static bool canBeCalledWithBarePointers (gpu::GPUFuncOp func)
Returns true if the given gpu.func can be safely called using the bare pointer calling convention.
template<typename OpTy >
static void populateOpPatterns (LLVMTypeConverter &converter, RewritePatternSet &patterns, StringRef f32Func, StringRef f64Func)
Macro Definition Documentation
GEN_PASS_DEF_CONVERTGPUOPSTOROCDLOPS
#define GEN_PASS_DEF_CONVERTGPUOPSTOROCDLOPS
Definition at line 42 of file LowerGpuOpsToROCDLOps.cpp.
Function Documentation
canBeCalledWithBarePointers()
static bool canBeCalledWithBarePointers (gpu::GPUFuncOp func) static
Returns true if the given gpu.func can be safely called using the bare pointer calling convention.
Definition at line 50 of file LowerGpuOpsToROCDLOps.cpp.
References mlir::WalkResult::advance(), mlir::applyPartialConversion(), mlir::applyPatternsAndFoldGreedily(), mlir::LLVMTypeConverter::canConvertToBarePtr(), mlir::configureGpuToROCDLConversionLegality(), mlir::emitError(), mlir::failed(), mlir::WalkResult::interrupt(), mlir::kDeriveIndexBitwidthFromDataLayout, options, mlir::amdgpu::Chipset::parse(), mlir::populateAMDGPUToROCDLConversionPatterns(), mlir::arith::populateArithToLLVMConversionPatterns(), mlir::cf::populateControlFlowToLLVMConversionPatterns(), mlir::populateFuncToLLVMConversionPatterns(), mlir::populateGpuRewritePatterns(), mlir::populateGpuToROCDLConversionPatterns(), mlir::populateMemRefToLLVMConversionPatterns(), mlir::populateVectorToLLVMConversionPatterns(), and mlir::WalkResult::wasInterrupted().
populateOpPatterns()
template<typename OpTy > static void populateOpPatterns (LLVMTypeConverter & converter, RewritePatternSet & patterns, StringRef f32Func, StringRef f64Func) static
Definition at line 161 of file LowerGpuOpsToROCDLOps.cpp.
References mlir::RewritePatternSet::add().