MLIR: lib/Dialect/SPIRV/Transforms/LowerABIAttributesPass.cpp File Reference
LowerABIAttributesPass.cpp File Reference
#include "mlir/Dialect/SPIRV/Transforms/Passes.h"
#include "mlir/Dialect/SPIRV/IR/SPIRVDialect.h"
#include "mlir/Dialect/SPIRV/IR/SPIRVOps.h"
#include "mlir/Dialect/SPIRV/Transforms/SPIRVConversion.h"
#include "mlir/Dialect/SPIRV/Utils/LayoutUtils.h"
#include "mlir/Transforms/DialectConversion.h"
#include "llvm/ADT/SetVector.h"
#include "mlir/Dialect/SPIRV/Transforms/Passes.h.inc"
Namespaces
mlir
Include the generated interface declarations.
mlir::spirv
Macros
#define GEN_PASS_DEF_SPIRVLOWERABIATTRIBUTES
Functions
static spirv::GlobalVariableOp createGlobalVarForEntryPointArgument (OpBuilder &builder, spirv::FuncOp funcOp, unsigned argIndex, spirv::InterfaceVarABIAttr abiInfo)
Creates a global variable for an argument based on the ABI info.
static LogicalResult getInterfaceVariables (spirv::FuncOp funcOp, SmallVectorImpl< Attribute > &interfaceVars)
Gets the global variables that need to be specified as interface variable with an spirv.EntryPointOp.
static LogicalResult lowerEntryPointABIAttr (spirv::FuncOp funcOp, OpBuilder &builder)
Lowers the entry point attribute.
Macro Definition Documentation
GEN_PASS_DEF_SPIRVLOWERABIATTRIBUTES
#define GEN_PASS_DEF_SPIRVLOWERABIATTRIBUTES
Definition at line 25 of file LowerABIAttributesPass.cpp.
Function Documentation
createGlobalVarForEntryPointArgument()
static spirv::GlobalVariableOp createGlobalVarForEntryPointArgument (OpBuilder & builder, spirv::FuncOp funcOp, unsigned argIndex, spirv::InterfaceVarABIAttr abiInfo) static
Creates a global variable for an argument based on the ABI info.
Definition at line 34 of file LowerABIAttributesPass.cpp.
References mlir::Type::cast(), mlir::OpBuilder::create(), mlir::VulkanLayoutUtils::decorateType(), mlir::spirv::PointerType::get(), mlir::spirv::StructType::get(), mlir::spirv::InterfaceVarABIAttr::getBinding(), mlir::spirv::InterfaceVarABIAttr::getDescriptorSet(), mlir::spirv::PointerType::getPointeeType(), mlir::spirv::InterfaceVarABIAttr::getStorageClass(), mlir::spirv::SPIRVType::isScalarOrVector(), and mlir::OpBuilder::setInsertionPoint().
Referenced by lowerEntryPointABIAttr().
getInterfaceVariables()
static LogicalResult getInterfaceVariables (spirv::FuncOp funcOp, SmallVectorImpl< Attribute > & interfaceVars) static
Gets the global variables that need to be specified as interface variable with an spirv.EntryPointOp.
Traverses the body of a entry function to do so.
Definition at line 78 of file LowerABIAttributesPass.cpp.
References mlir::failure(), and mlir::success().
Referenced by lowerEntryPointABIAttr().
lowerEntryPointABIAttr()
static LogicalResult lowerEntryPointABIAttr (spirv::FuncOp funcOp, OpBuilder & builder) static
Lowers the entry point attribute.
Definition at line 114 of file LowerABIAttributesPass.cpp.
References mlir::RewritePatternSet::add(), mlir::TypeConverter::addSourceMaterialization(), mlir::applyPartialConversion(), mlir::ConversionPatternRewriter::convertRegionTypes(), mlir::OpBuilder::create(), createGlobalVarForEntryPointArgument(), mlir::detail::enumerate(), mlir::failed(), mlir::failure(), mlir::Operation::getDialect(), mlir::spirv::getEntryPointABIAttrName(), mlir::spirv::getExecutionModel(), mlir::Builder::getFunctionType(), mlir::spirv::getInterfaceVarABIAttrName(), getInterfaceVariables(), mlir::Dialect::getNamespace(), mlir::ValueRange::getType(), getZero(), mlir::spirv::lookupTargetEnv(), mlir::Operation::removeAttr(), mlir::OpBuilder::setInsertionPointToEnd(), mlir::OpBuilder::setInsertionPointToStart(), mlir::success(), and mlir::RewriterBase::updateRootInPlace().