MLIR: lib/Conversion/MathToSPIRV/MathToSPIRV.cpp File Reference
MathToSPIRV.cpp File Reference
#include "../SPIRVCommon/Pattern.h"
#include "mlir/Dialect/Math/IR/Math.h"
#include "mlir/Dialect/SPIRV/IR/SPIRVDialect.h"
#include "mlir/Dialect/SPIRV/IR/SPIRVOps.h"
#include "mlir/Dialect/SPIRV/Transforms/SPIRVConversion.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/TypeUtilities.h"
#include "mlir/Transforms/DialectConversion.h"
#include "llvm/Support/Debug.h"
Namespaces
mlir
Include the generated interface declarations.
Macros
#define DEBUG_TYPE "math-to-spirv-pattern"
Functions
static Value getScalarOrVectorI32Constant (Type type, int value, OpBuilder &builder, Location loc)
Creates a 32-bit scalar/vector integer constant.
void mlir::populateMathToSPIRVPatterns (SPIRVTypeConverter &typeConverter, RewritePatternSet &patterns)
Appends to a pattern list additional patterns for translating Math ops to SPIR-V ops.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "math-to-spirv-pattern"
Definition at line 23 of file MathToSPIRV.cpp.
Function Documentation
getScalarOrVectorI32Constant()
static Value getScalarOrVectorI32Constant (Type type, int value, OpBuilder & builder, Location loc) static
Creates a 32-bit scalar/vector integer constant.
Returns nullptr if the given type is not a 32-bit scalar/vector type.
Definition at line 33 of file MathToSPIRV.cpp.
References mlir::presburger::abs(), mlir::Type::cast(), mlir::OpBuilder::create(), mlir::Type::dyn_cast(), mlir::failure(), mlir::presburger::floor(), mlir::DenseElementsAttr::get(), mlir::getElementTypeOrSelf(), mlir::Builder::getFloatAttr(), mlir::Builder::getI32IntegerAttr(), mlir::Builder::getI32VectorAttr(), mlir::Builder::getIntegerAttr(), mlir::Builder::getIntegerType(), mlir::FloatType::getWidth(), getZero(), mlir::Type::isInteger(), mlir::OpConversionPattern< SourceOp >::OpConversionPattern(), mlir::RewriterBase::replaceOpWithNewOp(), mlir::success(), and value.