MLIR: lib/Tools/mlir-opt/MlirOptMain.cpp File Reference
MlirOptMain.cpp File Reference
#include "mlir/Tools/mlir-opt/MlirOptMain.h"
#include "mlir/Bytecode/BytecodeWriter.h"
#include "mlir/IR/AsmState.h"
#include "mlir/IR/Attributes.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/Diagnostics.h"
#include "mlir/IR/Dialect.h"
#include "mlir/IR/Location.h"
#include "mlir/IR/MLIRContext.h"
#include "mlir/Parser/Parser.h"
#include "mlir/Pass/Pass.h"
#include "mlir/Pass/PassManager.h"
#include "mlir/Support/DebugCounter.h"
#include "mlir/Support/FileUtilities.h"
#include "mlir/Support/Timing.h"
#include "mlir/Support/ToolUtilities.h"
#include "mlir/Tools/ParseUtilities.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/FileUtilities.h"
#include "llvm/Support/InitLLVM.h"
#include "llvm/Support/Regex.h"
#include "llvm/Support/SourceMgr.h"
#include "llvm/Support/StringSaver.h"
#include "llvm/Support/ThreadPool.h"
#include "llvm/Support/ToolOutputFile.h"
Functions
static LogicalResult performActions (raw_ostream &os, bool verifyDiagnostics, bool verifyPasses, SourceMgr &sourceMgr, MLIRContext *context, PassPipelineFn passManagerSetupFn, bool emitBytecode, bool implicitModule)
Perform the actions on the input file indicated by the command line flags within the specified context.
static LogicalResult processBuffer (raw_ostream &os, std::unique_ptr< MemoryBuffer > ownedBuffer, bool verifyDiagnostics, bool verifyPasses, bool allowUnregisteredDialects, bool preloadDialectsInContext, bool emitBytecode, bool implicitModule, PassPipelineFn passManagerSetupFn, DialectRegistry &registry, llvm::ThreadPool *threadPool)
Parses the memory buffer.
Function Documentation
performActions()
static LogicalResult performActions (raw_ostream & os, bool verifyDiagnostics, bool verifyPasses, SourceMgr & sourceMgr, MLIRContext * context, PassPipelineFn passManagerSetupFn, bool emitBytecode, bool implicitModule) static
Perform the actions on the input file indicated by the command line flags within the specified context.
This typically parses the main source file, runs zero or more optimization passes, then prints the output.
Definition at line 49 of file MlirOptMain.cpp.
References mlir::PassReproducerOptions::apply(), mlir::applyDefaultTimingManagerCLOptions(), mlir::applyPassManagerCLOptions(), mlir::PassReproducerOptions::attachResourceParser(), mlir::MLIRContext::disableMultithreading(), mlir::MLIRContext::enableMultithreading(), mlir::PassManager::enableVerifier(), mlir::failed(), mlir::failure(), mlir::OwningOpRef< OpTy >::get(), mlir::Operation::getName(), mlir::TimingManager::getRootScope(), mlir::OperationName::getStringRef(), mlir::OpPassManager::Implicit, mlir::MLIRContext::isMultithreadingEnabled(), mlir::TimingScope::nest(), mlir::parseSourceFileForTool(), mlir::Operation::print(), mlir::TimingScope::stop(), mlir::success(), and mlir::writeBytecodeToFile().
Referenced by processBuffer().
processBuffer()
static LogicalResult processBuffer (raw_ostream & os, std::unique_ptr< MemoryBuffer > ownedBuffer, bool verifyDiagnostics, bool verifyPasses, bool allowUnregisteredDialects, bool preloadDialectsInContext, bool emitBytecode, bool implicitModule, PassPipelineFn passManagerSetupFn, DialectRegistry & registry, llvm::ThreadPool * threadPool) static
Parses the memory buffer.
If successfully, run a series of passes against it and print the result.
Definition at line 111 of file MlirOptMain.cpp.
References mlir::PassPipelineCLParser::addToPipeline(), mlir::MLIRContext::allowUnregisteredDialects(), mlir::MLIRContext::DISABLED, mlir::emitError(), mlir::failed(), mlir::failure(), mlir::MLIRContext::getDebugActionManager(), mlir::MLIRContext::getThreadPool(), mlir::MLIRContext::isMultithreadingEnabled(), mlir::MLIRContext::loadAllAvailableDialects(), mlir::MlirOptMain(), performActions(), mlir::MLIRContext::printOpOnDiagnostic(), mlir::DebugActionManager::registerActionHandler(), mlir::MLIRContext::setThreadPool(), mlir::splitAndProcessBuffer(), mlir::success(), and mlir::SourceMgrDiagnosticVerifierHandler::verify().