MLIR: lib/Tools/mlir-reduce/MlirReduceMain.cpp File Reference
MlirReduceMain.cpp File Reference
#include "mlir/Tools/mlir-reduce/MlirReduceMain.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/Parser/Parser.h"
#include "mlir/Pass/Pass.h"
#include "mlir/Pass/PassManager.h"
#include "mlir/Reducer/Passes.h"
#include "mlir/Rewrite/FrozenRewritePatternSet.h"
#include "mlir/Support/FileUtilities.h"
#include "mlir/Support/LogicalResult.h"
#include "mlir/Tools/ParseUtilities.h"
#include "llvm/Support/InitLLVM.h"
#include "llvm/Support/SourceMgr.h"
#include "llvm/Support/ToolOutputFile.h"
Functions
OwningOpRef< Operation * > loadModule (MLIRContext &context, StringRef inputFilename, bool insertImplictModule)
Function Documentation
loadModule()
OwningOpRef<Operation *> loadModule (MLIRContext & context, StringRef inputFilename, bool insertImplictModule)
Definition at line 33 of file MlirReduceMain.cpp.
References mlir::openInputFile(), and mlir::parseSourceFileForTool().
Referenced by mlir::mlirReduceMain().