MLIR: mlir::builtin_dialect_detail Namespace Reference
mlir::builtin_dialect_detail Namespace Reference
Functions
void addBytecodeInterface (BuiltinDialect *dialect)
Add the interfaces necessary for encoding the builtin dialect components in bytecode.
Function Documentation
addBytecodeInterface()
void mlir::builtin_dialect_detail::addBytecodeInterface (BuiltinDialect * dialect)
Add the interfaces necessary for encoding the builtin dialect components in bytecode.
Definition at line 387 of file BuiltinDialectBytecode.cpp.
References mlir::Type::dyn_cast(), mlir::DialectBytecodeReader::emitError(), mlir::failed(), mlir::failure(), mlir::FloatType::getFloatSemantics(), mlir::Type::isa(), mlir::DialectBytecodeReader::readAPFloatWithKnownSemantics(), mlir::DialectBytecodeReader::readAPIntWithKnownWidth(), mlir::DialectBytecodeReader::readAttribute(), mlir::DialectBytecodeReader::readAttributes(), mlir::DialectBytecodeReader::readBlob(), mlir::DialectBytecodeReader::readList(), mlir::DialectBytecodeReader::readResourceHandle(), mlir::DialectBytecodeReader::readSignedVarInts(), mlir::DialectBytecodeReader::readString(), mlir::DialectBytecodeReader::readType(), mlir::DialectBytecodeReader::readTypes(), mlir::DialectBytecodeReader::readVarInt(), mlir::success(), value, mlir::DialectBytecodeWriter::writeAPFloatWithKnownSemantics(), mlir::DialectBytecodeWriter::writeAPIntWithKnownWidth(), mlir::DialectBytecodeWriter::writeAttribute(), mlir::DialectBytecodeWriter::writeAttributes(), mlir::DialectBytecodeWriter::writeList(), mlir::DialectBytecodeWriter::writeOwnedBlob(), mlir::DialectBytecodeWriter::writeOwnedString(), mlir::DialectBytecodeWriter::writeResourceHandle(), mlir::DialectBytecodeWriter::writeSignedVarInts(), mlir::DialectBytecodeWriter::writeType(), mlir::DialectBytecodeWriter::writeTypes(), and mlir::DialectBytecodeWriter::writeVarInt().