MLIR: lib/Dialect/Linalg/Transforms/NamedOpConversions.cpp File Reference
NamedOpConversions.cpp File Reference
#include "mlir/Dialect/Linalg/Passes.h"
#include "mlir/Dialect/Linalg/IR/Linalg.h"
#include "mlir/Dialect/Linalg/Transforms/Transforms.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/Transforms/GreedyPatternRewriteDriver.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/TypeSwitch.h"
#include "mlir/Dialect/Linalg/Passes.h.inc"
Namespaces
mlir
Include the generated interface declarations.
Macros
#define GEN_PASS_DEF_LINALGNAMEDOPCONVERSION
Functions
static llvm::SmallVector< int64_t > getIndicesVector (int start, int end)
static LogicalResult matchAndReplaceDepthwiseConv (Operation *operation, Value input, Value kernel, Value iZp, Value kZp, Value init, Attribute stride, Attribute dilation, PatternRewriter &rewriter)
Macro Definition Documentation
GEN_PASS_DEF_LINALGNAMEDOPCONVERSION
#define GEN_PASS_DEF_LINALGNAMEDOPCONVERSION
Definition at line 24 of file NamedOpConversions.cpp.
Function Documentation
getIndicesVector()
static llvm::SmallVector<int64_t> getIndicesVector (int start, int end) static
Definition at line 31 of file NamedOpConversions.cpp.
Referenced by matchAndReplaceDepthwiseConv().
matchAndReplaceDepthwiseConv()
static LogicalResult matchAndReplaceDepthwiseConv (Operation * operation, Value input, Value kernel, Value iZp, Value kZp, Value init, Attribute stride, Attribute dilation, PatternRewriter & rewriter) static
Definition at line 36 of file NamedOpConversions.cpp.
References mlir::applyPatternsAndFoldGreedily(), mlir::OpBuilder::create(), mlir::Type::dyn_cast(), mlir::failed(), mlir::failure(), mlir::Operation::getContext(), getIndicesVector(), mlir::Operation::getLoc(), mlir::linalg::getPrunedAttributeList(), mlir::Operation::getResult(), mlir::Value::getType(), mlir::linalg::populateLinalgNamedOpConversionPatterns(), mlir::RewriterBase::replaceOpWithNewOp(), mlir::Operation::setAttr(), and mlir::success().