MLIR: mlir::transform::gpu Namespace Reference
mlir::transform::gpu Namespace Reference
Functions
DiagnosedSilenceableFailure mapNestedForeachToThreadsImpl (RewriterBase &rewriter, Operation *target, const SmallVectorImpl< int64_t > &blockDim, bool syncAfterDistribute, llvm::Optional< TransformOpInterface > transformOp)
Searches scf.foreach_thread ops nested under target and maps each such op to GPU threads.
DiagnosedSilenceableFailure mapForeachToBlocksImpl (RewriterBase &rewriter, scf::ForeachThreadOp foreachThreadOp, function_ref< void(RewriterBase &, scf::ForeachThreadOp, SmallVectorImpl< Value > &)> blockIdGenerator, SmallVectorImpl< int64_t > &gridDims, TransformOpInterface transformOp)
Maps the top level scf.foreach_thread op to GPU Thread Blocks.
DiagnosedSilenceableFailure findTopLevelForeachThreadOp (Operation *target, scf::ForeachThreadOp &topLevelForeachThreadOp, TransformOpInterface transformOp)
Finds the top level scf::ForeachThreadOp of given target.
Function Documentation
findTopLevelForeachThreadOp()
DiagnosedSilenceableFailure mlir::transform::gpu::findTopLevelForeachThreadOp (Operation * target, scf::ForeachThreadOp & topLevelForeachThreadOp, TransformOpInterface transformOp)
Finds the top level scf::ForeachThreadOp of given target.
Definition at line 213 of file GPUTransformOps.cpp.
References mlir::WalkResult::advance(), mlir::WalkResult::interrupt(), mlir::DiagnosedSilenceableFailure::success(), and mlir::Operation::walk().
Referenced by generateGpuBlockIds().
mapForeachToBlocksImpl()
DiagnosedSilenceableFailure mlir::transform::gpu::mapForeachToBlocksImpl (RewriterBase & rewriter, scf::ForeachThreadOp foreachThreadOp, function_ref< void(RewriterBase &, scf::ForeachThreadOp, SmallVectorImpl< Value > &)> blockIdGenerator, SmallVectorImpl< int64_t > & gridDims, TransformOpInterface transformOp)
Maps the top level scf.foreach_thread op to GPU Thread Blocks.
Mapping is one-to-one and the induction variables of scf.foreach_thread are rewritten to gpu.block_id according to the thread_dim_apping attribute. Dynamic, scf.foreach_thread trip counts are currently not supported. Dynamic block dim sizes are currently not supported.
Definition at line 154 of file GPUTransformOps.cpp.
References mlir::RewriterBase::eraseOp(), mlir::failed(), mlir::Block::front(), mlir::getConstantIntValue(), mlir::Block::getOperations(), mlir::Value::getUsers(), mlir::DiagnosedSilenceableFailure::success(), and value.
Referenced by generateGpuBlockIds().
mapNestedForeachToThreadsImpl()
DiagnosedSilenceableFailure mlir::transform::gpu::mapNestedForeachToThreadsImpl (RewriterBase & rewriter, Operation * target, const SmallVectorImpl< int64_t > & blockDim, bool syncAfterDistribute, llvm::Optional< TransformOpInterface > transformOp)
Searches scf.foreach_thread ops nested under target and maps each such op to GPU threads.
Mapping is one-to-one and the induction variables of scf.foreach_thread are rewritten to gpu.thread_id according to the thread_dim_apping attribute. Sibling scf.foreach_thread are supported in which case, the union of the number of threads is computed and may result in predication. Dynamic, scf.foreach_thread trip counts are currently not supported. Dynamic block dim sizes are currently not supported.
Definition at line 425 of file GPUTransformOps.cpp.
References mlir::WalkResult::advance(), alterGpuLaunch(), mlir::DiagnosedSilenceableFailure::attachNote(), checkGpuLimits(), diag(), mlir::extractFromI64ArrayAttr(), mlir::WalkResult::interrupt(), mlir::DiagnosedSilenceableFailure::isSilenceableFailure(), rewriteOneForeachThreadToGpuThreads(), mlir::OpBuilder::setInsertionPoint(), mlir::DiagnosedSilenceableFailure::succeeded(), mlir::DiagnosedSilenceableFailure::success(), and mlir::Operation::walk().