MLIR: mlir::quant::detail Namespace Reference
mlir::quant::detail Namespace Reference
Classes
struct AnyQuantizedTypeStorage
struct CalibratedQuantizedTypeStorage
struct QuantizedTypeStorage
struct UniformQuantizedPerAxisTypeStorage
struct UniformQuantizedTypeStorage
Functions
void addBytecodeInterface (QuantizationDialect *dialect)
Add the interfaces necessary for encoding the quantization dialect components in bytecode.
Function Documentation
addBytecodeInterface()
void mlir::quant::detail::addBytecodeInterface (QuantizationDialect * dialect)
Add the interfaces necessary for encoding the quantization dialect components in bytecode.
Definition at line 126 of file QuantDialectBytecode.cpp.
References mlir::DialectBytecodeReader::emitError(), mlir::failed(), mlir::failure(), mlir::quant::AnyQuantizedType::get(), mlir::quant::UniformQuantizedType::get(), mlir::quant::UniformQuantizedPerAxisType::get(), mlir::quant::CalibratedQuantizedType::get(), mlir::quant::CalibratedQuantizedType::getMax(), mlir::quant::CalibratedQuantizedType::getMin(), mlir::quant::UniformQuantizedPerAxisType::getQuantizedDimension(), mlir::quant::UniformQuantizedType::getScale(), mlir::quant::UniformQuantizedPerAxisType::getScales(), mlir::quant::UniformQuantizedType::getZeroPoint(), mlir::quant::UniformQuantizedPerAxisType::getZeroPoints(), max(), min(), mlir::DialectBytecodeReader::readAPFloatWithKnownSemantics(), mlir::DialectBytecodeReader::readList(), mlir::DialectBytecodeReader::readSignedVarInt(), mlir::DialectBytecodeReader::readSignedVarInts(), mlir::DialectBytecodeReader::readType(), mlir::DialectBytecodeReader::readVarInt(), mlir::succeeded(), mlir::success(), mlir::DialectBytecodeWriter::writeAPFloatWithKnownSemantics(), mlir::DialectBytecodeWriter::writeList(), mlir::DialectBytecodeWriter::writeSignedVarInt(), mlir::DialectBytecodeWriter::writeSignedVarInts(), mlir::DialectBytecodeWriter::writeType(), and mlir::DialectBytecodeWriter::writeVarInt().