MLIR: mlir::sparse_tensor::detail Namespace Reference
mlir::sparse_tensor::detail Namespace Reference
Classes
struct is_complex
struct is_complex< std::complex< T > >
Functions
uint64_t checkedMul (uint64_t lhs, uint64_t rhs)
A version of operator* on uint64_t which guards against overflows (when assertions are enabled).
template<typename V >
std::enable_if_t<!is_complex< V >::value, V > readCOOValue (char **linePtr, bool is_pattern)
Reads an element of a non-complex type for the current indices in coordinate scheme.
template<typename V >
std::enable_if_t< is_complex< V >::value, V > readCOOValue (char **linePtr, bool is_pattern)
Reads an element of a complex type for the current indices in coordinate scheme.
void assertPermutedSizesMatchShape (const std::vector< uint64_t > &dimSizes, uint64_t rank, const uint64_t *perm, const uint64_t *shape)
Asserts that the dimSizes (in target-order) under the perm (mapping semantic-order to target-order) are a refinement of the desired shape (in semantic-order).
Function Documentation
assertPermutedSizesMatchShape()
void mlir::sparse_tensor::detail::assertPermutedSizesMatchShape (const std::vector< uint64_t > & dimSizes, uint64_t rank, const uint64_t * perm, const uint64_t * shape)
Asserts that the dimSizes (in target-order) under the perm (mapping semantic-order to target-order) are a refinement of the desired shape (in semantic-order).
Precondition: perm and shape must be valid for rank.
Definition at line 108 of file Storage.cpp.
Referenced by mlir::sparse_tensor::SparseTensorStorage< P, I, V >::newSparseTensor().
checkedMul()
uint64_t mlir::sparse_tensor::detail::checkedMul (uint64_t lhs, uint64_t rhs) inline
A version of operator* on uint64_t which guards against overflows (when assertions are enabled).
Definition at line 38 of file CheckedMul.h.
Referenced by mlir::sparse_tensor::SparseTensorNNZ::SparseTensorNNZ(), mlir::sparse_tensor::SparseTensorStorage< P, I, V >::SparseTensorStorage(), and mlir::sparse_tensor::SparseTensorStorage< P, I, V >::toCOO().
readCOOValue() [1/2]
template<typename V > std::enable_if_t<!is_complex<V>::value, V> mlir::sparse_tensor::detail::readCOOValue (char ** linePtr, bool is_pattern) inline
Reads an element of a non-complex type for the current indices in coordinate scheme.
Definition at line 48 of file File.h.
readCOOValue() [2/2]
template<typename V > std::enable_if_t<is_complex<V>::value, V> mlir::sparse_tensor::detail::readCOOValue (char ** linePtr, bool is_pattern) inline
Reads an element of a complex type for the current indices in coordinate scheme.
Definition at line 58 of file File.h.