MLIR: lib/Conversion/NVGPUToNVVM/NVGPUToNVVM.cpp File Reference
NVGPUToNVVM.cpp File Reference
#include "mlir/Conversion/NVGPUToNVVM/NVGPUToNVVM.h"
#include "mlir/Conversion/LLVMCommon/ConversionTarget.h"
#include "mlir/Conversion/LLVMCommon/Pattern.h"
#include "mlir/Dialect/GPU/IR/GPUDialect.h"
#include "mlir/Dialect/LLVMIR/NVVMDialect.h"
#include "mlir/Dialect/NVGPU/IR/NVGPUDialect.h"
#include "mlir/Pass/Pass.h"
#include "mlir/Conversion/Passes.h.inc"
Namespaces
mlir
Include the generated interface declarations.
Macros
#define GEN_PASS_DEF_CONVERTNVGPUTONVVM
Functions
static Type inferIntrinsicResultType (Type vectorResultType)
Returns the type for the intrinsic given the vectorResultType of the gpu.mma.sync operation.
static Value convertIntrinsicResult (Location loc, Type intrinsicResultType, Type resultType, Value intrinsicResult, RewriterBase &rewriter)
Convert the SSA result of the NVVM intrinsic nvvm.mma.sync (which is always an LLVM struct) into a fragment that is compatible with the vector type of this operation.
static SmallVector< Value > unpackOperandVector (RewriterBase &rewriter, Location loc, Value operand, NVVM::MMATypes operandPtxType)
The gpu.mma.sync converter below expects matrix fragment operands to be given as 2D vectors where the rows are 32b or 64b wide.
Macro Definition Documentation
GEN_PASS_DEF_CONVERTNVGPUTONVVM
#define GEN_PASS_DEF_CONVERTNVGPUTONVVM
Definition at line 19 of file NVGPUToNVVM.cpp.
Function Documentation
convertIntrinsicResult()
static Value convertIntrinsicResult (Location loc, Type intrinsicResultType, Type resultType, Value intrinsicResult, RewriterBase & rewriter) static
Convert the SSA result of the NVVM intrinsic nvvm.mma.sync (which is always an LLVM struct) into a fragment that is compatible with the vector type of this operation.
This involves extracting elements from the struct and inserting them into an LLVM array. These extra data-movement operations should be canonicalized away by the LLVM backend.
Definition at line 66 of file NVGPUToNVVM.cpp.
References mlir::OpBuilder::create(), mlir::OpBuilder::createOrFold(), mlir::Type::dyn_cast(), mlir::detail::enumerate(), mlir::Builder::getContext(), mlir::Builder::getF16Type(), mlir::Builder::getF32Type(), mlir::Builder::getF64Type(), mlir::LLVM::getFixedVectorType(), mlir::Builder::getI32IntegerAttr(), and mlir::Builder::getI32Type().
Referenced by unpackOperandVector().
inferIntrinsicResultType()
static Type inferIntrinsicResultType (Type vectorResultType) static
Returns the type for the intrinsic given the vectorResultType of the gpu.mma.sync operation.
Definition at line 27 of file NVGPUToNVVM.cpp.
References mlir::Type::cast(), mlir::Type::getContext(), mlir::LLVM::getFixedVectorType(), and mlir::LLVM::LLVMStructType::getLiteral().
Referenced by unpackOperandVector().
unpackOperandVector()
static SmallVector<Value> unpackOperandVector (RewriterBase & rewriter, Location loc, Value operand, NVVM::MMATypes operandPtxType) static
The gpu.mma.sync converter below expects matrix fragment operands to be given as 2D vectors where the rows are 32b or 64b wide.
The nvvm.mma.sync op expects these argments to be a given in a long list of scalars of certain types. This function helps unpack the vector arguments and cast them to the types expected by nvvm.mma.sync.
Definition at line 142 of file NVGPUToNVVM.cpp.
References mlir::TypeConverter::addConversion(), mlir::ConversionTarget::addLegalDialect(), mlir::applyPartialConversion(), mlir::Attribute::cast(), mlir::Type::cast(), convertIntrinsicResult(), mlir::TypeConverter::convertType(), mlir::OpBuilder::create(), mlir::Attribute::dyn_cast(), mlir::ConversionPatternRewriter::eraseOp(), mlir::failed(), mlir::failure(), mlir::Builder::getContext(), mlir::Builder::getF32Type(), mlir::Builder::getF64Type(), mlir::LLVM::getFixedVectorType(), mlir::Builder::getI32IntegerAttr(), mlir::Builder::getI32Type(), mlir::Builder::getI64IntegerAttr(), mlir::Builder::getI64Type(), mlir::Builder::getI8Type(), mlir::Builder::getIntegerType(), mlir::LLVM::LLVMStructType::getLiteral(), mlir::Value::getType(), inferIntrinsicResultType(), kGlobalMemorySpace, mlir::populateNVGPUToNVVMConversionPatterns(), mlir::ConversionPatternRewriter::replaceOp(), and mlir::success().