MLIR: lib/Target/LLVMIR/Dialect/NVVM/NVVMToLLVMIRTranslation.cpp File Reference
NVVMToLLVMIRTranslation.cpp File Reference
#include "mlir/Target/LLVMIR/Dialect/NVVM/NVVMToLLVMIRTranslation.h"
#include "mlir/Dialect/LLVMIR/NVVMDialect.h"
#include "mlir/Dialect/Utils/StaticValueUtils.h"
#include "mlir/IR/Operation.h"
#include "mlir/Support/LogicalResult.h"
#include "mlir/Target/LLVMIR/ModuleTranslation.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/IntrinsicsNVPTX.h"
#include "mlir/Dialect/LLVMIR/NVVMConversions.inc"
Functions
static llvm::Intrinsic::ID getShflIntrinsicId (llvm::Type *resultType, NVVM::ShflKind kind, bool withPredicate)
static llvm::Intrinsic::ID getLdMatrixIntrinsicId (NVVM::MMALayout layout, int32_t num)
Return the intrinsic ID associated with ldmatrix for the given paramters.
Function Documentation
getLdMatrixIntrinsicId()
static llvm::Intrinsic::ID getLdMatrixIntrinsicId (NVVM::MMALayout layout, int32_t num) static
Return the intrinsic ID associated with ldmatrix for the given paramters.
Definition at line 70 of file NVVMToLLVMIRTranslation.cpp.
References mlir::Attribute::dyn_cast(), mlir::extractFromI64ArrayAttr(), mlir::failure(), mlir::LLVM::ModuleTranslation::getLLVMContext(), mlir::NamedAttribute::getName(), mlir::LLVM::ModuleTranslation::getOrInsertNamedModuleMetadata(), mlir::NamedAttribute::getValue(), mlir::LLVMTranslationDialectInterface::LLVMTranslationDialectInterface(), mlir::LLVM::ModuleTranslation::lookupFunction(), mlir::success(), and value.
getShflIntrinsicId()
static llvm::Intrinsic::ID getShflIntrinsicId (llvm::Type * resultType, NVVM::ShflKind kind, bool withPredicate) static
Definition at line 28 of file NVVMToLLVMIRTranslation.cpp.