MLIR: lib/Dialect/LLVMIR/IR/NVVMDialect.cpp File Reference
NVVMDialect.cpp File Reference
#include "mlir/Dialect/LLVMIR/NVVMDialect.h"
#include "mlir/Dialect/Utils/StaticValueUtils.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/BuiltinAttributes.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/DialectImplementation.h"
#include "mlir/IR/MLIRContext.h"
#include "mlir/IR/Operation.h"
#include "mlir/IR/OperationSupport.h"
#include "llvm/ADT/TypeSwitch.h"
#include "llvm/AsmParser/Parser.h"
#include "llvm/IR/Attributes.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/Type.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/SourceMgr.h"
#include "mlir/Dialect/LLVMIR/NVVMOpsDialect.cpp.inc"
#include "mlir/Dialect/LLVMIR/NVVMOpsEnums.cpp.inc"
#include "mlir/Dialect/LLVMIR/NVVMOps.cpp.inc"
#include "mlir/Dialect/LLVMIR/NVVMOpsAttributes.cpp.inc"
Macros
#define GET_OP_LIST
#define GET_ATTRDEF_LIST
#define GET_OP_CLASSES
#define GET_ATTRDEF_CLASSES
Functions
static void printNVVMIntrinsicOp (OpAsmPrinter &p, Operation *op)
static bool isInt4PtxType (MMATypes type)
static bool isInt8PtxType (MMATypes type)
static bool isIntegerPtxType (MMATypes type)
Macro Definition Documentation
GET_ATTRDEF_CLASSES
#define GET_ATTRDEF_CLASSES
Definition at line 715 of file NVVMDialect.cpp.
GET_ATTRDEF_LIST
#define GET_ATTRDEF_LIST
GET_OP_CLASSES
#define GET_OP_CLASSES
Definition at line 712 of file NVVMDialect.cpp.
GET_OP_LIST
#define GET_OP_LIST
Function Documentation
isInt4PtxType()
static bool isInt4PtxType (MMATypes type) static
Definition at line 107 of file NVVMDialect.cpp.
Referenced by isIntegerPtxType().
isInt8PtxType()
static bool isInt8PtxType (MMATypes type) static
Definition at line 111 of file NVVMDialect.cpp.
Referenced by isIntegerPtxType().
isIntegerPtxType()
static bool isIntegerPtxType (MMATypes type) static
Definition at line 115 of file NVVMDialect.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::addOperands(), mlir::Builder::getAttr(), mlir::Builder::getContext(), isInt4PtxType(), isInt8PtxType(), print(), mlir::AsmPrinter::printArrowTypeList(), mlir::OpAsmPrinter::printOperands(), and mlir::OpAsmPrinter::printOptionalAttrDict().
printNVVMIntrinsicOp()
static void printNVVMIntrinsicOp (OpAsmPrinter & p, Operation * op) static
Definition at line 45 of file NVVMDialect.cpp.
References mlir::AsmParser::addTypeToList(), mlir::OperationState::attributes, mlir::Type::dyn_cast(), mlir::emitError(), mlir::failure(), mlir::Type::getContext(), mlir::AsmParser::getContext(), mlir::LLVM::getFixedVectorType(), mlir::AsmParser::getNameLoc(), mlir::Operation::getNumResults(), mlir::Operation::getOperands(), mlir::Operation::getResultTypes(), mlir::Type::isa(), mlir::Type::isF16(), mlir::Type::isF32(), mlir::Type::isF64(), mlir::OperationState::operands, mlir::AsmParser::parseColonType(), mlir::OpAsmParser::parseOperandList(), mlir::AsmParser::parseOptionalAttrDict(), print(), mlir::OpAsmParser::resolveOperands(), mlir::success(), mlir::OperationState::types, and mlir::verify().