MLIR: lib/Dialect/Bufferization/Transforms/OneShotModuleBufferize.cpp File Reference
OneShotModuleBufferize.cpp File Reference
#include "mlir/Dialect/Bufferization/Transforms/OneShotModuleBufferize.h"
#include "mlir/Dialect/Bufferization/IR/BufferizableOpInterface.h"
#include "mlir/Dialect/Bufferization/IR/Bufferization.h"
#include "mlir/Dialect/Bufferization/Transforms/Bufferize.h"
#include "mlir/Dialect/Bufferization/Transforms/FuncBufferizableOpInterfaceImpl.h"
#include "mlir/Dialect/Bufferization/Transforms/OneShotAnalysis.h"
#include "mlir/Dialect/Bufferization/Transforms/TensorCopyInsertion.h"
#include "mlir/Dialect/Func/IR/FuncOps.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/IR/Operation.h"
Typedefs
using FuncCallerMap = DenseMap< func::FuncOp, DenseSet< Operation * > >
A mapping of FuncOps to their callers.
Functions
static const FuncAnalysisState & getFuncAnalysisState (const AnalysisState &state)
Get FuncAnalysisState.
static FuncAnalysisState & getFuncAnalysisState (AnalysisState &state)
Get or create FuncAnalysisState.
static LLVM_ATTRIBUTE_UNUSED FuncOpAnalysisState getFuncOpAnalysisState (const AnalysisState &state, func::FuncOp funcOp)
Return the state (phase) of analysis of the FuncOp.
static func::ReturnOp getAssumedUniqueReturnOp (func::FuncOp funcOp)
Return the unique ReturnOp that terminates funcOp.
static void removeBufferizationAttributes (BlockArgument bbArg)
Remove bufferization attributes on FuncOp arguments.
static func::FuncOp getCalledFunction (CallOpInterface callOp)
Return the func::FuncOp called by callOp.
static void equivalenceAnalysis (func::FuncOp funcOp, BufferizationAliasInfo &aliasInfo, OneShotAnalysisState &state)
Gather equivalence info of CallOps.
static LogicalResult getFuncOpsOrderedByCalls (ModuleOp moduleOp, SmallVectorImpl< func::FuncOp > &orderedFuncOps, FuncCallerMap &callerMap)
Store all functions of the moduleOp in orderedFuncOps, sorted by callee-caller order (i.e.
static void foldMemRefCasts (func::FuncOp funcOp)
Fold return values that are memref casts and update function return types.
Typedef Documentation
FuncCallerMap
using FuncCallerMap = DenseMap<func::FuncOp, DenseSet<Operation *> >
A mapping of FuncOps to their callers.
Definition at line 77 of file OneShotModuleBufferize.cpp.
Function Documentation
equivalenceAnalysis()
static void equivalenceAnalysis (func::FuncOp funcOp, BufferizationAliasInfo & aliasInfo, OneShotAnalysisState & state) static
Gather equivalence info of CallOps.
Note: This only adds new equivalence info if the called function was already analyzed.
Definition at line 247 of file OneShotModuleBufferize.cpp.
References mlir::WalkResult::advance(), mlir::bufferization::func_ext::FuncAnalysisState::equivalentFuncArgs, mlir::bufferization::func_ext::getCalledFunction(), mlir::bufferization::func_ext::getFuncAnalysisState(), mlir::bufferization::OneShotAnalysisState::isInPlace(), mlir::WalkResult::skip(), and mlir::bufferization::BufferizationAliasInfo::unionEquivalenceClasses().
Referenced by mlir::bufferization::analyzeModuleOp().
foldMemRefCasts()
static void foldMemRefCasts (func::FuncOp funcOp) static
Fold return values that are memref casts and update function return types.
During FuncOp bufferization, the exact type of the returned memrefs (if any) is not known yet. Therefore, the bufferization uses memref types with the most generic layout map as function return types. After bufferizing the entire function body, a more concise memref type can potentially be used for the return type of the function.
Definition at line 335 of file OneShotModuleBufferize.cpp.
References mlir::bufferization::func_ext::getAssumedUniqueReturnOp().
Referenced by mlir::bufferization::bufferizeModuleOp().
getAssumedUniqueReturnOp()
static func::ReturnOp getAssumedUniqueReturnOp (func::FuncOp funcOp) static
Return the unique ReturnOp that terminates funcOp.
Return nullptr if there is no such unique ReturnOp.
Definition at line 109 of file OneShotModuleBufferize.cpp.
References mlir::bufferization::func_ext::FuncAnalysisState::aliasingFuncArgs, mlir::bufferization::func_ext::FuncAnalysisState::aliasingReturnVals, mlir::bufferization::OneShotAnalysisState::areAliasingBufferizedValues(), mlir::bufferization::OneShotAnalysisState::areEquivalentBufferizedValues(), mlir::Attribute::cast(), mlir::bufferization::func_ext::FuncAnalysisState::equivalentFuncArgs, mlir::IROperand< DerivedT, IRValueT >::get(), mlir::BlockArgument::getArgNumber(), mlir::bufferization::func_ext::getAssumedUniqueReturnOp(), mlir::Operation::getAttr(), mlir::Operation::getContext(), mlir::bufferization::func_ext::getFuncAnalysisState(), mlir::Operation::getNumOperands(), mlir::OpOperand::getOperandNumber(), mlir::bufferization::AnalysisState::getOptions(), mlir::detail::IROperandBase::getOwner(), mlir::Value::getType(), mlir::Operation::hasAttr(), mlir::Type::isa(), mlir::bufferization::AnalysisState::isValueRead(), mlir::bufferization::OneShotAnalysisState::isValueWritten(), mlir::bufferization::func_ext::FuncAnalysisState::readBbArgs, mlir::Operation::setAttr(), mlir::success(), mlir::bufferization::BufferizationOptions::testAnalysisOnly, and mlir::bufferization::func_ext::FuncAnalysisState::writtenBbArgs.
getCalledFunction()
static func::FuncOp getCalledFunction (CallOpInterface callOp) static
Return the func::FuncOp called by callOp.
Definition at line 235 of file OneShotModuleBufferize.cpp.
References mlir::SymbolTable::lookupNearestSymbolFrom().
getFuncAnalysisState() [1/2]
static const FuncAnalysisState& getFuncAnalysisState (const AnalysisState & state) static
Get FuncAnalysisState.
Definition at line 81 of file OneShotModuleBufferize.cpp.
getFuncAnalysisState() [2/2]
static FuncAnalysisState& getFuncAnalysisState (AnalysisState & state) static
Get or create FuncAnalysisState.
Definition at line 90 of file OneShotModuleBufferize.cpp.
getFuncOpAnalysisState()
static LLVM_ATTRIBUTE_UNUSED FuncOpAnalysisState getFuncOpAnalysisState (const AnalysisState & state, func::FuncOp funcOp) static
Return the state (phase) of analysis of the FuncOp.
Used for debug modes.
Definition at line 98 of file OneShotModuleBufferize.cpp.
References mlir::bufferization::func_ext::FuncAnalysisState::analyzedFuncOps, mlir::bufferization::func_ext::getFuncAnalysisState(), and mlir::bufferization::func_ext::NotAnalyzed.
getFuncOpsOrderedByCalls()
static LogicalResult getFuncOpsOrderedByCalls (ModuleOp moduleOp, SmallVectorImpl< func::FuncOp > & orderedFuncOps, FuncCallerMap & callerMap) static
Store all functions of the moduleOp in orderedFuncOps, sorted by callee-caller order (i.e.
callees without callers first). Store the map of FuncOp to all its callers in callerMap. Return failure() if a cycle of calls is detected or if we are unable to retrieve the called FuncOp from any CallOpInterface.
Definition at line 279 of file OneShotModuleBufferize.cpp.
Referenced by mlir::bufferization::analyzeModuleOp(), and mlir::bufferization::bufferizeModuleOp().
removeBufferizationAttributes()
static void removeBufferizationAttributes (BlockArgument bbArg) static
Remove bufferization attributes on FuncOp arguments.
Definition at line 226 of file OneShotModuleBufferize.cpp.
References mlir::BlockArgument::getArgNumber(), mlir::BlockArgument::getOwner(), and mlir::Block::getParentOp().
Referenced by mlir::bufferization::bufferizeModuleOp().