MLIR: lib/Dialect/NVGPU/Transforms/OptimizeSharedMemory.cpp File Reference
OptimizeSharedMemory.cpp File Reference
#include "mlir/Dialect/NVGPU/Passes.h"
#include "mlir/Dialect/Arith/IR/Arith.h"
#include "mlir/Dialect/GPU/IR/GPUDialect.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/Dialect/NVGPU/IR/NVGPUDialect.h"
#include "mlir/Dialect/NVGPU/Transforms/Transforms.h"
#include "mlir/Dialect/Vector/IR/VectorOps.h"
#include "mlir/Interfaces/SideEffectInterfaces.h"
#include "mlir/Support/LogicalResult.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/Support/MathExtras.h"
#include "mlir/Dialect/NVGPU/Passes.h.inc"
Namespaces
mlir
Include the generated interface declarations.
mlir::nvgpu
Macros
#define GEN_PASS_DEF_OPTIMIZESHAREDMEMORY
Functions
static Value permuteVectorOffset (OpBuilder &b, Location loc, ArrayRef< Value > indices, MemRefType memrefTy, int64_t srcDim, int64_t tgtDim)
Uses srcIndexValue to permute tgtIndexValue via `result = xor(floordiv(srcIdxVal,permuteEveryN), floordiv(tgtIdxVal,vectorSize)))
static void transformIndices (OpBuilder &builder, Location loc, SmallVector< Value, 4 > &indices, MemRefType memrefTy, int64_t srcDim, int64_t tgtDim)
Operation::operand_range getIndices (Operation *op)
void setIndices (Operation *op, ArrayRef< Value > indices)
static LogicalResult getShmReadAndWriteOps (Operation *parentOp, Value shmMemRef, SmallVector< Operation *, 16 > &readOps, SmallVector< Operation *, 16 > &writeOps)
Return all operations within parentOp that read from or write to shmMemRef.
Variables
constexpr int64_t kSharedMemoryLineSizeBytes = 128
The size of a shared memory line according to NV documentation.
constexpr int64_t kDefaultVectorSizeBits = 128
We optimize for 128bit accesses, but this can be made an argument in the future.
Macro Definition Documentation
GEN_PASS_DEF_OPTIMIZESHAREDMEMORY
#define GEN_PASS_DEF_OPTIMIZESHAREDMEMORY
Definition at line 28 of file OptimizeSharedMemory.cpp.
Function Documentation
getIndices()
Operation::operand_range getIndices (Operation * op)
Definition at line 110 of file OptimizeSharedMemory.cpp.
Referenced by mlir::detail::DenseResourceElementsAttrBase< T >::classof(), concatElemAndIndices(), extractCompositeElement(), foldTransferInBoundsAttribute(), getShmReadAndWriteOps(), joinShapes(), mlirSparseElementsAttrGetIndices(), mlir::nvgpu::optimizeSharedMemoryReadsAndWrites(), parseGlobalMemrefOpTypeAndInitialValue(), printAccessChain(), printSwitchOpCases(), printTransferAttrs(), verifyAccessChain(), verifyAtomicCompareExchangeImpl(), verifyGatherOrScatterDims(), verifyMultShape(), verifyNumBlockArgs(), and verifyStructIndices().
getShmReadAndWriteOps()
static LogicalResult getShmReadAndWriteOps (Operation * parentOp, Value shmMemRef, SmallVector< Operation *, 16 > & readOps, SmallVector< Operation *, 16 > & writeOps) static
Return all operations within parentOp that read from or write to shmMemRef.
Definition at line 145 of file OptimizeSharedMemory.cpp.
References mlir::failure(), getIndices(), mlir::success(), and mlir::Operation::walk().
Referenced by mlir::nvgpu::optimizeSharedMemoryReadsAndWrites().
permuteVectorOffset()
static Value permuteVectorOffset (OpBuilder & b, Location loc, ArrayRef< Value > indices, MemRefType memrefTy, int64_t srcDim, int64_t tgtDim) static
Uses srcIndexValue to permute tgtIndexValue via `result = xor(floordiv(srcIdxVal,permuteEveryN), floordiv(tgtIdxVal,vectorSize)))
tgtIdxVal % vectorSize This is done using an optimized sequence ofarith` operations.
Definition at line 47 of file OptimizeSharedMemory.cpp.
References mlir::OpBuilder::create(), mlir::OpBuilder::createOrFold(), kDefaultVectorSizeBits, and kSharedMemoryLineSizeBytes.
Referenced by transformIndices().
setIndices()
void setIndices (Operation * op, ArrayRef< Value > indices)
Definition at line 126 of file OptimizeSharedMemory.cpp.
Referenced by mlir::nvgpu::optimizeSharedMemoryReadsAndWrites().
transformIndices()
static void transformIndices (OpBuilder & builder, Location loc, SmallVector< Value, 4 > & indices, MemRefType memrefTy, int64_t srcDim, int64_t tgtDim) static
Definition at line 102 of file OptimizeSharedMemory.cpp.
References permuteVectorOffset().
Referenced by mlir::nvgpu::optimizeSharedMemoryReadsAndWrites().
Variable Documentation
kDefaultVectorSizeBits
constexpr int64_t kDefaultVectorSizeBits = 128
We optimize for 128bit accesses, but this can be made an argument in the future.
Definition at line 40 of file OptimizeSharedMemory.cpp.
Referenced by mlir::nvgpu::optimizeSharedMemoryReadsAndWrites(), and permuteVectorOffset().
kSharedMemoryLineSizeBytes
constexpr int64_t kSharedMemoryLineSizeBytes = 128
The size of a shared memory line according to NV documentation.
Definition at line 37 of file OptimizeSharedMemory.cpp.
Referenced by mlir::nvgpu::optimizeSharedMemoryReadsAndWrites(), and permuteVectorOffset().