MLIR: lib/Conversion/PDLToPDLInterp/PDLToPDLInterp.cpp File Reference
PDLToPDLInterp.cpp File Reference
#include "mlir/Conversion/PDLToPDLInterp/PDLToPDLInterp.h"
#include "PredicateTree.h"
#include "mlir/Dialect/PDL/IR/PDL.h"
#include "mlir/Dialect/PDL/IR/PDLTypes.h"
#include "mlir/Dialect/PDLInterp/IR/PDLInterp.h"
#include "mlir/Pass/Pass.h"
#include "llvm/ADT/MapVector.h"
#include "llvm/ADT/ScopedHashTable.h"
#include "llvm/ADT/Sequence.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/TypeSwitch.h"
#include "mlir/Conversion/Passes.h.inc"
Namespaces
mlir
Include the generated interface declarations.
Macros
#define GEN_PASS_DEF_CONVERTPDLTOPDLINTERP
Functions
template<typename OpT , typename PredT , typename ValT = typename PredT::KeyTy>
static void createSwitchOp (Value val, Block *defaultDest, OpBuilder &builder, llvm::MapVector< Qualifier *, Block *> &dests)
Macro Definition Documentation
GEN_PASS_DEF_CONVERTPDLTOPDLINTERP
#define GEN_PASS_DEF_CONVERTPDLTOPDLINTERP
Definition at line 24 of file PDLToPDLInterp.cpp.
Function Documentation
createSwitchOp()
template<typename OpT , typename PredT , typename ValT = typename PredT::KeyTy> static void createSwitchOp (Value val, Block * defaultDest, OpBuilder & builder, llvm::MapVector< Qualifier *, Block *> & dests) static
Definition at line 450 of file PDLToPDLInterp.cpp.
References mlir::Block::back(), mlir::OpBuilder::create(), mlir::Value::getLoc(), mlir::Block::getParent(), and mlir::pdl_to_pdl_interp::MatcherNode::getQuestion().