MLIR: lib/Dialect/Utils/ReshapeOpsUtils.cpp File Reference
ReshapeOpsUtils.cpp File Reference
#include "mlir/Dialect/Utils/ReshapeOpsUtils.h"
#include "mlir/IR/AffineMap.h"
#include "mlir/IR/Builders.h"
#include <numeric>
Functions
template<typename AffineExprTy >
unsigned getMaxPosOfType (ArrayRef< ReassociationExprs > exprArrays)
static Optional< int64_t > getUniqueNonUnitDim (ArrayRef< int64_t > indices, ArrayRef< int64_t > shape)
Returns the index of the only non-unit dimension among indices of shape, if such a dimension exists and indices has more than one element.
static SmallVector< Optional< int64_t > > getCollapseShapeTrivialSegments (RankedTensorType sourceType, ArrayRef< ReassociationIndices > reassociationIndices)
static FailureOr< SmallVector< Optional< int64_t > > > canCollapseShapeBeSimplifiedByRankReducingSlice (RankedTensorType sourceType, ArrayRef< ReassociationIndices > reassociationIndices)
Returns true if any of the segments of the reassociation indices for a collapsing reshape can be simplified using a rank-reducing slice.
Function Documentation
canCollapseShapeBeSimplifiedByRankReducingSlice()
static FailureOr<SmallVector<Optional<int64_t> > > canCollapseShapeBeSimplifiedByRankReducingSlice (RankedTensorType sourceType, ArrayRef< ReassociationIndices > reassociationIndices) static
Returns true if any of the segments of the reassociation indices for a collapsing reshape can be simplified using a rank-reducing slice.
Definition at line 391 of file ReshapeOpsUtils.cpp.
References mlir::failed(), mlir::failure(), getCollapseShapeTrivialSegments(), and None.
getCollapseShapeTrivialSegments()
static SmallVector<Optional<int64_t> > getCollapseShapeTrivialSegments (RankedTensorType sourceType, ArrayRef< ReassociationIndices > reassociationIndices) static
Definition at line 378 of file ReshapeOpsUtils.cpp.
References getUniqueNonUnitDim().
Referenced by canCollapseShapeBeSimplifiedByRankReducingSlice().
getMaxPosOfType()
template<typename AffineExprTy > unsigned getMaxPosOfType (ArrayRef< ReassociationExprs > exprArrays)
Definition at line 146 of file ReshapeOpsUtils.cpp.
References mlir::AffineExpr::dyn_cast(), and max().
getUniqueNonUnitDim()
static Optional<int64_t> getUniqueNonUnitDim (ArrayRef< int64_t > indices, ArrayRef< int64_t > shape) static
Returns the index of the only non-unit dimension among indices of shape, if such a dimension exists and indices has more than one element.
Otherwise, return none.
Definition at line 359 of file ReshapeOpsUtils.cpp.
References None.
Referenced by getCollapseShapeTrivialSegments().