MLIR: lib/Dialect/SCF/TransformOps/SCFTransformOps.cpp File Reference
SCFTransformOps.cpp File Reference
#include "mlir/Dialect/SCF/TransformOps/SCFTransformOps.h"
#include "mlir/Dialect/Affine/IR/AffineOps.h"
#include "mlir/Dialect/Func/IR/FuncOps.h"
#include "mlir/Dialect/SCF/IR/SCF.h"
#include "mlir/Dialect/SCF/Transforms/Patterns.h"
#include "mlir/Dialect/SCF/Transforms/Transforms.h"
#include "mlir/Dialect/SCF/Utils/Utils.h"
#include "mlir/Dialect/Transform/IR/TransformDialect.h"
#include "mlir/Dialect/Transform/IR/TransformInterfaces.h"
#include "mlir/Dialect/Vector/IR/VectorOps.h"
#include "mlir/Dialect/SCF/TransformOps/SCFTransformOps.cpp.inc"
Macros
#define GET_OP_LIST
#define GET_OP_CLASSES
Functions
static scf::ExecuteRegionOp wrapInExecuteRegion (RewriterBase &b, Operation *op)
Wraps the given operation op into an scf.execute_region operation.
static void loopScheduling (scf::ForOp forOp, std::vector< std::pair< Operation *, unsigned >> &schedule, unsigned iterationInterval, unsigned readLatency)
Callback for PipeliningOption.
Macro Definition Documentation
GET_OP_CLASSES
#define GET_OP_CLASSES
Definition at line 252 of file SCFTransformOps.cpp.
GET_OP_LIST
#define GET_OP_LIST
Function Documentation
loopScheduling()
static void loopScheduling (scf::ForOp forOp, std::vector< std::pair< Operation *, unsigned >> & schedule, unsigned iterationInterval, unsigned readLatency) static
Callback for PipeliningOption.
Populates schedule with the mapping from an operation to its logical time position given the iteration interval and the read latency. The latter is only relevant for vector transfers.
Definition at line 157 of file SCFTransformOps.cpp.
References diag(), mlir::failed(), mlir::scf::PipeliningOption::getScheduleFn, mlir::loopUnrollByFactor(), max(), mlir::Note, options, mlir::DiagnosedSilenceableFailure::silenceableFailure(), mlir::succeeded(), and mlir::success().
wrapInExecuteRegion()
static scf::ExecuteRegionOp wrapInExecuteRegion (RewriterBase & b, Operation * op) static
Wraps the given operation op into an scf.execute_region operation.
Uses the provided rewriter for all operations to remain compatible with the rewriting infra, as opposed to just splicing the op in place.
Definition at line 67 of file SCFTransformOps.cpp.
References mlir::DiagnosedSilenceableFailure::attachNote(), mlir::OpBuilder::cloneWithoutRegions(), mlir::OpBuilder::create(), mlir::DiagnosedSilenceableFailure::definiteFailure(), diag(), mlir::Region::empty(), mlir::Region::end(), mlir::failed(), mlir::FlatSymbolRefAttr::get(), mlir::Operation::getLoc(), mlir::SymbolTable::getNearestSymbolTable(), mlir::Operation::getNumRegions(), mlir::transform::TransformState::getPayloadOps(), mlir::Operation::getRegions(), mlir::Operation::getResults(), mlir::Operation::getResultTypes(), mlir::RewriterBase::inlineRegionBefore(), mlir::SymbolTable::insert(), mlir::outlineSingleBlockRegion(), mlir::scf::peelAndCanonicalizeForLoop(), mlir::RewriterBase::replaceOp(), mlir::transform::TransformResults::set(), mlir::OpBuilder::setInsertionPoint(), mlir::OpBuilder::setInsertionPointToStart(), mlir::DiagnosedSilenceableFailure::success(), and mlir::success().