MLIR: lib/Analysis/Presburger/Simplex.cpp File Reference
Simplex.cpp File Reference
#include "mlir/Analysis/Presburger/Simplex.h"
#include "mlir/Analysis/Presburger/Matrix.h"
#include "mlir/Support/MathExtras.h"
#include "llvm/ADT/Optional.h"
#include "llvm/Support/Compiler.h"
#include <numeric>
Classes
class mlir::presburger::GBRSimplex
Given a simplex for a polytope, construct a new simplex whose variables are identified with a pair of points (x, y) in the original polytope.
Typedefs
using Direction = Simplex::Direction
Functions
static LLVM_ATTRIBUTE_UNUSED SmallVector< MPInt, 8 > scaleAndAddForAssert (ArrayRef< MPInt > a, const MPInt &scale, ArrayRef< MPInt > b)
static bool isRangeDivisibleBy (ArrayRef< MPInt > range, const MPInt &divisor)
Variables
const int nullIndex = std::numeric_limits<int>::max()
Typedef Documentation
Direction
using Direction = Simplex::Direction
Definition at line 19 of file Simplex.cpp.
Function Documentation
isRangeDivisibleBy()
static bool isRangeDivisibleBy (ArrayRef< MPInt > range, const MPInt & divisor) static
Definition at line 354 of file Simplex.cpp.
References mlir::presburger::PWMAFunction::addPiece(), mlir::presburger::SimplexBase::addZeroRow(), mlir::presburger::SimplexBase::Column, mlir::failure(), mlir::presburger::SimplexBase::getNumColumns(), mlir::presburger::PWMAFunction::getNumOutputs(), mlir::presburger::SimplexBase::getNumRows(), mlir::presburger::Matrix::getRow(), mlir::presburger::PWMAFunction::getSpace(), mlir::presburger::PresburgerSpace::insertVar(), mlir::presburger::SymbolicLexMin::lexmin, mlir::presburger::Local, mlir::presburger::mod(), mlir::presburger::normalizeDiv(), mlir::presburger::SimplexBase::nSymbol, mlir::presburger::Matrix::reserveRows(), mlir::success(), mlir::presburger::SimplexBase::tableau, mlir::presburger::SymbolicLexMin::unboundedDomain, mlir::presburger::PresburgerRelation::unionInPlace(), and mlir::presburger::SimplexBase::var.
scaleAndAddForAssert()
static LLVM_ATTRIBUTE_UNUSED SmallVector<MPInt, 8> scaleAndAddForAssert (ArrayRef< MPInt > a, const MPInt & scale, ArrayRef< MPInt > b) static
Definition at line 26 of file Simplex.cpp.
Referenced by mlir::presburger::GBRSimplex::removeLastEquality().
Variable Documentation
nullIndex
const int nullIndex = std::numeric_limits<int>::max()
Definition at line 21 of file Simplex.cpp.
Referenced by mlir::presburger::SimplexBase::getSnapshotBasis(), mlir::presburger::Simplex::makeProduct(), mlir::presburger::SimplexBase::SimplexBase(), mlir::presburger::SimplexBase::undo(), and mlir::presburger::SimplexBase::unknownFromIndex().