MLIR: lib/Dialect/SparseTensor/Transforms/SparseBufferRewriting.cpp File Reference
SparseBufferRewriting.cpp File Reference
#include "CodegenUtils.h"
#include "mlir/Dialect/Arith/IR/Arith.h"
#include "mlir/Dialect/Func/IR/FuncOps.h"
#include "mlir/Dialect/Linalg/IR/Linalg.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/Dialect/SCF/IR/SCF.h"
#include "mlir/Dialect/SparseTensor/IR/SparseTensor.h"
#include "mlir/Dialect/SparseTensor/Transforms/Passes.h"
#include "mlir/Support/LLVM.h"
Typedefs
using FuncGeneratorType = function_ref< void(OpBuilder &, ModuleOp, func::FuncOp, size_t)>
Functions
static void getMangledSortHelperFuncName (llvm::raw_svector_ostream &nameOstream, StringRef namePrefix, size_t dim, ValueRange operands)
Constructs a function name with this format to facilitate quick sort: <namePrefix><dim>_<x type>_<y0 type>..._<yn type>
static FlatSymbolRefAttr getMangledSortHelperFunc (OpBuilder &builder, func::FuncOp insertPoint, TypeRange resultTypes, StringRef namePrefix, size_t dim, ValueRange operands, FuncGeneratorType createFunc)
Looks up a function that is appropriate for the given operands being sorted, and creates such a function if it doesn't exist yet.
static void createMaySwapFunc (OpBuilder &builder, ModuleOp unused, func::FuncOp func, size_t dim)
Creates a function for swapping the values in index i and j for all the buffers.
static scf::IfOp createLessThanCompare (OpBuilder &builder, Location loc, Value i, Value j, Value x, bool isLastDim)
Generates an if-statement to compare x[i] and x[j].
static void createLessThanFunc (OpBuilder &builder, ModuleOp unused, func::FuncOp func, size_t dim)
Creates a function to compare the xs values in index i and j for all the dimensions.
static void createBinarySearchFunc (OpBuilder &builder, ModuleOp module, func::FuncOp func, size_t dim)
Creates a function to use a binary search to find the insertion point for inserting xs[hi] to the sorted values xs[lo..hi).
static void createPartitionFunc (OpBuilder &builder, ModuleOp module, func::FuncOp func, size_t dim)
Creates a function to perform quick sort partition on the values in the range of index [lo, hi), assuming lo < hi.
static void createSortNonstableFunc (OpBuilder &builder, ModuleOp module, func::FuncOp func, size_t dim)
Creates a function to perform quick sort on the value in the range of index [lo, hi).
static void createSortStableFunc (OpBuilder &builder, ModuleOp module, func::FuncOp func, size_t dim)
Creates a function to perform insertion sort on the values in the range of index [lo, hi).
Variables
static constexpr uint64_t loIdx = 0
static constexpr uint64_t hiIdx = 1
static constexpr uint64_t xStartIdx = 2
static constexpr const char kMaySwapFuncNamePrefix [] = "_sparse_may_swap_"
static constexpr const char kLessThanFuncNamePrefix [] = "_sparse_less_than_"
static constexpr const char kPartitionFuncNamePrefix [] = "_sparse_partition_"
static constexpr const char kBinarySearchFuncNamePrefix []
static constexpr const char kSortNonstableFuncNamePrefix []
static constexpr const char kSortStableFuncNamePrefix []
Typedef Documentation
FuncGeneratorType
using FuncGeneratorType = function_ref<void(OpBuilder &, ModuleOp, func::FuncOp, size_t)>
Definition at line 47 of file SparseBufferRewriting.cpp.
Function Documentation
createBinarySearchFunc()
static void createBinarySearchFunc (OpBuilder & builder, ModuleOp module, func::FuncOp func, size_t dim) static
Creates a function to use a binary search to find the insertion point for inserting xs[hi] to the sorted values xs[lo..hi).
Definition at line 228 of file SparseBufferRewriting.cpp.
References mlir::sparse_tensor::constantIndex(), mlir::OpBuilder::create(), mlir::OpBuilder::createBlock(), createLessThanFunc(), mlir::Block::getArguments(), getMangledSortHelperFunc(), mlir::Value::getType(), hiIdx, kLessThanFuncNamePrefix, loIdx, mlir::OpBuilder::setInsertionPointAfter(), mlir::OpBuilder::setInsertionPointToEnd(), mlir::OpBuilder::setInsertionPointToStart(), and xStartIdx.
Referenced by createSortStableFunc().
createLessThanCompare()
static scf::IfOp createLessThanCompare (OpBuilder & builder, Location loc, Value i, Value j, Value x, bool isLastDim) static
Generates an if-statement to compare x[i] and x[j].
Definition at line 135 of file SparseBufferRewriting.cpp.
References mlir::sparse_tensor::constantI1(), mlir::OpBuilder::create(), mlir::Value::getType(), mlir::OpBuilder::setInsertionPointAfter(), and mlir::OpBuilder::setInsertionPointToStart().
Referenced by createLessThanFunc().
createLessThanFunc()
static void createLessThanFunc (OpBuilder & builder, ModuleOp unused, func::FuncOp func, size_t dim) static
Creates a function to compare the xs values in index i and j for all the dimensions.
The function returns true iff xs[i] < xs[j].
Definition at line 188 of file SparseBufferRewriting.cpp.
References mlir::OpBuilder::create(), createLessThanCompare(), mlir::detail::enumerate(), mlir::Block::getArguments(), mlir::OpBuilder::setInsertionPointAfter(), mlir::OpBuilder::setInsertionPointToStart(), and xStartIdx.
Referenced by createBinarySearchFunc(), and createPartitionFunc().
createMaySwapFunc()
static void createMaySwapFunc (OpBuilder & builder, ModuleOp unused, func::FuncOp func, size_t dim) static
Creates a function for swapping the values in index i and j for all the buffers.
Definition at line 106 of file SparseBufferRewriting.cpp.
References mlir::OpBuilder::create(), mlir::Block::getArguments(), mlir::OpBuilder::setInsertionPointAfter(), mlir::OpBuilder::setInsertionPointToStart(), and xStartIdx.
Referenced by createPartitionFunc().
createPartitionFunc()
static void createPartitionFunc (OpBuilder & builder, ModuleOp module, func::FuncOp func, size_t dim) static
Creates a function to perform quick sort partition on the values in the range of index [lo, hi), assuming lo < hi.
Definition at line 305 of file SparseBufferRewriting.cpp.
References mlir::sparse_tensor::constantIndex(), mlir::OpBuilder::create(), createLessThanFunc(), createMaySwapFunc(), mlir::Block::getArguments(), getMangledSortHelperFunc(), mlir::Value::getType(), hiIdx, kLessThanFuncNamePrefix, kMaySwapFuncNamePrefix, loIdx, mlir::OpBuilder::setInsertionPointAfter(), mlir::OpBuilder::setInsertionPointToStart(), and xStartIdx.
Referenced by createSortNonstableFunc().
createSortNonstableFunc()
static void createSortNonstableFunc (OpBuilder & builder, ModuleOp module, func::FuncOp func, size_t dim) static
Creates a function to perform quick sort on the value in the range of index [lo, hi).
Definition at line 379 of file SparseBufferRewriting.cpp.
References mlir::sparse_tensor::constantIndex(), mlir::OpBuilder::create(), createPartitionFunc(), mlir::Block::getArguments(), getMangledSortHelperFunc(), hiIdx, kPartitionFuncNamePrefix, loIdx, mlir::OpBuilder::setInsertionPointAfter(), mlir::OpBuilder::setInsertionPointToStart(), and xStartIdx.
Referenced by createSortStableFunc().
createSortStableFunc()
static void createSortStableFunc (OpBuilder & builder, ModuleOp module, func::FuncOp func, size_t dim) static
Creates a function to perform insertion sort on the values in the range of index [lo, hi).
Definition at line 431 of file SparseBufferRewriting.cpp.
References mlir::Type::cast(), mlir::sparse_tensor::constantIndex(), mlir::OpBuilder::create(), createBinarySearchFunc(), mlir::OpBuilder::createBlock(), createSortNonstableFunc(), mlir::Block::getArguments(), mlir::Value::getDefiningOp(), getMangledSortHelperFunc(), mlir::Value::getType(), hiIdx, kBinarySearchFuncNamePrefix, kSortNonstableFuncNamePrefix, kSortStableFuncNamePrefix, loIdx, mlir::RewriterBase::replaceOp(), mlir::RewriterBase::replaceOpWithNewOp(), mlir::OpBuilder::setInsertionPointAfter(), mlir::OpBuilder::setInsertionPointToEnd(), mlir::OpBuilder::setInsertionPointToStart(), mlir::success(), value, and xStartIdx.
getMangledSortHelperFunc()
static FlatSymbolRefAttr getMangledSortHelperFunc (OpBuilder & builder, func::FuncOp insertPoint, TypeRange resultTypes, StringRef namePrefix, size_t dim, ValueRange operands, FuncGeneratorType createFunc) static
Looks up a function that is appropriate for the given operands being sorted, and creates such a function if it doesn't exist yet.
Definition at line 65 of file SparseBufferRewriting.cpp.
References mlir::OpBuilder::create(), getMangledSortHelperFuncName(), mlir::ValueRange::getTypes(), and mlir::OpBuilder::setInsertionPoint().
Referenced by createBinarySearchFunc(), createPartitionFunc(), createSortNonstableFunc(), and createSortStableFunc().
getMangledSortHelperFuncName()
static void getMangledSortHelperFuncName (llvm::raw_svector_ostream & nameOstream, StringRef namePrefix, size_t dim, ValueRange operands) static
Constructs a function name with this format to facilitate quick sort: <namePrefix><dim>_<x type>_<y0 type>..._<yn type>
Definition at line 51 of file SparseBufferRewriting.cpp.
References getElementType(), mlir::ValueRange::getType(), and xStartIdx.
Referenced by getMangledSortHelperFunc().
Variable Documentation
hiIdx
constexpr uint64_t hiIdx = 1 static
Definition at line 33 of file SparseBufferRewriting.cpp.
Referenced by createBinarySearchFunc(), createPartitionFunc(), createSortNonstableFunc(), and createSortStableFunc().
kBinarySearchFuncNamePrefix
constexpr const char kBinarySearchFuncNamePrefix[] static
Initial value:
=
    "_sparse_binary_search_"
Definition at line 39 of file SparseBufferRewriting.cpp.
Referenced by createSortStableFunc().
kLessThanFuncNamePrefix
constexpr const char kLessThanFuncNamePrefix[] = "_sparse_less_than_" static
Definition at line 37 of file SparseBufferRewriting.cpp.
Referenced by createBinarySearchFunc(), and createPartitionFunc().
kMaySwapFuncNamePrefix
constexpr const char kMaySwapFuncNamePrefix[] = "_sparse_may_swap_" static
Definition at line 36 of file SparseBufferRewriting.cpp.
Referenced by createPartitionFunc().
kPartitionFuncNamePrefix
constexpr const char kPartitionFuncNamePrefix[] = "_sparse_partition_" static
Definition at line 38 of file SparseBufferRewriting.cpp.
Referenced by createSortNonstableFunc().
kSortNonstableFuncNamePrefix
constexpr const char kSortNonstableFuncNamePrefix[] static
Initial value:
=
    "_sparse_sort_nonstable_"
Definition at line 41 of file SparseBufferRewriting.cpp.
Referenced by createSortStableFunc().
kSortStableFuncNamePrefix
constexpr const char kSortStableFuncNamePrefix[] static
Initial value:
=
    "_sparse_sort_stable_"
Definition at line 43 of file SparseBufferRewriting.cpp.
Referenced by createSortStableFunc().
loIdx
constexpr uint64_t loIdx = 0 static
Definition at line 32 of file SparseBufferRewriting.cpp.
Referenced by createBinarySearchFunc(), createPartitionFunc(), createSortNonstableFunc(), and createSortStableFunc().
xStartIdx
constexpr uint64_t xStartIdx = 2 static
Definition at line 34 of file SparseBufferRewriting.cpp.
Referenced by createBinarySearchFunc(), createLessThanFunc(), createMaySwapFunc(), createPartitionFunc(), createSortNonstableFunc(), createSortStableFunc(), and getMangledSortHelperFuncName().