MLIR: lib/Dialect/SparseTensor/Pipelines/SparseTensorPipelines.cpp File Reference
SparseTensorPipelines.cpp File Reference
#include "mlir/Dialect/SparseTensor/Pipelines/Passes.h"
#include "mlir/Conversion/Passes.h"
#include "mlir/Dialect/Arith/Transforms/Passes.h"
#include "mlir/Dialect/Bufferization/Transforms/Bufferize.h"
#include "mlir/Dialect/Bufferization/Transforms/OneShotAnalysis.h"
#include "mlir/Dialect/Bufferization/Transforms/Passes.h"
#include "mlir/Dialect/Func/IR/FuncOps.h"
#include "mlir/Dialect/Linalg/Passes.h"
#include "mlir/Dialect/SparseTensor/IR/SparseTensor.h"
#include "mlir/Dialect/SparseTensor/Transforms/Passes.h"
#include "mlir/Pass/PassManager.h"
#include "mlir/Transforms/Passes.h"
Functions
static bufferization::OneShotBufferizationOptions getBufferizationOptions (bool analysisOnly)
Return configuration options for One-Shot Bufferize.
Function Documentation
getBufferizationOptions()
static bufferization::OneShotBufferizationOptions getBufferizationOptions (bool analysisOnly) static
Return configuration options for One-Shot Bufferize.
Definition at line 28 of file SparseTensorPipelines.cpp.
References mlir::Type::cast(), mlir::bufferization::getMemRefTypeWithStaticIdentityLayout(), mlir::Value::getType(), options, and value.
Referenced by mlir::sparse_tensor::buildSparseCompiler().