MLIR: lib/Dialect/SparseTensor/Transforms/SparseTensorRewriting.cpp File Reference
SparseTensorRewriting.cpp File Reference
#include "CodegenUtils.h"
#include "mlir/Dialect/Arith/IR/Arith.h"
#include "mlir/Dialect/Bufferization/IR/Bufferization.h"
#include "mlir/Dialect/Linalg/IR/Linalg.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/Dialect/SCF/IR/SCF.h"
#include "mlir/Dialect/SparseTensor/IR/SparseTensor.h"
#include "mlir/Dialect/SparseTensor/Transforms/Passes.h"
#include "mlir/Dialect/Tensor/IR/Tensor.h"
#include "mlir/IR/AffineMap.h"
#include "mlir/IR/Matchers.h"
#include "mlir/Support/LLVM.h"
Functions
static bool isZeroValue (Value val)
static bool isSparseTensor (OpOperand *op)
static bool isAlloc (OpOperand *op, bool isZero)
static bool isSampling (GenericOp op)
static bool isMulChain (Value val, Value x)
static bool isSumOfMul (GenericOp op)
static bool isZeroYield (GenericOp op)
static void sizesForTensor (OpBuilder &builder, SmallVector< Value, 4 > &sizes, Location loc, ShapedType stp, Value tensor)
Populates given sizes array from type (for static sizes) and from the tensor (for dynamic sizes).
static RankedTensorType getUnorderedCOOFromType (RankedTensorType src)
static void getDynamicSizes (RankedTensorType tp, const SmallVectorImpl< Value > &sizes, SmallVectorImpl< Value > &dynSizes)
Collects the dynamic dimension sizes for tp with the assumption that sizes are the dimension sizes for the type.
Function Documentation
getDynamicSizes()
static void getDynamicSizes (RankedTensorType tp, const SmallVectorImpl< Value > & sizes, SmallVectorImpl< Value > & dynSizes) static
Collects the dynamic dimension sizes for tp with the assumption that sizes are the dimension sizes for the type.
Stores the dynamic dimension sizes to dynSizes.
Definition at line 161 of file SparseTensorRewriting.cpp.
References mlir::Block::addArgument(), mlir::sparse_tensor::allocDenseTensor(), mlir::Block::back(), mlir::Attribute::cast(), mlir::Type::cast(), mlir::OpBuilder::clone(), mlir::sparse_tensor::constantIndex(), mlir::sparse_tensor::constantZero(), mlir::OpBuilder::create(), mlir::sparse_tensor::createFuncCall(), mlir::detail::enumerate(), mlir::RewriterBase::eraseOp(), mlir::failure(), mlir::Block::front(), mlir::sparse_tensor::genAlloca(), mlir::sparse_tensor::genAllocaScalar(), mlir::sparse_tensor::genDenseTensorOrSparseConstantIterLoop(), mlir::sparse_tensor::genReshapeDstShape(), mlir::Builder::getAffineMapArrayAttr(), mlir::Block::getArgument(), mlir::Value::getDefiningOp(), mlir::sparse_tensor::getFunc(), mlir::Builder::getIndexAttr(), mlir::sparse_tensor::getIndexOverheadType(), mlir::Builder::getIndexType(), mlir::OpBuilder::getInsertionPoint(), mlir::BlockArgument::getLoc(), mlir::sparse_tensor::getOpaquePointerType(), mlir::Operation::getOperand(), mlir::sparse_tensor::getPointerOverheadType(), mlir::Operation::getResult(), getShape(), mlir::sparse_tensor::getSparseTensorEncoding(), mlir::Block::getTerminator(), mlir::Builder::getType(), mlir::Value::getType(), getUnorderedCOOFromType(), mlir::sparse_tensor::SparseTensorLoopEmitter::initializeLoopEmit(), isAlloc(), isSampling(), isSparseTensor(), isSumOfMul(), mlir::sparse_tensor::isUniqueCOOType(), isZeroYield(), mlir::BlockAndValueMapping::map(), mlir::RewriterBase::mergeBlockBefore(), NewOp, mlir::OpRewritePattern< SourceOp >::OpRewritePattern(), mlir::sparse_tensor::primaryTypeFunctionSuffix(), mlir::RewriterBase::replaceOp(), mlir::RewriterBase::replaceOpWithNewOp(), mlir::OpBuilder::setInsertionPointAfter(), mlir::OpBuilder::setInsertionPointAfterValue(), mlir::OpBuilder::setInsertionPointToStart(), mlir::Operation::setOperand(), sizesForTensor(), mlir::sparse_tensor::sizesFromSrc(), mlir::success(), mlir::sparse_tensor::toOrigDim(), mlir::sparse_tensor::toStoredDim(), mlir::sparse_tensor::translateIndicesArray(), mlir::RewriterBase::updateRootInPlace(), and value.
Referenced by isLastMemrefDimUnitStride(), joinShapes(), mlir::bufferization::populateDynamicDimSizes(), and mlir::transform::tileToForeachThreadOpImpl().
getUnorderedCOOFromType()
static RankedTensorType getUnorderedCOOFromType (RankedTensorType src) static
Definition at line 130 of file SparseTensorRewriting.cpp.
References mlir::AffineMap::getMultiDimIdentityMap(), and mlir::sparse_tensor::getSparseTensorEncoding().
Referenced by getDynamicSizes().
isAlloc()
static bool isAlloc (OpOperand * op, bool isZero) static
Definition at line 51 of file SparseTensorRewriting.cpp.
References copy(), mlir::IROperand< DerivedT, IRValueT >::get(), mlir::Value::getDefiningOp(), and isZeroValue().
Referenced by getDynamicSizes().
isMulChain()
static bool isMulChain (Value val, Value x) static
Definition at line 78 of file SparseTensorRewriting.cpp.
References mlir::Value::dyn_cast(), and mlir::Value::getDefiningOp().
Referenced by isSumOfMul().
isSampling()
static bool isSampling (GenericOp op) static
Definition at line 63 of file SparseTensorRewriting.cpp.
Referenced by getDynamicSizes().
isSparseTensor()
static bool isSparseTensor (OpOperand * op) static
Definition at line 42 of file SparseTensorRewriting.cpp.
References mlir::IROperand< DerivedT, IRValueT >::get(), mlir::sparse_tensor::getSparseTensorEncoding(), and mlir::Value::getType().
Referenced by getDynamicSizes().
isSumOfMul()
static bool isSumOfMul (GenericOp op) static
Definition at line 90 of file SparseTensorRewriting.cpp.
References isMulChain().
Referenced by getDynamicSizes().
isZeroValue()
static bool isZeroValue (Value val) static
Definition at line 37 of file SparseTensorRewriting.cpp.
References mlir::m_AnyZeroFloat(), mlir::m_Zero(), and mlir::matchPattern().
Referenced by isAlloc(), and isZeroYield().
isZeroYield()
static bool isZeroYield (GenericOp op) static
Definition at line 103 of file SparseTensorRewriting.cpp.
References isZeroValue().
Referenced by getDynamicSizes().
sizesForTensor()
static void sizesForTensor (OpBuilder & builder, SmallVector< Value, 4 > & sizes, Location loc, ShapedType stp, Value tensor) static
Populates given sizes array from type (for static sizes) and from the tensor (for dynamic sizes).
Definition at line 115 of file SparseTensorRewriting.cpp.
References mlir::sparse_tensor::constantIndex(), mlir::OpBuilder::create(), and mlir::detail::enumerate().
Referenced by getDynamicSizes().