MLIR: lib/Dialect/SPIRV/IR/SPIRVDialect.cpp File Reference
SPIRVDialect.cpp File Reference
#include "mlir/Dialect/SPIRV/IR/SPIRVDialect.h"
#include "mlir/Dialect/SPIRV/IR/ParserUtils.h"
#include "mlir/Dialect/SPIRV/IR/SPIRVOps.h"
#include "mlir/Dialect/SPIRV/IR/SPIRVTypes.h"
#include "mlir/Dialect/SPIRV/IR/TargetAndABI.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/DialectImplementation.h"
#include "mlir/IR/MLIRContext.h"
#include "mlir/Parser/Parser.h"
#include "mlir/Transforms/InliningUtils.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/Sequence.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/StringMap.h"
#include "llvm/ADT/TypeSwitch.h"
#include "llvm/Support/raw_ostream.h"
#include "mlir/Dialect/SPIRV/IR/SPIRVOpsDialect.cpp.inc"
#include "mlir/Dialect/SPIRV/IR/SPIRVOps.cpp.inc"
Macros
#define GET_OP_LIST
Functions
static bool containsReturn (Region &region)
Returns true if the given region contains spirv.Return or spirv.ReturnValue ops.
template<typename ValTy >
static Optional< ValTy > parseAndVerify (SPIRVDialect const &dialect, DialectAsmParser &parser)
template<>
Optional< Type > parseAndVerify< Type > (SPIRVDialect const &dialect, DialectAsmParser &parser)
template<>
Optional< unsigned > parseAndVerify< unsigned > (SPIRVDialect const &dialect, DialectAsmParser &parser)
static Type parseAndVerifyType (SPIRVDialect const &dialect, DialectAsmParser &parser)
static Type parseAndVerifyMatrixType (SPIRVDialect const &dialect, DialectAsmParser &parser)
static Type parseAndVerifySampledImageType (SPIRVDialect const &dialect, DialectAsmParser &parser)
static LogicalResult parseOptionalArrayStride (const SPIRVDialect &dialect, DialectAsmParser &parser, unsigned &stride)
Parses an optional , stride = N assembly segment.
static Type parseArrayType (SPIRVDialect const &dialect, DialectAsmParser &parser)
static Type parseCooperativeMatrixType (SPIRVDialect const &dialect, DialectAsmParser &parser)
static Type parseJointMatrixType (SPIRVDialect const &dialect, DialectAsmParser &parser)
static Type parsePointerType (SPIRVDialect const &dialect, DialectAsmParser &parser)
static Type parseRuntimeArrayType (SPIRVDialect const &dialect, DialectAsmParser &parser)
static Type parseMatrixType (SPIRVDialect const &dialect, DialectAsmParser &parser)
template<typename IntTy >
static Optional< IntTy > parseAndVerifyInteger (SPIRVDialect const &dialect, DialectAsmParser &parser)
static Type parseImageType (SPIRVDialect const &dialect, DialectAsmParser &parser)
static Type parseSampledImageType (SPIRVDialect const &dialect, DialectAsmParser &parser)
static ParseResult parseStructMemberDecorations (SPIRVDialect const &dialect, DialectAsmParser &parser, ArrayRef< Type > memberTypes, SmallVectorImpl< StructType::OffsetInfo > &offsetInfo, SmallVectorImpl< StructType::MemberDecorationInfo > &memberDecorationInfo)
static Type parseStructType (SPIRVDialect const &dialect, DialectAsmParser &parser)
static void print (ArrayType type, DialectAsmPrinter &os)
static void print (RuntimeArrayType type, DialectAsmPrinter &os)
static void print (PointerType type, DialectAsmPrinter &os)
static void print (ImageType type, DialectAsmPrinter &os)
static void print (SampledImageType type, DialectAsmPrinter &os)
static void print (StructType type, DialectAsmPrinter &os)
static void print (CooperativeMatrixNVType type, DialectAsmPrinter &os)
static void print (JointMatrixINTELType type, DialectAsmPrinter &os)
static void print (MatrixType type, DialectAsmPrinter &os)
static LogicalResult verifyRegionAttribute (Location loc, Type valueType, NamedAttribute attribute)
Verifies the given SPIR-V attribute attached to a value of the given valueType is valid.
Macro Definition Documentation
GET_OP_LIST
#define GET_OP_LIST
Function Documentation
containsReturn()
static bool containsReturn (Region & region) inline static
Returns true if the given region contains spirv.Return or spirv.ReturnValue ops.
Definition at line 43 of file SPIRVDialect.cpp.
References mlir::OpBuilder::create(), mlir::DialectInlinerInterface::DialectInlinerInterface(), mlir::Operation::erase(), mlir::Operation::getLoc(), mlir::Region::getParentOp(), mlir::Operation::getRegion(), mlir::Block::getTerminator(), isLegalToInline(), parseAndVerify(), parseAndVerify< Type >(), and parseAndVerify< unsigned >().
parseAndVerify()
template<typename ValTy > static Optional< ValTy > parseAndVerify (SPIRVDialect const & dialect, DialectAsmParser & parser) static
Definition at line 477 of file SPIRVDialect.cpp.
References mlir::AsmParser::emitError(), mlir::AsmParser::getCurrentLocation(), and mlir::AsmParser::parseKeyword().
Referenced by containsReturn().
parseAndVerify< Type >()
template<> Optional< Type > parseAndVerify< Type > (SPIRVDialect const & dialect, DialectAsmParser & parser)
Definition at line 492 of file SPIRVDialect.cpp.
References parseAndVerifyType().
Referenced by containsReturn().
parseAndVerify< unsigned >()
template<> Optional< unsigned > parseAndVerify< unsigned > (SPIRVDialect const & dialect, DialectAsmParser & parser)
Definition at line 511 of file SPIRVDialect.cpp.
References mlir::failed(), mlir::AsmParser::parseComma(), and value.
Referenced by containsReturn(), and parseOptionalArrayStride().
parseAndVerifyInteger()
template<typename IntTy > static Optional<IntTy> parseAndVerifyInteger (SPIRVDialect const & dialect, DialectAsmParser & parser) static
Definition at line 502 of file SPIRVDialect.cpp.
References max(), and mlir::AsmParser::parseInteger().
parseAndVerifyMatrixType()
static Type parseAndVerifyMatrixType (SPIRVDialect const & dialect, DialectAsmParser & parser) static
Definition at line 199 of file SPIRVDialect.cpp.
References mlir::Type::dyn_cast(), mlir::AsmParser::emitError(), mlir::AsmParser::getCurrentLocation(), and mlir::AsmParser::parseType().
Referenced by parseMatrixType().
parseAndVerifySampledImageType()
static Type parseAndVerifySampledImageType (SPIRVDialect const & dialect, DialectAsmParser & parser) static
Definition at line 235 of file SPIRVDialect.cpp.
References mlir::AsmParser::emitError(), mlir::AsmParser::getCurrentLocation(), mlir::Type::isa(), and mlir::AsmParser::parseType().
Referenced by parseSampledImageType().
parseAndVerifyType()
static Type parseAndVerifyType (SPIRVDialect const & dialect, DialectAsmParser & parser) static
Definition at line 155 of file SPIRVDialect.cpp.
References mlir::Type::dyn_cast(), mlir::AsmParser::emitError(), mlir::AsmParser::getCurrentLocation(), mlir::Type::getDialect(), mlir::Type::isBF16(), mlir::spirv::ScalarType::isValid(), and mlir::AsmParser::parseType().
Referenced by parseAndVerify< Type >(), parseArrayType(), parseCooperativeMatrixType(), parseJointMatrixType(), parsePointerType(), and parseRuntimeArrayType().
parseArrayType()
static Type parseArrayType (SPIRVDialect const & dialect, DialectAsmParser & parser) static
Definition at line 285 of file SPIRVDialect.cpp.
References mlir::AsmParser::emitError(), mlir::failed(), mlir::spirv::ArrayType::get(), mlir::AsmParser::getCurrentLocation(), parseAndVerifyType(), mlir::AsmParser::parseDimensionList(), mlir::AsmParser::parseGreater(), mlir::AsmParser::parseLess(), and parseOptionalArrayStride().
Referenced by parseStructType().
parseCooperativeMatrixType()
static Type parseCooperativeMatrixType (SPIRVDialect const & dialect, DialectAsmParser & parser) static
Definition at line 324 of file SPIRVDialect.cpp.
References mlir::AsmParser::emitError(), mlir::spirv::CooperativeMatrixNVType::get(), mlir::AsmParser::getCurrentLocation(), parseAndVerifyType(), mlir::AsmParser::parseComma(), mlir::AsmParser::parseDimensionList(), mlir::parseEnumKeywordAttr(), mlir::AsmParser::parseGreater(), and mlir::AsmParser::parseLess().
Referenced by parseStructType().
parseImageType()
static Type parseImageType (SPIRVDialect const & dialect, DialectAsmParser & parser) static
Definition at line 568 of file SPIRVDialect.cpp.
References mlir::spirv::ImageType::get(), mlir::AsmParser::parseGreater(), mlir::AsmParser::parseLess(), and value.
Referenced by parseStructType().
parseJointMatrixType()
static Type parseJointMatrixType (SPIRVDialect const & dialect, DialectAsmParser & parser) static
Definition at line 355 of file SPIRVDialect.cpp.
References mlir::AsmParser::emitError(), mlir::spirv::JointMatrixINTELType::get(), mlir::AsmParser::getCurrentLocation(), parseAndVerifyType(), mlir::AsmParser::parseComma(), mlir::AsmParser::parseDimensionList(), mlir::parseEnumKeywordAttr(), mlir::AsmParser::parseGreater(), and mlir::AsmParser::parseLess().
Referenced by parseStructType().
parseMatrixType()
static Type parseMatrixType (SPIRVDialect const & dialect, DialectAsmParser & parser) static
Definition at line 441 of file SPIRVDialect.cpp.
References mlir::AsmParser::emitError(), mlir::spirv::MatrixType::get(), mlir::AsmParser::getCurrentLocation(), parseAndVerifyMatrixType(), mlir::AsmParser::parseDimensionList(), mlir::AsmParser::parseGreater(), and mlir::AsmParser::parseLess().
Referenced by parseStructType().
parseOptionalArrayStride()
static LogicalResult parseOptionalArrayStride (const SPIRVDialect & dialect, DialectAsmParser & parser, unsigned & stride) static
Parses an optional , stride = N assembly segment.
If no parsing failure occurs, writes N to stride if existing and writes 0 to stride if missing.
Definition at line 255 of file SPIRVDialect.cpp.
References mlir::AsmParser::emitError(), mlir::failed(), mlir::failure(), mlir::AsmParser::getCurrentLocation(), parseAndVerify< unsigned >(), mlir::AsmParser::parseEqual(), mlir::AsmParser::parseKeyword(), mlir::AsmParser::parseOptionalComma(), and mlir::success().
Referenced by parseArrayType(), and parseRuntimeArrayType().
parsePointerType()
static Type parsePointerType (SPIRVDialect const & dialect, DialectAsmParser & parser) static
Definition at line 395 of file SPIRVDialect.cpp.
References mlir::AsmParser::emitError(), mlir::spirv::PointerType::get(), mlir::AsmParser::getCurrentLocation(), parseAndVerifyType(), mlir::AsmParser::parseComma(), mlir::AsmParser::parseGreater(), mlir::AsmParser::parseKeyword(), and mlir::AsmParser::parseLess().
Referenced by parseStructType().
parseRuntimeArrayType()
static Type parseRuntimeArrayType (SPIRVDialect const & dialect, DialectAsmParser & parser) static
Definition at line 422 of file SPIRVDialect.cpp.
References mlir::failed(), mlir::spirv::RuntimeArrayType::get(), parseAndVerifyType(), mlir::AsmParser::parseGreater(), mlir::AsmParser::parseLess(), and parseOptionalArrayStride().
Referenced by parseStructType().
parseSampledImageType()
static Type parseSampledImageType (SPIRVDialect const & dialect, DialectAsmParser & parser) static
Definition at line 586 of file SPIRVDialect.cpp.
References mlir::spirv::SampledImageType::get(), parseAndVerifySampledImageType(), mlir::AsmParser::parseGreater(), and mlir::AsmParser::parseLess().
Referenced by parseStructType().
parseStructMemberDecorations()
static ParseResult parseStructMemberDecorations (SPIRVDialect const & dialect, DialectAsmParser & parser, ArrayRef< Type > memberTypes, SmallVectorImpl< StructType::OffsetInfo > & offsetInfo, SmallVectorImpl< StructType::MemberDecorationInfo > & memberDecorationInfo) static
Definition at line 601 of file SPIRVDialect.cpp.
References mlir::AsmParser::emitError(), mlir::failed(), mlir::failure(), mlir::AsmParser::getCurrentLocation(), mlir::OptionalParseResult::has_value(), mlir::AsmParser::parseComma(), mlir::AsmParser::parseCommaSeparatedList(), mlir::AsmParser::parseOptionalEqual(), mlir::AsmParser::parseOptionalInteger(), mlir::AsmParser::parseOptionalRSquare(), mlir::AsmParser::parseRSquare(), mlir::succeeded(), and mlir::success().
Referenced by parseStructType().
parseStructType()
static Type parseStructType (SPIRVDialect const & dialect, DialectAsmParser & parser) static
Definition at line 668 of file SPIRVDialect.cpp.
References mlir::AsmParser::emitError(), mlir::failed(), mlir::spirv::StructType::get(), mlir::spirv::StructType::getEmpty(), mlir::spirv::StructType::getIdentified(), mlir::AsmParser::getNameLoc(), parseArrayType(), mlir::AsmParser::parseComma(), parseCooperativeMatrixType(), mlir::AsmParser::parseGreater(), parseImageType(), parseJointMatrixType(), mlir::AsmParser::parseKeyword(), mlir::AsmParser::parseLess(), mlir::AsmParser::parseLParen(), parseMatrixType(), mlir::AsmParser::parseOptionalComma(), mlir::AsmParser::parseOptionalGreater(), mlir::AsmParser::parseOptionalKeyword(), mlir::AsmParser::parseOptionalLSquare(), mlir::AsmParser::parseOptionalRParen(), parsePointerType(), mlir::AsmParser::parseRParen(), parseRuntimeArrayType(), parseSampledImageType(), parseStructMemberDecorations(), mlir::parseType(), mlir::AsmParser::parseType(), and mlir::succeeded().
print() [1/9]
static void print (ArrayType type, DialectAsmPrinter & os) static
Definition at line 813 of file SPIRVDialect.cpp.
References mlir::spirv::ArrayType::getArrayStride(), mlir::spirv::ArrayType::getElementType(), and mlir::spirv::ArrayType::getNumElements().
Referenced by print().
print() [2/9]
static void print (RuntimeArrayType type, DialectAsmPrinter & os) static
Definition at line 820 of file SPIRVDialect.cpp.
References mlir::spirv::RuntimeArrayType::getArrayStride(), and mlir::spirv::RuntimeArrayType::getElementType().
print() [3/9]
static void print (PointerType type, DialectAsmPrinter & os) static
Definition at line 827 of file SPIRVDialect.cpp.
References mlir::spirv::PointerType::getPointeeType(), and mlir::spirv::PointerType::getStorageClass().
print() [4/9]
static void print (ImageType type, DialectAsmPrinter & os) static
Definition at line 832 of file SPIRVDialect.cpp.
References mlir::spirv::ImageType::getArrayedInfo(), mlir::spirv::ImageType::getDepthInfo(), mlir::spirv::ImageType::getDim(), mlir::spirv::ImageType::getElementType(), mlir::spirv::ImageType::getImageFormat(), mlir::spirv::ImageType::getSamplerUseInfo(), and mlir::spirv::ImageType::getSamplingInfo().
print() [5/9]
static void print (SampledImageType type, DialectAsmPrinter & os) static
Definition at line 841 of file SPIRVDialect.cpp.
References mlir::spirv::SampledImageType::getImageType().
print() [6/9]
static void print (StructType type, DialectAsmPrinter & os) static
Definition at line 845 of file SPIRVDialect.cpp.
References mlir::spirv::StructType::getElementType(), mlir::spirv::StructType::getIdentifier(), mlir::spirv::StructType::getMemberDecorations(), mlir::spirv::StructType::getMemberOffset(), mlir::spirv::StructType::getNumElements(), mlir::spirv::StructType::hasOffset(), and mlir::spirv::StructType::isIdentified().
print() [7/9]
static void print (CooperativeMatrixNVType type, DialectAsmPrinter & os) static
Definition at line 893 of file SPIRVDialect.cpp.
References mlir::spirv::CooperativeMatrixNVType::getColumns(), mlir::spirv::CooperativeMatrixNVType::getElementType(), mlir::spirv::CooperativeMatrixNVType::getRows(), and mlir::spirv::CooperativeMatrixNVType::getScope().
print() [8/9]
static void print (JointMatrixINTELType type, DialectAsmPrinter & os) static
Definition at line 899 of file SPIRVDialect.cpp.
References mlir::spirv::JointMatrixINTELType::getColumns(), mlir::spirv::JointMatrixINTELType::getElementType(), mlir::spirv::JointMatrixINTELType::getMatrixLayout(), mlir::spirv::JointMatrixINTELType::getRows(), and mlir::spirv::JointMatrixINTELType::getScope().
print() [9/9]
static void print (MatrixType type, DialectAsmPrinter & os) static
Definition at line 906 of file SPIRVDialect.cpp.
References mlir::OpBuilder::create(), mlir::Operation::emitError(), mlir::spirv::MatrixType::getColumnType(), mlir::spirv::getEntryPointABIAttrName(), mlir::NamedAttribute::getName(), mlir::spirv::MatrixType::getNumColumns(), mlir::spirv::getTargetEnvAttrName(), mlir::NamedAttribute::getValue(), mlir::Attribute::isa(), materializeConstant(), print(), mlir::LLVM::detail::printType(), mlir::success(), and value.
verifyRegionAttribute()
static LogicalResult verifyRegionAttribute (Location loc, Type valueType, NamedAttribute attribute) static
Verifies the given SPIR-V attribute attached to a value of the given valueType is valid.
Definition at line 959 of file SPIRVDialect.cpp.
References mlir::Attribute::dyn_cast(), mlir::emitError(), mlir::Operation::emitError(), mlir::Region::getArgument(), mlir::spirv::getInterfaceVarABIAttrName(), mlir::Operation::getLoc(), mlir::NamedAttribute::getName(), mlir::Operation::getRegion(), mlir::Value::getType(), mlir::NamedAttribute::getValue(), mlir::Type::isIntOrIndexOrFloat(), and mlir::success().