MLIR: lib/Dialect/SPIRV/IR/SPIRVAttributes.cpp File Reference
SPIRVAttributes.cpp File Reference
#include "mlir/Dialect/SPIRV/IR/SPIRVAttributes.h"
#include "mlir/Dialect/SPIRV/IR/SPIRVDialect.h"
#include "mlir/Dialect/SPIRV/IR/SPIRVTypes.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/DialectImplementation.h"
#include "llvm/ADT/TypeSwitch.h"
#include "mlir/Dialect/SPIRV/IR/SPIRVAttrUtils.inc"
#include "mlir/Dialect/SPIRV/IR/SPIRVAttributes.cpp.inc"
Classes
struct mlir::spirv::detail::InterfaceVarABIAttributeStorage
struct mlir::spirv::detail::VerCapExtAttributeStorage
struct mlir::spirv::detail::TargetEnvAttributeStorage
Namespaces
mlir
Include the generated interface declarations.
mlir::spirv
mlir::spirv::detail
Macros
#define GET_ATTRDEF_CLASSES
#define GET_ATTRDEF_LIST
Functions
static ParseResult parseKeywordList (DialectAsmParser &parser, function_ref< LogicalResult(SMLoc, StringRef)> processKeyword)
Parses a comma-separated list of keywords, invokes processKeyword on each of the parsed keyword, and returns failure if any error occurs.
static Attribute parseInterfaceVarABIAttr (DialectAsmParser &parser)
Parses a spirv::InterfaceVarABIAttr.
static Attribute parseVerCapExtAttr (DialectAsmParser &parser)
static Attribute parseTargetEnvAttr (DialectAsmParser &parser)
Parses a spirv::TargetEnvAttr.
static void print (spirv::VerCapExtAttr triple, DialectAsmPrinter &printer)
static void print (spirv::TargetEnvAttr targetEnv, DialectAsmPrinter &printer)
static void print (spirv::InterfaceVarABIAttr interfaceVarABIAttr, DialectAsmPrinter &printer)
Macro Definition Documentation
GET_ATTRDEF_CLASSES
#define GET_ATTRDEF_CLASSES
Definition at line 341 of file SPIRVAttributes.cpp.
GET_ATTRDEF_LIST
#define GET_ATTRDEF_LIST
Function Documentation
parseInterfaceVarABIAttr()
static Attribute parseInterfaceVarABIAttr (DialectAsmParser & parser) static
Parses a spirv::InterfaceVarABIAttr.
Definition at line 375 of file SPIRVAttributes.cpp.
References mlir::AsmParser::emitError(), mlir::failed(), mlir::spirv::InterfaceVarABIAttr::get(), mlir::AsmParser::getBuilder(), mlir::AsmParser::getCurrentLocation(), mlir::Builder::getI32IntegerAttr(), mlir::AsmParser::parseComma(), mlir::AsmParser::parseGreater(), mlir::AsmParser::parseKeyword(), mlir::AsmParser::parseLess(), mlir::AsmParser::parseLParen(), mlir::AsmParser::parseOptionalComma(), mlir::AsmParser::parseOptionalInteger(), mlir::AsmParser::parseRParen(), and mlir::succeeded().
Referenced by parseTargetEnvAttr().
parseKeywordList()
static ParseResult parseKeywordList (DialectAsmParser & parser, function_ref< LogicalResult(SMLoc, StringRef)> processKeyword) static
Parses a comma-separated list of keywords, invokes processKeyword on each of the parsed keyword, and returns failure if any error occurs.
Definition at line 351 of file SPIRVAttributes.cpp.
References mlir::failed(), mlir::failure(), mlir::AsmParser::parseCommaSeparatedList(), mlir::AsmParser::parseLSquare(), mlir::AsmParser::parseOptionalRSquare(), mlir::AsmParser::parseRSquare(), mlir::succeeded(), and mlir::success().
Referenced by parseVerCapExtAttr().
parseTargetEnvAttr()
static Attribute parseTargetEnvAttr (DialectAsmParser & parser) static
Parses a spirv::TargetEnvAttr.
Definition at line 518 of file SPIRVAttributes.cpp.
References mlir::AsmParser::emitError(), mlir::spirv::TargetEnvAttr::get(), mlir::AsmParser::getCurrentLocation(), mlir::spirv::InterfaceVarABIAttr::getKindName(), mlir::spirv::VerCapExtAttr::getKindName(), mlir::spirv::TargetEnvAttr::getKindName(), mlir::AsmParser::getNameLoc(), mlir::OptionalParseResult::has_value(), mlir::spirv::TargetEnvAttr::kUnknownDeviceID, mlir::parseAttribute(), mlir::AsmParser::parseAttribute(), mlir::AsmParser::parseComma(), mlir::AsmParser::parseGreater(), mlir::AsmParser::parseInteger(), parseInterfaceVarABIAttr(), mlir::AsmParser::parseKeyword(), mlir::AsmParser::parseLess(), mlir::AsmParser::parseOptionalColon(), mlir::AsmParser::parseOptionalKeyword(), parseVerCapExtAttr(), and mlir::succeeded().
parseVerCapExtAttr()
static Attribute parseVerCapExtAttr (DialectAsmParser & parser) static
Definition at line 443 of file SPIRVAttributes.cpp.
References mlir::AsmParser::emitError(), mlir::failure(), mlir::spirv::VerCapExtAttr::get(), mlir::Builder::getArrayAttr(), mlir::AsmParser::getBuilder(), mlir::AsmParser::getCurrentLocation(), mlir::Builder::getI32IntegerAttr(), mlir::Builder::getStringAttr(), mlir::AsmParser::parseComma(), mlir::AsmParser::parseGreater(), mlir::AsmParser::parseKeyword(), parseKeywordList(), mlir::AsmParser::parseLess(), and mlir::success().
Referenced by parseTargetEnvAttr().
print() [1/3]
static void print (spirv::VerCapExtAttr triple, DialectAsmPrinter & printer) static
Definition at line 602 of file SPIRVAttributes.cpp.
References mlir::spirv::VerCapExtAttr::getCapabilities(), mlir::spirv::VerCapExtAttr::getExtensionsAttr(), mlir::spirv::VerCapExtAttr::getKindName(), mlir::AsmPrinter::getStream(), and mlir::spirv::VerCapExtAttr::getVersion().
Referenced by acceptBitWidth(), mlir::Diagnostic::append(), mlir::Op< AffineDmaStartOp, OpTrait::MemRefsNormalizable, OpTrait::VariadicOperands, OpTrait::ZeroResults, OpTrait::OpInvariants, AffineMapAccessInterface::Trait >::attachInterface(), buildGenericRegion(), buildIdentityRegion(), buildLLVMFunctionType(), mlir::scf::buildLoopNest(), mlir::pdl::PDLType::classof(), composeSetAndOperands(), computeMemRefRankReductionMask(), concatElemAndIndices(), mlir::createLoopFusionPass(), mlir::tblgen::DagLeaf::DagLeaf(), mlir::Attribute::dump(), mlir::AffineExpr::dump(), mlir::IntegerSet::dump(), mlir::presburger::PresburgerRelation::dump(), mlir::AffineMap::dump(), mlir::Type::dump(), mlir::OperationName::dump(), mlir::Value::dump(), mlir::Operation::dump(), mlir::Block::dump(), eachHasOnlyOneOfTypes(), mlir::CallGraph::end(), findDuplicateElement(), foldTransferInBoundsAttribute(), mlir::TimingIdentifier::get(), mlir::python::PyOperationBase::getAsm(), mlir::tblgen::Operator::getDialect(), mlir::pdll::ods::Context::getDialects(), mlir::scf::getForeachThreadOpThreadIndexOwner(), mlir::OperationName::getIdentifier(), mlir::pdll::ast::Type::getImpl(), getLoadStoreElementType(), mlir::pdll::ast::Node::getLoc(), getOption(), mlir::scf::getParallelForInductionVarOwner(), mlir::AnalysisState::getPoint(), mlir::Block::getSublistAccess(), mlir::GenericProgramPoint::getTypeID(), mlir::Value::getUsers(), hasOneBranchOpTo(), mlir::scf::insideMutuallyExclusiveBranches(), mlir::DynamicAttr::isa(), mlir::DynamicType::isa(), isComputeOperation(), isIntegerPtxType(), SelectToExtUI::matchAndRewrite(), CanonicalizeSingleResultAffineMinMaxOp< T >::matchAndRewrite(), mlir::tblgen::DagNode::operator bool(), mlir::AffineExpr::operator!(), mlir::IntegerSet::operator!=(), mlir::AffineMap::operator!=(), mlir::detail::PassOptions::ListOption< DataType, OptionParser >::operator*(), mlir::operator<<(), mlir::detail::PassOptions::Option< bool >::operator=(), mlir::detail::DenseArrayAttrImpl< int32_t >::operator[](), parentLLVMModule(), parseDstStyleOp(), parseGlobalMemrefOpTypeAndInitialValue(), llvm::cl::parser< mlir::OpPassManager >::parser(), parseTileLikeOp(), mlir::bufferization::populateDynamicDimSizes(), mlir::Attribute::print(), impl::MemRefDataPrinter< T >::print(), mlir::Type::print(), mlir::Value::print(), mlir::Operation::print(), mlir::Block::print(), print(), mlir::detail::DenseArrayAttrImpl< int32_t >::print(), printAccessChain(), printAttributions(), printAwaitResultType(), printBound(), printCreateOperationOpResults(), printDenseI64ArrayAttr(), impl::MemRefDataPrinter< T >::printFirst(), printInitializationList(), mlir::AsmPrinter::Impl::printIntegerSet(), impl::MemRefDataPrinter< T >::printLast(), printMemRefMetaData(), printMinMaxBound(), printNVVMIntrinsicOp(), mlir::detail::pass_options::printOptionValue(), mlir::raw_indented_ostream::printReindented(), printSizeAssignment(), printTransferAttrs(), mlir::ProgramPoint::ProgramPoint(), mlir::transform::TransformDialectExtension< DerivedTy, ExtraDialects >::registerPDLMatchConstraintFn(), mlir::replaceForOpWithNewYields(), replaceOpWithRegion(), mlir::presburger::DivisionRepr::setDiv(), mlir::DynamicOpDefinition::setPrintFn(), mlir::transform::tileToForeachThreadOpImpl(), verifyAllocLikeOp(), verifyAtomicCompareExchangeImpl(), verifyAttributions(), verifyConstantType(), verifyDimAndSymbolIdentifiers(), verifyGroupNonUniformShuffleOp(), verifyJointMatrixMad(), verifyMemoryOpIndexing(), verifyMemoryOpMetadata(), verifyPointerAndCoopMatrixType(), mlir::OpState::verifyRegions(), verifyVectorMemoryOp(), and mlir::DebugCounter::~DebugCounter().
print() [2/3]
static void print (spirv::TargetEnvAttr targetEnv, DialectAsmPrinter & printer) static
Definition at line 616 of file SPIRVAttributes.cpp.
References mlir::spirv::TargetEnvAttr::getDeviceID(), mlir::spirv::TargetEnvAttr::getDeviceType(), mlir::spirv::TargetEnvAttr::getKindName(), mlir::spirv::TargetEnvAttr::getResourceLimits(), mlir::spirv::TargetEnvAttr::getTripleAttr(), mlir::spirv::TargetEnvAttr::getVendorID(), mlir::spirv::TargetEnvAttr::kUnknownDeviceID, and print().
print() [3/3]
static void print (spirv::InterfaceVarABIAttr interfaceVarABIAttr, DialectAsmPrinter & printer) static
Definition at line 633 of file SPIRVAttributes.cpp.
References mlir::Attribute::dyn_cast(), mlir::spirv::InterfaceVarABIAttr::getBinding(), mlir::spirv::InterfaceVarABIAttr::getDescriptorSet(), mlir::spirv::InterfaceVarABIAttr::getKindName(), mlir::spirv::InterfaceVarABIAttr::getStorageClass(), print(), and mlir::succeeded().