MLIR: lib/Dialect/SPIRV/IR/SPIRVCanonicalization.cpp File Reference
SPIRVCanonicalization.cpp File Reference
#include <utility>
#include "mlir/Dialect/SPIRV/IR/SPIRVOps.h"
#include "mlir/Dialect/CommonFolders.h"
#include "mlir/Dialect/SPIRV/IR/SPIRVDialect.h"
#include "mlir/Dialect/SPIRV/IR/SPIRVTypes.h"
#include "mlir/IR/Matchers.h"
#include "mlir/IR/PatternMatch.h"
#include "SPIRVCanonicalization.inc"
Functions
static Optional< bool > getScalarOrSplatBoolAttr (Attribute attr)
Returns the boolean value under the hood if the given boolAttr is a scalar or splat vector bool constant.
static Attribute extractCompositeElement (Attribute composite, ArrayRef< unsigned > indices)
Function Documentation
extractCompositeElement()
static Attribute extractCompositeElement (Attribute composite, ArrayRef< unsigned > indices) static
Definition at line 45 of file SPIRVCanonicalization.cpp.
References mlir::RewritePatternSet::add(), mlir::Attribute::cast(), mlir::Attribute::dyn_cast(), mlir::failure(), getIndices(), mlir::Builder::getIntegerAttr(), mlir::m_One(), mlir::m_Zero(), mlir::matchPattern(), mlir::RewriterBase::replaceOpWithNewOp(), and mlir::success().
getScalarOrSplatBoolAttr()
static Optional<bool> getScalarOrSplatBoolAttr (Attribute attr) static
Returns the boolean value under the hood if the given boolAttr is a scalar or splat vector bool constant.
Definition at line 31 of file SPIRVCanonicalization.cpp.
References mlir::Attribute::dyn_cast().