MLIR: mlir::OpRewritePattern< SourceOp > Struct Template Reference
mlir::OpRewritePattern< SourceOp > Struct Template Reference
OpRewritePattern is a wrapper around RewritePattern that allows for matching and rewriting against an instance of a derived operation class as opposed to a raw Operation.
#include "mlir/IR/PatternMatch.h"
Public Member Functions
OpRewritePattern (MLIRContext *context, PatternBenefit benefit=1, ArrayRef< StringRef > generatedNames={})
Patterns must specify the root operation name they match against, and can also specify the benefit of the pattern matching and a list of generated ops.
Public Member Functions inherited from mlir::detail::OpOrInterfaceRewritePatternBase< SourceOp >
void rewrite (Operation *op, PatternRewriter &rewriter) const final
Wrappers around the RewritePattern methods that pass the derived op type.
LogicalResult match (Operation *op) const final
Attempt to match against code rooted at the specified operation, which is the same operation code as getRootKind().
LogicalResult matchAndRewrite (Operation *op, PatternRewriter &rewriter) const final
Attempt to match against code rooted at the specified operation, which is the same operation code as getRootKind().
virtual void rewrite (SourceOp op, PatternRewriter &rewriter) const
Rewrite and Match methods that operate on the SourceOp type.
virtual LogicalResult match (SourceOp op) const
virtual LogicalResult matchAndRewrite (SourceOp op, PatternRewriter &rewriter) const
Public Member Functions inherited from mlir::RewritePattern
virtual ~RewritePattern ()=default
Public Member Functions inherited from mlir::Pattern
ArrayRef< OperationName > getGeneratedOps () const
Return a list of operations that may be generated when rewriting an operation instance with this pattern.
Optional< OperationName > getRootKind () const
Return the root node that this pattern matches.
Optional< TypeID > getRootInterfaceID () const
Return the interface ID used to match the root operation of this pattern.
Optional< TypeID > getRootTraitID () const
Return the trait ID used to match the root operation of this pattern.
PatternBenefit getBenefit () const
Return the benefit (the inverse of "cost") of matching this pattern.
bool hasBoundedRewriteRecursion () const
Returns true if this pattern is known to result in recursive application, i.e.
MLIRContext * getContext () const
Return the MLIRContext used to create this pattern.
StringRef getDebugName () const
Return a readable name for this pattern.
void setDebugName (StringRef name)
Set the human readable debug name used for this pattern.
ArrayRef< StringRef > getDebugLabels () const
Return the set of debug labels attached to this pattern.
void addDebugLabels (ArrayRef< StringRef > labels)
Add the provided debug labels to this pattern.
void addDebugLabels (StringRef label)
Additional Inherited Members
Static Public Member Functions inherited from mlir::RewritePattern
template<typename T , typename... Args>
static std::unique_ptr< T > create (Args &&...args)
This method provides a convenient interface for creating and initializing derived rewrite patterns of the given type T.
Protected Member Functions inherited from mlir::Pattern
Pattern (StringRef rootName, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Construct a pattern with a certain benefit that matches the operation with the given root name.
Pattern (MatchAnyOpTypeTag tag, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Construct a pattern that may match any operation type.
Pattern (MatchInterfaceOpTypeTag tag, TypeID interfaceID, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Construct a pattern that may match any operation that implements the interface defined by the provided interfaceID.
Pattern (MatchTraitOpTypeTag tag, TypeID traitID, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Construct a pattern that may match any operation that implements the trait defined by the provided traitID.
void setHasBoundedRewriteRecursion (bool hasBoundedRecursionArg=true)
Set the flag detailing if this pattern has bounded rewrite recursion or not.
Detailed Description
template<typename SourceOp>
struct mlir::OpRewritePattern< SourceOp >
OpRewritePattern is a wrapper around RewritePattern that allows for matching and rewriting against an instance of a derived operation class as opposed to a raw Operation.
Definition at line 355 of file PatternMatch.h.
Constructor & Destructor Documentation
OpRewritePattern()
template<typename SourceOp> mlir::OpRewritePattern< SourceOp >::OpRewritePattern (MLIRContext * context, PatternBenefit benefit = 1, ArrayRef< StringRef > generatedNames = {}) inline
Patterns must specify the root operation name they match against, and can also specify the benefit of the pattern matching and a list of generated ops.
Definition at line 360 of file PatternMatch.h.
Referenced by createConst(), findAncestorOpInRegion(), foldExtractStridedOpFromInsertChain(), foldTransferInBoundsAttribute(), getAsValue(), getDimPosition(), getDynamicSizes(), mlir::vector::getVectorReductionOp(), insertCasts(), mlir::vector::isBroadcastableTo(), isLastMemrefDimUnitStride(), makeI64ArrayAttr(), printNamedStructuredOp(), and splatZero().
The documentation for this struct was generated from the following file:
include/mlir/IR/PatternMatch.h