MLIR: mlir::pdll::ast::Name Struct Reference
mlir::pdll::ast::Name Struct Reference
This class provides a convenient API for interacting with source names.
#include "mlir/Tools/PDLL/AST/Nodes.h"
Public Member Functions
StringRef getName () const
Return the raw string name.
SMRange getLoc () const
Get the location of this name.
Static Public Member Functions
static const Name & create (Context &ctx, StringRef name, SMRange location)
Detailed Description
This class provides a convenient API for interacting with source names.
It contains a string name as well as the source location for that name.
Definition at line 36 of file Nodes.h.
Member Function Documentation
create()
const Name & Name::create (Context & ctx, StringRef name, SMRange location) static
Definition at line 32 of file Nodes.cpp.
References copyStringWithNull(), mlir::pdll::ast::Context::getAllocator(), mlir::pdll::ast::CallExpr::getArguments(), mlir::pdll::ast::OperationExpr::getAttributes(), mlir::pdll::ast::UserConstraintDecl::getBody(), mlir::pdll::ast::PatternDecl::getBody(), mlir::pdll::ast::UserRewriteDecl::getBody(), mlir::pdll::ast::CallExpr::getCallableExpr(), mlir::pdll::ast::CompoundStmt::getChildren(), mlir::pdll::ast::Module::getChildren(), mlir::pdll::ast::VariableDecl::getConstraints(), mlir::pdll::ast::DeclRefExpr::getDecl(), mlir::pdll::ast::TupleExpr::getElements(), mlir::pdll::ast::VariableDecl::getInitExpr(), mlir::pdll::ast::UserConstraintDecl::getInputs(), mlir::pdll::ast::UserRewriteDecl::getInputs(), mlir::pdll::ast::OperationExpr::getNameDecl(), mlir::pdll::ast::OpConstraintDecl::getNameDecl(), mlir::pdll::ast::OperationExpr::getOperands(), mlir::pdll::ast::MemberAccessExpr::getParentExpr(), mlir::pdll::ast::ReplaceStmt::getReplExprs(), mlir::pdll::ast::ReturnStmt::getResultExpr(), mlir::pdll::ast::UserConstraintDecl::getResults(), mlir::pdll::ast::UserRewriteDecl::getResults(), mlir::pdll::ast::OperationExpr::getResultTypes(), mlir::pdll::ast::RewriteStmt::getRewriteBody(), mlir::pdll::ast::OpRewriteStmt::getRootOpExpr(), mlir::pdll::ast::AttrConstraintDecl::getTypeExpr(), mlir::pdll::ast::ValueConstraintDecl::getTypeExpr(), mlir::pdll::ast::ValueRangeConstraintDecl::getTypeExpr(), mlir::pdll::ast::NamedAttributeDecl::getValue(), mlir::pdll::ast::LetStmt::getVarDecl(), and visit().
Referenced by checkAndNestUnderRewriteOp().
getLoc()
SMRange mlir::pdll::ast::Name::getLoc () const inline
Get the location of this name.
Definition at line 43 of file Nodes.h.
Referenced by getDocumentationFor(), mlir::pdll::ast::OpNameDecl::getName(), mlir::pdll::ast::VariableDecl::getType(), mlir::pdll::ast::NamedAttributeDecl::getValue(), mlir::pdll::ast::UserConstraintDecl::isExternal(), and mlir::pdll::ast::UserRewriteDecl::isExternal().
getName()
StringRef mlir::pdll::ast::Name::getName () const inline
Return the raw string name.
Definition at line 40 of file Nodes.h.
Referenced by mlir::pdll::ast::DeclScope::add(), checkAndNestUnderRewriteOp(), getDocumentationFor(), mlir::pdll::ast::OpNameDecl::getName(), and shouldAddHintFor().
The documentation for this struct was generated from the following files:
include/mlir/Tools/PDLL/AST/Nodes.h
lib/Tools/PDLL/AST/Nodes.cpp