MLIR: lib/IR/SubElementInterfaces.cpp File Reference
SubElementInterfaces.cpp File Reference
#include "mlir/IR/SubElementInterfaces.h"
#include "llvm/ADT/DenseSet.h"
#include "mlir/IR/SubElementAttrInterfaces.cpp.inc"
#include "mlir/IR/SubElementTypeInterfaces.cpp.inc"
Functions
template<typename InterfaceT >
static void walkSubElementsImpl (InterfaceT interface, function_ref< void(Attribute)> walkAttrsFn, function_ref< void(Type)> walkTypesFn, DenseSet< Attribute > &visitedAttrs, DenseSet< Type > &visitedTypes)
template<typename InterfaceT , typename T , typename ReplaceSubElementFnT >
static void updateSubElementImpl (T element, function_ref< std::pair< T, WalkResult >(T)> walkFn, DenseMap< T, T > &visited, SmallVectorImpl< T > &newElements, FailureOr< bool > &changed, ReplaceSubElementFnT &&replaceSubElementFn)
template<typename InterfaceT >
static InterfaceT::ValueType replaceSubElementsImpl (InterfaceT interface, SubElementResultReplFn< Attribute > walkAttrsFn, SubElementResultReplFn< Type > walkTypesFn, DenseMap< Attribute, Attribute > &visitedAttrs, DenseMap< Type, Type > &visitedTypes)
Function Documentation
replaceSubElementsImpl()
template<typename InterfaceT > static InterfaceT::ValueType replaceSubElementsImpl (InterfaceT interface, SubElementResultReplFn< Attribute > walkAttrsFn, SubElementResultReplFn< Type > walkTypesFn, DenseMap< Attribute, Attribute > & visitedAttrs, DenseMap< Type, Type > & visitedTypes) static
Definition at line 151 of file SubElementInterfaces.cpp.
References mlir::failed().
updateSubElementImpl()
template<typename InterfaceT , typename T , typename ReplaceSubElementFnT > static void updateSubElementImpl (T element, function_ref< std::pair< T, WalkResult >(T)> walkFn, DenseMap< T, T > & visited, SmallVectorImpl< T > & newElements, FailureOr< bool > & changed, ReplaceSubElementFnT && replaceSubElementFn) static
Definition at line 97 of file SubElementInterfaces.cpp.
References mlir::WalkResult::advance(), mlir::failed(), mlir::failure(), mlir::WalkResult::wasInterrupted(), and mlir::WalkResult::wasSkipped().
walkSubElementsImpl()
template<typename InterfaceT > static void walkSubElementsImpl (InterfaceT interface, function_ref< void(Attribute)> walkAttrsFn, function_ref< void(Type)> walkTypesFn, DenseSet< Attribute > & visitedAttrs, DenseSet< Type > & visitedTypes) static
Definition at line 23 of file SubElementInterfaces.cpp.
References mlir::Attribute::dyn_cast(), and mlir::Attribute::hasTrait().