MLIR: lib/Tools/tblgen-lsp-server/TableGenServer.cpp File Reference
TableGenServer.cpp File Reference
#include "TableGenServer.h"
#include "../lsp-server-support/CompilationDatabase.h"
#include "../lsp-server-support/Logging.h"
#include "../lsp-server-support/Protocol.h"
#include "../lsp-server-support/SourceMgrUtils.h"
#include "mlir/Support/IndentedOstream.h"
#include "mlir/Support/LogicalResult.h"
#include "llvm/ADT/IntervalMap.h"
#include "llvm/ADT/PointerUnion.h"
#include "llvm/ADT/StringMap.h"
#include "llvm/ADT/StringSet.h"
#include "llvm/ADT/TypeSwitch.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/Path.h"
#include "llvm/TableGen/Parser.h"
#include "llvm/TableGen/Record.h"
Classes
struct mlir::lsp::TableGenServer::Impl
Functions
static lsp::URIForFile getURIFromLoc (const llvm::SourceMgr &mgr, SMLoc loc, const lsp::URIForFile &mainFileURI)
Returns a language server uri for the given source location.
static lsp::Location getLocationFromLoc (llvm::SourceMgr &mgr, SMRange loc, const lsp::URIForFile &uri)
Returns a language server location from the given source range.
static lsp::Location getLocationFromLoc (llvm::SourceMgr &mgr, SMLoc loc, const lsp::URIForFile &uri)
static Optional< lsp::Diagnostic > getLspDiagnoticFromDiag (const llvm::SMDiagnostic &diag, const lsp::URIForFile &uri)
Convert the given TableGen diagnostic to the LSP form.
static std::pair< const llvm::Record *, const llvm::RecordVal * > getBaseValue (const llvm::Record *record, const llvm::RecordVal *value)
Get the base definition of the given record value, or nullptr if one couldn't be found.
Function Documentation
getBaseValue()
static std::pair<const llvm::Record *, const llvm::RecordVal *> getBaseValue (const llvm::Record * record, const llvm::RecordVal * value) static
Get the base definition of the given record value, or nullptr if one couldn't be found.
Definition at line 100 of file TableGenServer.cpp.
References mlir::lsp::TextDocumentContentChangeEvent::applyTo(), mlir::lsp::contains(), mlir::lsp::Hover::contents, mlir::lsp::convertTokenLocToRange(), diag(), mlir::lsp::Logger::error(), mlir::lsp::extractSourceDocComment(), mlir::failed(), mlir::failure(), mlir::lsp::URIForFile::file(), mlir::lsp::gatherIncludeFiles(), mlir::lsp::Position::getAsSMLoc(), getLocationFromLoc(), getLspDiagnoticFromDiag(), mlir::raw_indented_ostream::printReindented(), mlir::success(), value, and mlir::lsp::MarkupContent::value.
getLocationFromLoc() [1/2]
static lsp::Location getLocationFromLoc (llvm::SourceMgr & mgr, SMRange loc, const lsp::URIForFile & uri) static
Returns a language server location from the given source range.
Definition at line 46 of file TableGenServer.cpp.
References getURIFromLoc().
Referenced by getBaseValue(), getLocationFromLoc(), and getLspDiagnoticFromDiag().
getLocationFromLoc() [2/2]
static lsp::Location getLocationFromLoc (llvm::SourceMgr & mgr, SMLoc loc, const lsp::URIForFile & uri) static
Definition at line 51 of file TableGenServer.cpp.
References mlir::lsp::convertTokenLocToRange(), and getLocationFromLoc().
getLspDiagnoticFromDiag()
static Optional<lsp::Diagnostic> getLspDiagnoticFromDiag (const llvm::SMDiagnostic & diag, const lsp::URIForFile & uri) static
Convert the given TableGen diagnostic to the LSP form.
Definition at line 58 of file TableGenServer.cpp.
References mlir::lsp::Diagnostic::category, mlir::lsp::Error, getLocationFromLoc(), mlir::lsp::Information, mlir::lsp::Diagnostic::message, mlir::lsp::Location::range, mlir::lsp::Diagnostic::range, mlir::lsp::Diagnostic::severity, mlir::lsp::Diagnostic::source, mlir::lsp::Location::uri, and mlir::lsp::Warning.
Referenced by getBaseValue().
getURIFromLoc()
static lsp::URIForFile getURIFromLoc (const llvm::SourceMgr & mgr, SMLoc loc, const lsp::URIForFile & mainFileURI) static
Returns a language server uri for the given source location.
mainFileURI corresponds to the uri for the main file of the source manager.
Definition at line 31 of file TableGenServer.cpp.
References mlir::lsp::Logger::error(), mlir::lsp::URIForFile::fromFile(), and toString().
Referenced by getLocationFromLoc().