MLIR: lib/Dialect/Linalg/Transforms/TilingInterfaceImpl.cpp File Reference
TilingInterfaceImpl.cpp File Reference
#include "mlir/Dialect/Linalg/Transforms/TilingInterfaceImpl.h"
#include "mlir/Analysis/SliceAnalysis.h"
#include "mlir/Dialect/Affine/IR/AffineOps.h"
#include "mlir/Dialect/Arith/IR/Arith.h"
#include "mlir/Dialect/Arith/Utils/Utils.h"
#include "mlir/Dialect/Linalg/IR/Linalg.h"
#include "mlir/Dialect/Linalg/Utils/Utils.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/Dialect/Tensor/IR/Tensor.h"
#include "mlir/Dialect/Utils/StaticValueUtils.h"
#include "mlir/Interfaces/TilingInterface.h"
#include "mlir/Dialect/Linalg/IR/LinalgStructuredOps.cpp.inc"
Macros
#define GET_OP_LIST
Functions
static SmallVector< Value > getIndicesForAccess (OpBuilder &b, Location loc, AffineMap indexingMap, ValueRange ivs)
Return the SSA values that represent the data point accessed using a given indexingMap for a given point in the iteration space represented by ivs.
static LogicalResult inlinePayload (OpBuilder &b, LinalgOp linalgOp, ValueRange ivs, ValueRange argValues)
Method to inline the payload of a linalgOp given the iteration space point and values for the arguments of the payload.
template<typename OpType >
static void registerOne (MLIRContext *ctx)
template<typename... OpTypes>
static void registerAll (MLIRContext *ctx)
Variadic helper function.
Macro Definition Documentation
GET_OP_LIST
#define GET_OP_LIST
Definition at line 416 of file TilingInterfaceImpl.cpp.
Function Documentation
getIndicesForAccess()
static SmallVector<Value> getIndicesForAccess (OpBuilder & b, Location loc, AffineMap indexingMap, ValueRange ivs) static
Return the SSA values that represent the data point accessed using a given indexingMap for a given point in the iteration space represented by ivs.
Definition at line 31 of file TilingInterfaceImpl.cpp.
References mlir::OpBuilder::create(), mlir::AffineMap::get(), mlir::AffineMap::getNumDims(), mlir::AffineMap::getNumResults(), mlir::AffineMap::getNumSymbols(), and mlir::AffineMap::getResults().
Referenced by inlinePayload().
inlinePayload()
static LogicalResult inlinePayload (OpBuilder & b, LinalgOp linalgOp, ValueRange ivs, ValueRange argValues) static
Method to inline the payload of a linalgOp given the iteration space point and values for the arguments of the payload.
Definition at line 47 of file TilingInterfaceImpl.cpp.
References mlir::bindDims(), mlir::Operation::clone(), mlir::OpBuilder::clone(), mlir::Region::cloneInto(), mlir::linalg::computeSliceParameters(), mlir::OpBuilder::create(), mlir::OpBuilder::createOrFold(), mlir::dispatchIndexOpFoldResults(), mlir::Operation::emitOpError(), mlir::detail::enumerate(), mlir::AffineMap::get(), mlir::IROperand< DerivedT, IRValueT >::get(), mlir::Builder::getAffineDimExpr(), mlir::Block::getArguments(), mlir::Builder::getContext(), mlir::Operation::getContext(), mlir::Builder::getIndexAttr(), getIndicesForAccess(), mlir::Operation::getLoc(), mlir::Builder::getMultiDimIdentityMap(), mlir::linalg::getNeutralElement(), mlir::AffineMap::getNumResults(), mlir::Operation::getOperands(), mlir::getParallelIteratorTypeName(), mlir::getReductionIteratorTypeName(), mlir::Operation::getRegion(), mlir::Operation::getResult(), mlir::AffineMap::getResults(), mlir::Operation::getResultTypes(), mlir::linalg::getTensorOutputTypes(), mlir::Block::getTerminator(), mlir::ValueRange::getType(), mlir::BlockAndValueMapping::lookupOrDefault(), mlir::makeComposedFoldedAffineApply(), mlir::linalg::makeTiledShapes(), mlir::BlockAndValueMapping::map(), mlir::matchReduction(), mlir::linalg::offsetIndices(), mlir::linalg::SliceParameters::offsets, mlir::OpBuilder::setInsertionPoint(), mlir::Operation::setOperand(), mlir::linalg::SliceParameters::sizes, mlir::success(), and mlir::Block::without_terminator().
registerAll()
template<typename... OpTypes> static void registerAll (MLIRContext * ctx) static
Variadic helper function.
Definition at line 412 of file TilingInterfaceImpl.cpp.
Referenced by mlir::linalg::registerTilingInterfaceExternalModels().
registerOne()
template<typename OpType > static void registerOne (MLIRContext * ctx) static
Definition at line 404 of file TilingInterfaceImpl.cpp.