MLIR: lib/Transforms/Utils/TopologicalSortUtils.cpp File Reference
TopologicalSortUtils.cpp File Reference
#include "mlir/Transforms/TopologicalSortUtils.h"
#include "mlir/IR/OpDefinition.h"
Functions
static bool isOpReady (Operation *op, DenseSet< Operation *> &unscheduledOps, function_ref< bool(Value, Operation *)> isOperandReady)
Return true if the given operation is ready to be scheduled.
Function Documentation
isOpReady()
static bool isOpReady (Operation * op, DenseSet< Operation *> & unscheduledOps, function_ref< bool(Value, Operation *)> isOperandReady) static
Return true if the given operation is ready to be scheduled.
Definition at line 15 of file TopologicalSortUtils.cpp.
References mlir::WalkResult::advance(), mlir::Operation::getOperands(), mlir::Operation::getParentOp(), mlir::WalkResult::interrupt(), value, mlir::Operation::walk(), and mlir::WalkResult::wasInterrupted().
Referenced by mlir::computeTopologicalSorting(), and mlir::sortTopologically().