MLIR: lib/Tools/mlir-translate/Translation.cpp File Reference
Translation.cpp File Reference
#include "mlir/Tools/mlir-translate/Translation.h"
#include "mlir/IR/AsmState.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/Dialect.h"
#include "mlir/IR/Verifier.h"
#include "mlir/Parser/Parser.h"
#include "mlir/Tools/ParseUtilities.h"
#include "llvm/Support/SourceMgr.h"
Classes
struct TranslationOptions
struct TranslationBundle
Functions
static llvm::StringMap< TranslationBundle > & getTranslationRegistry ()
Get the mutable static map between registered file-to-file MLIR translations and TranslateFunctions with its description that perform those translations.
static void registerTranslation (StringRef name, StringRef description, const TranslateFunction &function)
Register the given translation.
static void registerTranslateToMLIRFunction (StringRef name, StringRef description, const TranslateSourceMgrToMLIRFunction &function)
Variables
static llvm::ManagedStatic< TranslationOptions > clOptions
Function Documentation
getTranslationRegistry()
static llvm::StringMap<TranslationBundle>& getTranslationRegistry () static
Get the mutable static map between registered file-to-file MLIR translations and TranslateFunctions with its description that perform those translations.
Definition at line 50 of file Translation.cpp.
Referenced by registerTranslation(), and mlir::TranslationParser::TranslationParser().
registerTranslateToMLIRFunction()
static void registerTranslateToMLIRFunction (StringRef name, StringRef description, const TranslateSourceMgrToMLIRFunction & function) static
Definition at line 79 of file Translation.cpp.
References mlir::MLIRContext::appendDialectRegistry(), clOptions, mlir::failed(), mlir::failure(), mlir::OwningOpRef< OpTy >::get(), mlir::parseSourceFileForTool(), mlir::Operation::print(), registerTranslation(), mlir::success(), mlir::TranslateFromMLIRRegistration::TranslateFromMLIRRegistration(), mlir::TranslateToMLIRRegistration::TranslateToMLIRRegistration(), and mlir::verify().
registerTranslation()
static void registerTranslation (StringRef name, StringRef description, const TranslateFunction & function) static
Register the given translation.
Definition at line 56 of file Translation.cpp.
References getTranslationRegistry().
Referenced by registerTranslateToMLIRFunction(), and mlir::TranslateRegistration::TranslateRegistration().
Variable Documentation
clOptions
llvm::ManagedStatic<TranslationOptions> clOptions static
Definition at line 35 of file Translation.cpp.
Referenced by registerTranslateToMLIRFunction(), and mlir::registerTranslationCLOptions().