MLIR: lib/Dialect/Transform/IR/TransformOps.cpp File Reference
TransformOps.cpp File Reference
#include "mlir/Dialect/Transform/IR/TransformOps.h"
#include "mlir/Dialect/PDL/IR/PDLOps.h"
#include "mlir/Dialect/Transform/IR/TransformDialect.h"
#include "mlir/Dialect/Transform/IR/TransformInterfaces.h"
#include "mlir/Dialect/Transform/IR/TransformTypes.h"
#include "mlir/IR/OpImplementation.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/Interfaces/ControlFlowInterfaces.h"
#include "mlir/Rewrite/FrozenRewritePatternSet.h"
#include "mlir/Rewrite/PatternApplicator.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/ScopeExit.h"
#include "llvm/Support/Debug.h"
#include "mlir/Dialect/Transform/IR/TransformOps.cpp.inc"
Macros
#define DEBUG_TYPE "transform-dialect"
#define DBGS() (llvm::dbgs() << "[" DEBUG_TYPE "] ")
#define GET_OP_CLASSES
Functions
static void forwardTerminatorOperands (Block *block, transform::TransformState &state, transform::TransformResults &results)
static bool isValueUsePotentialConsumer (OpOperand &use)
Returns true if the given op operand may be consuming the handle value in the Transform IR.
LogicalResult checkDoubleConsume (Value value, function_ref< InFlightDiagnostic()> reportError)
Macro Definition Documentation
DBGS
#define DBGS () (llvm::dbgs() << "[" DEBUG_TYPE "] ")
Definition at line 24 of file TransformOps.cpp.
Referenced by forwardTerminatorOperands().
DEBUG_TYPE
#define DEBUG_TYPE "transform-dialect"
Definition at line 23 of file TransformOps.cpp.
GET_OP_CLASSES
#define GET_OP_CLASSES
Definition at line 28 of file TransformOps.cpp.
Function Documentation
checkDoubleConsume()
LogicalResult checkDoubleConsume (Value value, function_ref< InFlightDiagnostic()> reportError)
Definition at line 611 of file TransformOps.cpp.
References mlir::transform::TransformState::addExtension(), mlir::transform::TransformState::applyTransform(), mlir::InFlightDiagnostic::attachNote(), mlir::DiagnosedSilenceableFailure::definiteFailure(), diag(), mlir::failed(), mlir::failure(), mlir::SideEffects::Effect::Base< DerivedEffect, BaseEffect >::get(), mlir::Region::getArguments(), mlir::Operation::getLoc(), mlir::OpOperand::getOperandNumber(), mlir::Block::getOperations(), mlir::detail::IROperandBase::getOwner(), mlir::transform::TransformState::getPayloadOps(), mlir::transform::TransformState::getTopLevel(), mlir::Value::getUses(), isValueUsePotentialConsumer(), mlir::transform::TransformState::make_region_scope(), mlir::transform::onlyReadsHandle(), mlir::transform::onlyReadsPayload(), mlir::transform::TransformState::removeExtension(), mlir::DiagnosedSilenceableFailure::success(), mlir::success(), and mlir::verify().
forwardTerminatorOperands()
static void forwardTerminatorOperands (Block * block, transform::TransformState & state, transform::TransformResults & results) static
Definition at line 158 of file TransformOps.cpp.
References mlir::transform::TransformState::applyTransform(), mlir::DiagnosedSilenceableFailure::attachNote(), mlir::InFlightDiagnostic::attachNote(), mlir::Operation::clone(), mlir::transform::consumesHandle(), DBGS, mlir::DiagnosedSilenceableFailure::definiteFailure(), diag(), mlir::emitDefiniteFailure(), mlir::detail::enumerate(), mlir::failed(), mlir::Block::front(), mlir::Region::getArguments(), mlir::Operation::getBlock(), mlir::Value::getDefiningOp(), mlir::transform::TransformState::getExtension(), mlir::Operation::getLoc(), mlir::DiagnosedSilenceableFailure::getMessage(), mlir::Operation::getNumOperands(), mlir::Operation::getOperand(), mlir::Operation::getOperands(), mlir::Block::getOperations(), mlir::Operation::getOpResults(), mlir::Block::getParentOp(), mlir::Operation::getParentWithTrait(), mlir::transform::TransformState::getPayloadOps(), mlir::Operation::getResults(), mlir::Block::getTerminator(), mlir::transform::TransformState::getTopLevel(), mlir::OperandRange::getTypes(), mlir::DiagnosedSilenceableFailure::isDefiniteFailure(), mlir::transform::isHandleConsumed(), mlir::DiagnosedSilenceableFailure::isSilenceableFailure(), mlir::transform::TransformState::make_region_scope(), mlir::transform::TransformState::mapBlockArguments(), mlir::transform::onlyReadsHandle(), mlir::transform::onlyReadsPayload(), mlir::transform::producesHandle(), mlir::RewriterBase::replaceOp(), mlir::transform::TransformResults::set(), mlir::DiagnosedSilenceableFailure::silence(), mlir::DiagnosedSilenceableFailure::succeeded(), mlir::DiagnosedSilenceableFailure::success(), mlir::success(), and mlir::verify().
isValueUsePotentialConsumer()
static bool isValueUsePotentialConsumer (OpOperand & use) static
Returns true if the given op operand may be consuming the handle value in the Transform IR.
That is, if it may have a Free effect on it.
Definition at line 601 of file TransformOps.cpp.
References mlir::IROperand< DerivedT, IRValueT >::get(), mlir::detail::IROperandBase::getOwner(), and mlir::transform::isHandleConsumed().
Referenced by checkDoubleConsume().