MLIR: lib/Dialect/SPIRV/Transforms/UnifyAliasedResourcePass.cpp File Reference
UnifyAliasedResourcePass.cpp File Reference
#include "mlir/Dialect/SPIRV/Transforms/Passes.h"
#include "mlir/Dialect/SPIRV/IR/SPIRVDialect.h"
#include "mlir/Dialect/SPIRV/IR/SPIRVOps.h"
#include "mlir/Dialect/SPIRV/IR/SPIRVTypes.h"
#include "mlir/Dialect/SPIRV/IR/TargetAndABI.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/BuiltinAttributes.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/SymbolTable.h"
#include "mlir/Transforms/DialectConversion.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/Support/Debug.h"
#include <algorithm>
#include <iterator>
#include "mlir/Dialect/SPIRV/Transforms/Passes.h.inc"
Classes
class ConvertAliasResource< OpTy >
struct ConvertVariable
struct ConvertAddressOf
struct ConvertAccessChain
struct ConvertLoad
struct ConvertStore
Namespaces
mlir
Include the generated interface declarations.
mlir::spirv
Macros
#define GEN_PASS_DEF_SPIRVUNIFYALIASEDRESOURCEPASS
#define DEBUG_TYPE "spirv-unify-aliased-resource"
Typedefs
using Descriptor = std::pair< uint32_t, uint32_t >
using AliasedResourceMap = DenseMap< Descriptor, SmallVector< spirv::GlobalVariableOp > >
Functions
static AliasedResourceMap collectAliasedResources (spirv::ModuleOp moduleOp)
Collects all aliased resources in the given SPIR-V moduleOp.
static Type getRuntimeArrayElementType (Type type)
Returns the element type if the given type is a runtime array resource: !spirv.ptr<!spirv.struct<!spirv.rtarray<...>>>.
static Optional< int > deduceCanonicalResource (ArrayRef< spirv::SPIRVType > types)
Given a list of resource element types, returns the index of the canonical resource that all resources should be unified into.
static bool areSameBitwidthScalarType (Type a, Type b)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "spirv-unify-aliased-resource"
Definition at line 38 of file UnifyAliasedResourcePass.cpp.
GEN_PASS_DEF_SPIRVUNIFYALIASEDRESOURCEPASS
#define GEN_PASS_DEF_SPIRVUNIFYALIASEDRESOURCEPASS
Definition at line 33 of file UnifyAliasedResourcePass.cpp.
Typedef Documentation
AliasedResourceMap
using AliasedResourceMap = DenseMap<Descriptor, SmallVector<spirv::GlobalVariableOp> >
Definition at line 48 of file UnifyAliasedResourcePass.cpp.
Descriptor
using Descriptor = std::pair<uint32_t, uint32_t>
Definition at line 46 of file UnifyAliasedResourcePass.cpp.
Function Documentation
areSameBitwidthScalarType()
static bool areSameBitwidthScalarType (Type a, Type b) static
Definition at line 147 of file UnifyAliasedResourcePass.cpp.
References mlir::Type::cast(), collectAliasedResources(), deduceCanonicalResource(), mlir::detail::enumerate(), getElementType(), mlir::Type::getIntOrFloatBitWidth(), getRuntimeArrayElementType(), mlir::Type::isIntOrFloat(), mlir::SymbolTable::lookupSymbolIn(), and MLIR_DEFINE_EXPLICIT_INTERNAL_INLINE_TYPE_ID.
Referenced by ConvertAccessChain::matchAndRewrite(), ConvertLoad::matchAndRewrite(), and ConvertStore::matchAndRewrite().
collectAliasedResources()
static AliasedResourceMap collectAliasedResources (spirv::ModuleOp moduleOp) static
Collects all aliased resources in the given SPIR-V moduleOp.
Definition at line 51 of file UnifyAliasedResourcePass.cpp.
Referenced by areSameBitwidthScalarType(), and ConvertStore::matchAndRewrite().
deduceCanonicalResource()
static Optional<int> deduceCanonicalResource (ArrayRef< spirv::SPIRVType > types) static
Given a list of resource element types, returns the index of the canonical resource that all resources should be unified into.
Returns llvm::None if unable to unify.
Definition at line 87 of file UnifyAliasedResourcePass.cpp.
References mlir::Type::dyn_cast(), mlir::detail::enumerate(), mlir::Type::getIntOrFloatBitWidth(), mlir::spirv::SPIRVType::getSizeInBytes(), and mlir::spirv::SPIRVType::isScalarOrVector().
Referenced by areSameBitwidthScalarType().
getRuntimeArrayElementType()
static Type getRuntimeArrayElementType (Type type) static
Returns the element type if the given type is a runtime array resource: !spirv.ptr<!spirv.struct<!spirv.rtarray<...>>>.
Returns null type otherwise.
Definition at line 67 of file UnifyAliasedResourcePass.cpp.
References mlir::Type::dyn_cast(), mlir::spirv::RuntimeArrayType::getElementType(), mlir::spirv::StructType::getElementType(), and mlir::spirv::PointerType::getPointeeType().
Referenced by areSameBitwidthScalarType().