MLIR: lib/Dialect/Vector/Transforms/VectorDistribute.cpp File Reference
VectorDistribute.cpp File Reference
#include "mlir/Dialect/Affine/IR/AffineOps.h"
#include "mlir/Dialect/Arith/IR/Arith.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/Dialect/SCF/IR/SCF.h"
#include "mlir/Dialect/Vector/IR/VectorOps.h"
#include "mlir/Dialect/Vector/Transforms/VectorDistribution.h"
#include "mlir/IR/AffineExpr.h"
#include "mlir/Transforms/RegionUtils.h"
#include "mlir/Transforms/SideEffectUtils.h"
#include "llvm/ADT/SetVector.h"
#include <utility>
Functions
static AffineMap calculateImplicitMap (VectorType sequentialType, VectorType distributedType)
Currently the distribution map is implicit based on the vector shape.
static WarpExecuteOnLane0Op moveRegionToNewWarpOpAndReplaceReturns (RewriterBase &rewriter, WarpExecuteOnLane0Op warpOp, ValueRange newYieldedValues, TypeRange newReturnTypes)
Helper to create a new WarpExecuteOnLane0Op with different signature.
static WarpExecuteOnLane0Op moveRegionToNewWarpOpAndAppendReturns (RewriterBase &rewriter, WarpExecuteOnLane0Op warpOp, ValueRange newYieldedValues, TypeRange newReturnTypes, llvm::SmallVector< size_t > &indices)
Helper to create a new WarpExecuteOnLane0Op region with extra outputs.
static bool canBeHoisted (Operation *op, function_ref< bool(Value)> definedOutside)
Helper to know if an op can be hoisted out of the region.
static OpOperand * getWarpResult (WarpExecuteOnLane0Op warpOp, const std::function< bool(Operation *)> &fn)
Return a value yielded by warpOp which statifies the filter lamdba condition and is not dead.
static Operation * cloneOpWithOperandsAndTypes (RewriterBase &rewriter, Location loc, Operation *op, ArrayRef< Value > operands, ArrayRef< Type > resultTypes)
Function Documentation
calculateImplicitMap()
static AffineMap calculateImplicitMap (VectorType sequentialType, VectorType distributedType) static
Currently the distribution map is implicit based on the vector shape.
In the future it will be part of the op. Example:
%0 = vector.warp_execute_on_lane_0(%arg0) -> (vector<1x16x2xf32>) {
  ...
  vector.yield %3 : vector<32x16x64xf32>
}
Would have an implicit map of: (d0, d1, d2) -> (d0, d2)
Definition at line 35 of file VectorDistribute.cpp.
References mlir::Type::cast(), mlir::OpBuilder::create(), mlir::OpBuilder::createOrFold(), mlir::Type::dyn_cast(), mlir::AffineMap::get(), mlir::getAffineDimExpr(), mlir::getAffineSymbolExpr(), mlir::Builder::getContext(), mlir::Value::getType(), and mlir::Type::isa().
canBeHoisted()
static bool canBeHoisted (Operation * op, function_ref< bool(Value)> definedOutside) static
Helper to know if an op can be hoisted out of the region.
Definition at line 225 of file VectorDistribute.cpp.
References mlir::Operation::getNumRegions(), mlir::Operation::getOperands(), and mlir::isMemoryEffectFree().
Referenced by mlir::vector::populateWarpExecuteOnLane0OpToScfForPattern().
cloneOpWithOperandsAndTypes()
static Operation* cloneOpWithOperandsAndTypes (RewriterBase & rewriter, Location loc, Operation * op, ArrayRef< Value > operands, ArrayRef< Type > resultTypes) static
Definition at line 250 of file VectorDistribute.cpp.
getWarpResult()
static OpOperand* getWarpResult (WarpExecuteOnLane0Op warpOp, const std::function< bool(Operation *)> & fn) static
Return a value yielded by warpOp which statifies the filter lamdba condition and is not dead.
Definition at line 233 of file VectorDistribute.cpp.
References mlir::Value::getDefiningOp().
moveRegionToNewWarpOpAndAppendReturns()
static WarpExecuteOnLane0Op moveRegionToNewWarpOpAndAppendReturns (RewriterBase & rewriter, WarpExecuteOnLane0Op warpOp, ValueRange newYieldedValues, TypeRange newReturnTypes, llvm::SmallVector< size_t > & indices) static
Helper to create a new WarpExecuteOnLane0Op region with extra outputs.
indices return the index of each new output.
Definition at line 192 of file VectorDistribute.cpp.
References mlir::detail::enumerate(), moveRegionToNewWarpOpAndReplaceReturns(), and mlir::RewriterBase::replaceOp().
moveRegionToNewWarpOpAndReplaceReturns()
static WarpExecuteOnLane0Op moveRegionToNewWarpOpAndReplaceReturns (RewriterBase & rewriter, WarpExecuteOnLane0Op warpOp, ValueRange newYieldedValues, TypeRange newReturnTypes) static
Helper to create a new WarpExecuteOnLane0Op with different signature.
Definition at line 164 of file VectorDistribute.cpp.
References mlir::Region::begin(), mlir::OpBuilder::create(), mlir::RewriterBase::eraseBlock(), mlir::Region::front(), mlir::Region::getBlocks(), mlir::RewriterBase::inlineRegionBefore(), mlir::OpBuilder::setInsertionPoint(), and mlir::RewriterBase::updateRootInPlace().
Referenced by moveRegionToNewWarpOpAndAppendReturns().