MLIR: lib/Dialect/Vector/Transforms/VectorTransferOpTransforms.cpp File Reference
VectorTransferOpTransforms.cpp File Reference
#include "mlir/Dialect/Arith/IR/Arith.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/Dialect/Vector/IR/VectorOps.h"
#include "mlir/Dialect/Vector/Transforms/VectorTransforms.h"
#include "mlir/Dialect/Vector/Utils/VectorUtils.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/Dominance.h"
#include "mlir/Transforms/SideEffectUtils.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/Support/Debug.h"
Macros
#define DEBUG_TYPE "vector-transfer-opt"
#define DBGS() (llvm::dbgs() << '[' << DEBUG_TYPE << "] ")
Functions
static Operation * findAncestorOpInRegion (Region *region, Operation *op)
Return the ancestor op in the region or nullptr if the region is not an ancestor of the op.
Macro Definition Documentation
DBGS
#define DBGS () (llvm::dbgs() << '[' << DEBUG_TYPE << "] ")
Definition at line 28 of file VectorTransferOpTransforms.cpp.
Referenced by findAncestorOpInRegion().
DEBUG_TYPE
#define DEBUG_TYPE "vector-transfer-opt"
Definition at line 26 of file VectorTransferOpTransforms.cpp.
Function Documentation
findAncestorOpInRegion()
static Operation* findAncestorOpInRegion (Region * region, Operation * op) static
Return the ancestor op in the region or nullptr if the region is not an ancestor of the op.
Definition at line 34 of file VectorTransferOpTransforms.cpp.
References mlir::canonicalizeStridedLayout(), mlir::Type::cast(), mlir::vector::checkSameValueRAW(), mlir::vector::checkSameValueWAW(), mlir::OpBuilder::create(), DBGS, mlir::Type::dyn_cast(), mlir::Operation::erase(), mlir::RewriterBase::eraseOp(), mlir::failed(), mlir::failure(), mlir::AffineMap::get(), mlir::getAffineDimExpr(), mlir::Operation::getBlock(), mlir::Builder::getBoolArrayAttr(), mlir::Builder::getContext(), mlir::Value::getDefiningOp(), mlir::Builder::getMultiDimIdentityMap(), mlir::Operation::getParentOp(), mlir::Operation::getParentRegion(), mlir::Region::getParentRegion(), mlir::getStridesAndOffset(), mlir::Value::getType(), mlir::Value::getUsers(), mlir::vector::isDisjointTransferSet(), mlir::isMemoryEffectFree(), isZero(), mlir::OpRewritePattern< SourceOp >::OpRewritePattern(), mlir::RewriterBase::replaceOpWithNewOp(), mlir::Block::succ_begin(), mlir::Block::succ_end(), mlir::succeeded(), mlir::success(), and mlir::arith::ConstantIndexOp::value().