MLIR: lib/Dialect/Vector/Transforms/VectorTransforms.cpp File Reference
VectorTransforms.cpp File Reference
#include "mlir/Dialect/Vector/Transforms/VectorTransforms.h"
#include <type_traits>
#include "mlir/Dialect/Affine/IR/AffineOps.h"
#include "mlir/Dialect/Arith/IR/Arith.h"
#include "mlir/Dialect/Arith/Utils/Utils.h"
#include "mlir/Dialect/Linalg/IR/Linalg.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/Dialect/SCF/IR/SCF.h"
#include "mlir/Dialect/Utils/IndexingUtils.h"
#include "mlir/Dialect/Utils/StructuredOpsUtils.h"
#include "mlir/Dialect/Vector/IR/VectorOps.h"
#include "mlir/Dialect/Vector/Utils/VectorUtils.h"
#include "mlir/IR/BuiltinAttributeInterfaces.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/ImplicitLocOpBuilder.h"
#include "mlir/IR/Matchers.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/Interfaces/VectorInterfaces.h"
#include "llvm/ADT/DenseSet.h"
#include "llvm/ADT/MapVector.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
Classes
struct TransferReadToVectorLoadLowering
Progressive lowering of transfer_read.
struct VectorLoadToMemrefLoadLowering
Replace a 0-d vector.load with a memref.load + vector.broadcast.
struct VectorStoreToMemrefStoreLowering
Replace a 0-d vector.store with a vector.extractelement + memref.store.
struct TransferWriteToVectorStoreLowering
Progressive lowering of transfer_write.
struct BubbleDownVectorBitCastForExtract
struct BubbleDownBitCastForStridedSliceExtract
struct BubbleUpBitCastForStridedSliceInsert
struct MaterializeTransferMask< ConcreteOp >
class VectorCreateMaskOpConversion
Conversion pattern for a vector.create_mask (0-D and 1-D only).
class DropInnerMostUnitDims
Namespaces
mlir
Include the generated interface declarations.
Macros
#define DEBUG_TYPE "vector-to-vector"
Functions
static Optional< int64_t > getResultIndex (AffineMap map, int64_t index)
static SmallVector< Attribute, 4 > adjustIter (ArrayAttr iteratorTypes, int64_t index)
static AffineMap adjustMap (AffineMap map, int64_t index, PatternRewriter &rewriter)
static Value reshapeLoad (Location loc, Value val, VectorType type, int64_t index, int64_t pos, PatternRewriter &rewriter)
static Value reshapeStore (Location loc, Value val, Value result, VectorType type, int64_t index, int64_t pos, PatternRewriter &rewriter)
template<typename IntType >
static SmallVector< IntType, 4 > extractVector (ArrayAttr arrayAttr)
static Optional< Value > createContractArithOp (Location loc, Value x, Value y, Value acc, vector::CombiningKind kind, PatternRewriter &rewriter, bool isInt)
Helper to create arithmetic operation associated with a kind of contraction.
static SmallVector< int64_t > getReductionIndex (AffineMap map, ArrayAttr iteratorTypes)
Return the positions of the reductions in the given map.
static llvm::Optional< unsigned > getDimPosition (AffineMap map, unsigned dim)
Look for a given dimension in an affine map and return its position.
static Value createAdd (Location loc, Value x, Value y, bool isInt, PatternRewriter &rewriter)
Creates an AddIOp if isInt is true otherwise create an arith::AddFOp using operands x and y.
static Value createMul (Location loc, Value x, Value y, bool isInt, PatternRewriter &rewriter)
Creates a MulIOp if isInt is true otherwise create an MulFOp using operands x andy`.
static SmallVector< int64_t, 4 > getIntValueVector (ArrayAttr arrayAttr)
static Value buildVectorComparison (PatternRewriter &rewriter, Operation *op, bool force32BitVectorIndices, int64_t dim, Value b, Value *off=nullptr)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "vector-to-vector"
Definition at line 41 of file VectorTransforms.cpp.
Function Documentation
adjustIter()
static SmallVector<Attribute, 4> adjustIter (ArrayAttr iteratorTypes, int64_t index) static
Definition at line 57 of file VectorTransforms.cpp.
References mlir::detail::enumerate().
adjustMap()
static AffineMap adjustMap (AffineMap map, int64_t index, PatternRewriter & rewriter) static
Definition at line 70 of file VectorTransforms.cpp.
References mlir::AffineMap::get(), mlir::getAffineDimExpr(), mlir::Builder::getContext(), mlir::AffineMap::getDimPosition(), mlir::AffineMap::getNumDims(), and mlir::AffineMap::getNumResults().
buildVectorComparison()
static Value buildVectorComparison (PatternRewriter & rewriter, Operation * op, bool force32BitVectorIndices, int64_t dim, Value b, Value * off = nullptr) static
Definition at line 2549 of file VectorTransforms.cpp.
References mlir::OpBuilder::create(), mlir::DenseIntElementsAttr::get(), mlir::Builder::getI32Type(), mlir::Builder::getI32VectorAttr(), mlir::Builder::getI64Type(), mlir::Builder::getI64VectorAttr(), mlir::Operation::getLoc(), mlir::Value::getType(), and mlir::getValueOrCreateCastToIndexLike().
Referenced by VectorCreateMaskOpConversion::matchAndRewrite().
createAdd()
static Value createAdd (Location loc, Value x, Value y, bool isInt, PatternRewriter & rewriter) static
Creates an AddIOp if isInt is true otherwise create an arith::AddFOp using operands x and y.
Definition at line 1395 of file VectorTransforms.cpp.
References mlir::OpBuilder::create().
createContractArithOp()
static Optional<Value> createContractArithOp (Location loc, Value x, Value y, Value acc, vector::CombiningKind kind, PatternRewriter & rewriter, bool isInt) static
Helper to create arithmetic operation associated with a kind of contraction.
Definition at line 150 of file VectorTransforms.cpp.
createMul()
static Value createMul (Location loc, Value x, Value y, bool isInt, PatternRewriter & rewriter) static
Creates a MulIOp if isInt is true otherwise create an MulFOp using operands x andy`.
Definition at line 1404 of file VectorTransforms.cpp.
References mlir::OpBuilder::create().
extractVector()
template<typename IntType > static SmallVector<IntType, 4> extractVector (ArrayAttr arrayAttr) static
Definition at line 143 of file VectorTransforms.cpp.
getDimPosition()
static llvm::Optional<unsigned> getDimPosition (AffineMap map, unsigned dim) static
Look for a given dimension in an affine map and return its position.
Return llvm::None if the dimension is not in the map results.
Definition at line 194 of file VectorTransforms.cpp.
References mlir::applyPermutationToVector(), mlir::computeStrides(), mlir::OpBuilder::create(), mlir::delinearize(), mlir::failure(), mlir::vector::Flat, mlir::AffineMap::getDimPosition(), mlir::Builder::getI32IntegerAttr(), getNumElements(), mlir::AffineMap::getNumResults(), mlir::Builder::getZeroAttr(), mlir::vector::None, mlir::RewriterBase::notifyMatchFailure(), mlir::OpRewritePattern< SourceOp >::OpRewritePattern(), mlir::RewriterBase::replaceOp(), mlir::RewriterBase::replaceOpWithNewOp(), mlir::vector::Shuffle, mlir::success(), and mlir::vector::VectorTransformsOptions::vectorTransposeLowering.
Referenced by mlir::AffineMap::getPermutedPosition(), and mlir::AffineMap::operator!=().
getIntValueVector()
static SmallVector<int64_t, 4> getIntValueVector (ArrayAttr arrayAttr) static
Definition at line 2302 of file VectorTransforms.cpp.
Referenced by BubbleDownBitCastForStridedSliceExtract::matchAndRewrite(), and BubbleUpBitCastForStridedSliceInsert::matchAndRewrite().
getReductionIndex()
static SmallVector<int64_t> getReductionIndex (AffineMap map, ArrayAttr iteratorTypes) static
Return the positions of the reductions in the given map.
Definition at line 182 of file VectorTransforms.cpp.
References mlir::AffineMap::getDimPosition(), mlir::AffineMap::getNumResults(), and mlir::vector::isReductionIterator().
getResultIndex()
static Optional<int64_t> getResultIndex (AffineMap map, int64_t index) static
Definition at line 47 of file VectorTransforms.cpp.
References mlir::AffineMap::getDimPosition(), mlir::AffineMap::getNumResults(), and None.
reshapeLoad()
static Value reshapeLoad (Location loc, Value val, VectorType type, int64_t index, int64_t pos, PatternRewriter & rewriter) static
Definition at line 88 of file VectorTransforms.cpp.
References mlir::Type::cast(), mlir::OpBuilder::create(), mlir::VectorType::Builder::dropDim(), mlir::Builder::getI64ArrayAttr(), and mlir::Builder::getZeroAttr().
reshapeStore()
static Value reshapeStore (Location loc, Value val, Value result, VectorType type, int64_t index, int64_t pos, PatternRewriter & rewriter) static
Definition at line 117 of file VectorTransforms.cpp.
References mlir::OpBuilder::create(), mlir::VectorType::Builder::dropDim(), and mlir::Builder::getI64ArrayAttr().
Variable Documentation
strRef
StringRef strRef
Definition at line 1527 of file VectorTransforms.cpp.
Referenced by twineToStrRef().