MLIR: lib/Dialect/Vector/Transforms/VectorDropLeadUnitDim.cpp File Reference
VectorDropLeadUnitDim.cpp File Reference
#include "mlir/Dialect/Utils/StructuredOpsUtils.h"
#include "mlir/Dialect/Vector/IR/VectorOps.h"
#include "mlir/Dialect/Vector/Transforms/VectorRewritePatterns.h"
#include "mlir/Dialect/Vector/Utils/VectorUtils.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/ImplicitLocOpBuilder.h"
#include "mlir/IR/TypeUtilities.h"
Macros
#define DEBUG_TYPE "vector-drop-unit-dim"
Functions
static VectorType trimLeadingOneDims (VectorType oldType)
static SmallVector< int64_t > splatZero (int64_t rank)
Return a smallVector of size rank containing all zeros.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "vector-drop-unit-dim"
Definition at line 17 of file VectorDropLeadUnitDim.cpp.
Function Documentation
splatZero()
static SmallVector<int64_t> splatZero (int64_t rank) static
Return a smallVector of size rank containing all zeros.
Definition at line 35 of file VectorDropLeadUnitDim.cpp.
References mlir::Type::cast(), mlir::OpBuilder::create(), mlir::Type::dyn_cast(), mlir::detail::enumerate(), mlir::failure(), mlir::AffineMap::get(), mlir::Builder::getAffineDimExpr(), mlir::Builder::getAffineMapArrayAttr(), mlir::Builder::getArrayAttr(), mlir::Operation::getAttrs(), mlir::Builder::getContext(), mlir::Builder::getI64Type(), mlir::OperationName::getIdentifier(), mlir::Operation::getLoc(), mlir::Operation::getName(), mlir::AffineMap::getNumDims(), mlir::Operation::getNumResults(), mlir::AffineMap::getNumSymbols(), mlir::Operation::getOperands(), mlir::AffineMap::getPermutationMap(), mlir::Operation::getResult(), mlir::AffineMap::getResults(), mlir::Operation::getResultTypes(), mlir::Builder::getZeroAttr(), mlir::OpTrait::hasElementwiseMappableTraits(), mlir::vector::isParallelIterator(), mlir::OpRewritePattern< SourceOp >::OpRewritePattern(), mlir::RewriterBase::replaceOpWithNewOp(), mlir::success(), mlir::transform::detail::transposeResults(), and trimLeadingOneDims().
trimLeadingOneDims()
static VectorType trimLeadingOneDims (VectorType oldType) static
Definition at line 24 of file VectorDropLeadUnitDim.cpp.
Referenced by splatZero().