MLIR: lib/Conversion/GPUToSPIRV/WmmaOpsToSPIRV.cpp File Reference
WmmaOpsToSPIRV.cpp File Reference
#include "mlir/Conversion/GPUToSPIRV/GPUToSPIRV.h"
#include "mlir/Conversion/GPUToSPIRV/GPUToSPIRVPass.h"
#include "mlir/Dialect/GPU/IR/GPUDialect.h"
#include "mlir/Dialect/SPIRV/IR/SPIRVAttributes.h"
#include "mlir/Dialect/SPIRV/IR/SPIRVDialect.h"
#include "mlir/Dialect/SPIRV/IR/SPIRVEnums.h"
#include "mlir/Dialect/SPIRV/IR/SPIRVOps.h"
#include "mlir/Dialect/SPIRV/IR/TargetAndABI.h"
#include "mlir/Dialect/SPIRV/Transforms/SPIRVConversion.h"
#include "mlir/IR/TypeUtilities.h"
Functions
static void createElementWiseOp (ConversionPatternRewriter &builder, gpu::SubgroupMmaElementwiseOp op, spirv::CooperativeMatrixNVType coopType, ValueRange operands)
Function Documentation
createElementWiseOp()
static void createElementWiseOp (ConversionPatternRewriter & builder, gpu::SubgroupMmaElementwiseOp op, spirv::CooperativeMatrixNVType coopType, ValueRange operands) static
Definition at line 28 of file WmmaOpsToSPIRV.cpp.
References mlir::Attribute::cast(), mlir::convertMMAToSPIRVType(), mlir::OpBuilder::create(), mlir::failure(), mlir::Builder::getBoolAttr(), mlir::spirv::getElementPtr(), mlir::Builder::getI1Type(), mlir::Builder::getI32Type(), mlir::OpConversionPattern< SourceOp >::OpConversionPattern(), mlir::RewriterBase::replaceOpWithNewOp(), and mlir::success().